### ISSUE TITLE
Labels of some buttons are unreadable on linux

### ISSUE THREAD

**Issue by glaubersm** [BiglySoftware/BiglyBT#1002]
OS and version linux, Arch Linux
For *nix: Desktop Environment KDE Plasma 5.15.4
Java 10.0.2 (64 bit)
Oracle Corporation
/usr/lib/jvm/java-10-openjdk

SWT v4922, gtk/3.24.8, zoom=100, dpi=96
Linux v5.0.7-arch1-1-ARCH, amd64 (64 bit)
B1.9.0.0/4 az3

Some buttons are unreadable on linux.
See the screenshots below.

![biglybt5](https://user-images.githubusercontent.com/15967631/56148504-ccec4680-5f80-11e9-90e4-e680a7731ed6.png)

"All" button below the search field is unreadable.
![biglybt3](https://user-images.githubusercontent.com/15967631/56148505-ce1d7380-5f80-11e9-8e1f-2619de2ecca9.png)
![biglybt2](https://user-images.githubusercontent.com/15967631/56148507-ceb60a00-5f80-11e9-88d8-cefdf9ddd0dc.png)
![biglybt](https://user-images.githubusercontent.com/15967631/56148508-ceb60a00-5f80-11e9-9253-5958646ea670.png)

**Comment by TuxPaper** [comment]
I'll check the All button, as we might do something stupid like force a color.  But for the other ones, they are using the standard disabled state for the buttons, so the problem might either be in the KDE theme and how the library SWT uses it. It's possible SWT has fixed it up, but I can't remember if they build a Linux Arch version or we just found one somewhere on the internet :P

**Comment by glaubersm** [comment]
The buttons are also unreadable on Gnome 3.32.
I use swt 4.6.3 installed from Arch repositories.

**Comment by ferdnyc** [comment]
For the 'All' button, that appears to be _very_ theme-dependent, but I'm also not sure BiglyBT isn't doing something wrong in the way it displays state. For instance, here's how those look on my system, stock Fedora 29 Gnome Shell with the default Adwaita theme.

Neither selected (oops, I caught the focus indicator on Tag 1, ignore that):
![image](https://user-images.githubusercontent.com/538020/56618105-97ce9c80-65ef-11e9-9461-f3e9158655bf.png)

Tag 1 selected:
![image](https://user-images.githubusercontent.com/538020/56618127-a7e67c00-65ef-11e9-9f77-e845a7d4a6f4.png)

Tag 2 selected:
![image](https://user-images.githubusercontent.com/538020/56618148-b59c0180-65ef-11e9-901b-b240525f3fee.png)

I mean, don't get me wrong, I'll take it over unreadable labels, but I'm _pretty_ sure the state is supposed to be more visible than that.

My suspicion is, the button state is _expected_ to be shown with a color fill that's not happening. And in @glaubersm 's theme, I further suspect that fill color is supposed to be a darker / deeper one, such that the white text would be more visible. Hence the text color change.

That may also explain the dialog controls, because if you look at this image [from the GNOME 3 HIG](https://developer.gnome.org/hig/stable/buttons.html.en):

![image](https://user-images.githubusercontent.com/538020/56618348-52f73580-65f0-11e9-868d-bfc7e16f48aa.png)

You can see both the selected-button fill that's missing in my screenshots, and the blue "Suggested" action coloring that's probably missing from the dialog-window buttons in @glaubersm 's screenshots.

**Comment by ferdnyc** [comment]
Hah! In fact, here's Open Torrents on my system under 1.9.0.1_B13.

![image](https://user-images.githubusercontent.com/538020/56619137-9488e000-65f2-11e9-9f27-34c2cbc784c2.png)

Now, I'd previously tested that under 1.7.x.x (my install was behind) before I let it auto-update, and I don't recall it doing the same thing. So that may be a recent change. I'll try to go back and double-check that, if I can.

Note also that not all dialogs are affected the same way. Here's the dialog that results from clicking Properties > Trackers in the context menu of a tag row, in Tags Overview: 

![image](https://user-images.githubusercontent.com/538020/56619251-ed587880-65f2-11e9-878a-38351b0cfa38.png)

That is, I suspect, how Open Torrents is meant to look as well.

**Comment by ferdnyc** [comment]
And the same two dialogs in 1.9.0.1_B12, on the LXDE desktop of the system that I use as my BiglyBT "daily driver". 
![image](https://user-images.githubusercontent.com/538020/56619480-9d2de600-65f3-11e9-84be-07673bae4f62.png)

![image](https://user-images.githubusercontent.com/538020/56619450-8dae9d00-65f3-11e9-96d2-3cd02054e2db.png)

So, it's definitely a theme thing, to an extent. But BiglyBT doesn't appear to always respect all of the theme parameters in the same way.

(Oh, and the "Selected button for 'Tag Buttons in Library' feature is practically undetectable" thing, that happens on LXDE as well, and has been... forever, really, I think ever since the buttons were first added. Or it happened in the switch to GTK3.)

**Comment by ferdnyc** [comment]
So, as far as the dialogs go...

Near as I can _tell_, dialogs like "Update Property" are instances of `SimpleTextEntryWidget`. It uses `Utils.createOKCancelButtons` to set up its actions, which is just two calls to `createAlertButton` (in different orders, because Mac gotta Mac). That method instantiates standard SWT Button objects of type `SWT.PUSH`, and everything's fine.

https://github.com/BiglySoftware/BiglyBT/blob/5b4ea5cacea689dfad4d8ee93f9fb33a60192d02/uis/src/com/biglybt/ui/swt/SimpleTextEntryWindow.java#L288-L298

`SimpleTextEntryWidget` also eventually gets around to calling:
```java
	    shell.setDefaultButton(ok);
```
which presumably explains the blue styling. Other classes like `AdvRenameWindow` are the same.

But the `OpenTorrentsWindow`, that's built on a `SkinnedDialog` which is a whole 'nother animal.

https://github.com/BiglySoftware/BiglyBT/blob/d58fc13579a8fda5bf7724d7bc9963092f159bed/uis/src/com/biglybt/ui/swt/shells/opentorrent/OpenTorrentWindow.java#L105-L110

It goes through some complicated stuff involving styles/skins (I think?), but eventually ends up calling the `swt_createButtons` method of its `StandardButtonsArea buttonsArea`. That does _more_ complicated stuff laying out and ordering the buttons, including the `def_button`, but never actually _calls_ `setDefaultButton()`. That, a comment explains, gets deferred to a `shellActivated` listener, **#BecauseWindows**:

https://github.com/BiglySoftware/BiglyBT/blob/d58fc13579a8fda5bf7724d7bc9963092f159bed/uis/src/com/biglybt/ui/swt/views/skin/StandardButtonsArea.java#L212-L219

I don't know that that's the _problem_, but it's definitely a glaring **_difference_** in the two code paths.

**Comment by ferdnyc** [comment]
(To be clear, I don't necessarily think it's the deferred `setDefaultButton()` that's causing this. I think it's the "skinned" part of `SkinnedDialog`, which ends up styling the button _instead of_ the deferred `setDefaultButton()` call.)

**Comment by ferdnyc** [comment]
I should also mention, this _does_ only happen when using the system SWT. With the bundled version, the various dialogs look like this:

![image](https://user-images.githubusercontent.com/538020/56627558-5c929480-6614-11e9-99a9-7bad6e8cb15f.png)

![image](https://user-images.githubusercontent.com/538020/56627582-7502af00-6614-11e9-93e0-057fa4a372e2.png)

(...Exactly like my LXDE screenshots, in fact, which makes me think that version might be using the bundled SWT.)

Interestingly, though, even with the bundled SWT you can still see how the `SkinnedDialog` buttons have an unusual appearance. The "Add Files" and "Add Folder" buttons in the Open Torrents dialog have a gradient fill, and when you mouse over them the surface brightens. The "OK" and "Cancel" buttons in the `AdvRenameWindow` are the same. But the "OK" and "Cancel" buttons in the Open Torrents window are completely flat, and they offer absolutely no mouseover response. When you press them, they barely react at all — they look identical to the Tag Buttons from my first screenshots, in fact.

**Comment by TuxPaper** [comment]
This also looks suspect

https://github.com/BiglySoftware/BiglyBT/blob/d58fc13579a8fda5bf7724d7bc9963092f159bed/uis/src/com/biglybt/ui/swt/views/skin/StandardButtonsArea.java#L139-L141

**Comment by ferdnyc** [comment]
@TuxPaper Good call! I spotted that earlier, then promptly forgot about it. And you're right, commenting it out does indeed fix the OK/Cancel button styling in the SkinnedDialogs.

...Now I just have to go _remove_ the extra `setDefaultButton()` calls I added in two or different places (ineffectively), just to make sure they weren't _also_ needed. :roll_eyes:  (And maybe if I can see where the same trick is presumably pulled on the Tag Button styling as well.)

**Comment by ferdnyc** [comment]
Oh wow.
```console
$ grep INHERIT **/*.java
uis/src/com/biglybt/ui/swt/devices/DevicesWizard.java:		header.setBackgroundMode(SWT.INHERIT_DEFAULT);
uis/src/com/biglybt/ui/swt/devices/TranscodeChooser.java:		parent.setBackgroundMode(SWT.INHERIT_FORCE);
uis/src/com/biglybt/ui/swt/mdi/TabbedEntry.java:				parent.setBackgroundMode(SWT.INHERIT_NONE);
uis/src/com/biglybt/ui/swt/mdi/TabbedEntry.java:				parent.setBackgroundMode(SWT.INHERIT_NONE);
uis/src/com/biglybt/ui/swt/shells/MessageBoxShell.java:		shell.setBackgroundMode(SWT.INHERIT_DEFAULT);
uis/src/com/biglybt/ui/swt/shells/MessageSlideShell.java:			shell.setBackgroundMode(SWT.INHERIT_DEFAULT);
uis/src/com/biglybt/ui/swt/shells/opentorrent/OpenTorrentOptionsWindow.java:	parent.setBackgroundMode( SWT.INHERIT_FORCE );	// win 7 classic theme shows grey background without this
uis/src/com/biglybt/ui/swt/shells/opentorrent/OpenTorrentOptionsWindow.java:	parent.setBackgroundMode( SWT.INHERIT_FORCE );	// win 7 classic theme shows grey background without this
uis/src/com/biglybt/ui/swt/shells/opentorrent/OpenTorrentOptionsWindow.java:	parent.setBackgroundMode( SWT.INHERIT_FORCE );	// win 7 classic theme shows grey background without this
uis/src/com/biglybt/ui/swt/shells/uiswitcher/UISwitcherWindow.java:		c.setBackgroundMode(SWT.INHERIT_DEFAULT);
uis/src/com/biglybt/ui/swt/skin/SWTSkin.java:		skinComposite.setBackgroundMode(SWT.INHERIT_DEFAULT);
uis/src/com/biglybt/ui/swt/skin/SWTSkinObjectBasic.java:			//control.setBackgroundMode(SWT.INHERIT_NONE);
uis/src/com/biglybt/ui/swt/skin/SWTSkinObjectButton.java:			// Windows SWT Bug: button BG won't draw properly without INHERIT FORCE
uis/src/com/biglybt/ui/swt/skin/SWTSkinObjectButton.java:			createOn.setBackgroundMode(SWT.INHERIT_FORCE);
uis/src/com/biglybt/ui/swt/skin/SWTSkinObjectCheckbox.java:		createOn.setBackgroundMode(SWT.INHERIT_FORCE);
uis/src/com/biglybt/ui/swt/skin/SWTSkinObjectContainer.java:		// setting INHERIT_FORCE here would make the BG of a text box be
uis/src/com/biglybt/ui/swt/skin/SWTSkinObjectContainer.java:		//parentComposite.setBackgroundMode(SWT.INHERIT_FORCE);
uis/src/com/biglybt/ui/swt/skin/SWTSkinObjectToggle.java:		createOn.setBackgroundMode(SWT.INHERIT_FORCE);
uis/src/com/biglybt/ui/swt/subscriptions/SubscriptionsView.java:		composite.setBackgroundMode(SWT.INHERIT_DEFAULT);
uis/src/com/biglybt/ui/swt/subscriptions/SubscriptionWizard.java:		header.setBackgroundMode(SWT.INHERIT_DEFAULT);
uis/src/com/biglybt/ui/swt/subscriptions/SubscriptionWizard.java:		composite.setBackgroundMode(SWT.INHERIT_FORCE);
uis/src/com/biglybt/ui/swt/subscriptions/SubscriptionWizard.java:		compEmpty.setBackgroundMode(SWT.INHERIT_DEFAULT);
uis/src/com/biglybt/ui/swt/TorrentMenuFancy.java:		shell.setBackgroundMode(SWT.INHERIT_FORCE);
uis/src/com/biglybt/ui/swt/TorrentMenuFancy.java:		composite.setBackgroundMode(SWT.INHERIT_FORCE);
uis/src/com/biglybt/ui/swt/twistie/TwistieLabel.java:		setBackgroundMode(SWT.INHERIT_FORCE);
uis/src/com/biglybt/ui/swt/twistie/TwistieSection.java:		setBackgroundMode(SWT.INHERIT_FORCE);
uis/src/com/biglybt/ui/swt/twistie/TwistieSection.java:			setBackgroundMode(SWT.INHERIT_FORCE);
uis/src/com/biglybt/ui/swt/views/columnsetup/TableColumnSetupWindow.java:	cProficiency.setBackgroundMode(SWT.INHERIT_FORCE);
uis/src/com/biglybt/ui/swt/views/ConfigView.java:				curComposite.setBackgroundMode(SWT.INHERIT_DEFAULT);
uis/src/com/biglybt/ui/swt/views/MyTorrentsView.java:			cCategoriesAndTags.setBackgroundMode(SWT.INHERIT_FORCE);
uis/src/com/biglybt/ui/swt/views/skin/sidebar/SideBarEntrySWT.java:		parent.setBackgroundMode(SWT.INHERIT_NONE);
uis/src/com/biglybt/ui/swt/views/skin/sidebar/SideBarEntrySWT.java:		parent.setBackgroundMode(SWT.INHERIT_NONE);
uis/src/com/biglybt/ui/swt/views/skin/StandardButtonsArea.java:		// cButtonArea.setBackgroundMode(SWT.INHERIT_FORCE);
```

**Comment by ferdnyc** [comment]
(OK, only like _half_ of those are `INHERIT_FORCE`...)
```console
$ grep INHERIT_FORCE **/*.java
uis/src/com/biglybt/ui/swt/devices/TranscodeChooser.java:		parent.setBackgroundMode(SWT.INHERIT_FORCE);
uis/src/com/biglybt/ui/swt/shells/opentorrent/OpenTorrentOptionsWindow.java:	parent.setBackgroundMode( SWT.INHERIT_FORCE );	// win 7 classic theme shows grey background without this
uis/src/com/biglybt/ui/swt/shells/opentorrent/OpenTorrentOptionsWindow.java:	parent.setBackgroundMode( SWT.INHERIT_FORCE );	// win 7 classic theme shows grey background without this
uis/src/com/biglybt/ui/swt/shells/opentorrent/OpenTorrentOptionsWindow.java:	parent.setBackgroundMode( SWT.INHERIT_FORCE );	// win 7 classic theme shows grey background without this
uis/src/com/biglybt/ui/swt/skin/SWTSkinObjectButton.java:			createOn.setBackgroundMode(SWT.INHERIT_FORCE);
uis/src/com/biglybt/ui/swt/skin/SWTSkinObjectCheckbox.java:		createOn.setBackgroundMode(SWT.INHERIT_FORCE);
uis/src/com/biglybt/ui/swt/skin/SWTSkinObjectContainer.java:		// setting INHERIT_FORCE here would make the BG of a text box be
uis/src/com/biglybt/ui/swt/skin/SWTSkinObjectContainer.java:		//parentComposite.setBackgroundMode(SWT.INHERIT_FORCE);
uis/src/com/biglybt/ui/swt/skin/SWTSkinObjectToggle.java:		createOn.setBackgroundMode(SWT.INHERIT_FORCE);
uis/src/com/biglybt/ui/swt/subscriptions/SubscriptionWizard.java:		composite.setBackgroundMode(SWT.INHERIT_FORCE);
uis/src/com/biglybt/ui/swt/TorrentMenuFancy.java:		shell.setBackgroundMode(SWT.INHERIT_FORCE);
uis/src/com/biglybt/ui/swt/TorrentMenuFancy.java:		composite.setBackgroundMode(SWT.INHERIT_FORCE);
uis/src/com/biglybt/ui/swt/twistie/TwistieLabel.java:		setBackgroundMode(SWT.INHERIT_FORCE);
uis/src/com/biglybt/ui/swt/twistie/TwistieSection.java:		setBackgroundMode(SWT.INHERIT_FORCE);
uis/src/com/biglybt/ui/swt/twistie/TwistieSection.java:			setBackgroundMode(SWT.INHERIT_FORCE);
uis/src/com/biglybt/ui/swt/views/columnsetup/TableColumnSetupWindow.java:	cProficiency.setBackgroundMode(SWT.INHERIT_FORCE);
uis/src/com/biglybt/ui/swt/views/MyTorrentsView.java:			cCategoriesAndTags.setBackgroundMode(SWT.INHERIT_FORCE);
uis/src/com/biglybt/ui/swt/views/skin/StandardButtonsArea.java:		// cButtonArea.setBackgroundMode(SWT.INHERIT_FORCE);
```

**Comment by ferdnyc** [comment]
They weren't necessary. And hey, commenting out the one in `uis/src/com/biglybt/ui/swt/views/MyTorrentsView.java` means I can actually see which Tag Button I have pressed, for the first time! \o/

![image](https://user-images.githubusercontent.com/538020/56632714-1f84cd00-6629-11e9-92f3-3387bf76e527.png)

(I mean, it's still kind of **#TooSubtle**, but it's a hell of a lot better than before!)

**Comment by ferdnyc** [comment]
`SWTSkinObjectButton`, alone of all the source files, has a Windows-only wrapper around the places where it applies `SWT.INHERIT_FORCE`:

https://github.com/BiglySoftware/BiglyBT/blob/69c3e090f02d1ed738ac8c6c5de4842b96ca0fac/uis/src/com/biglybt/ui/swt/skin/SWTSkinObjectButton.java#L68-L78

But it's becoming clear, now, that _all_ of them should really be wrapped the same way. So far I've discovered that `INHERIT_FORCE` was also hiding the active tab indication, in the fancy menus. (With it, the entire tab line stays white at all times. Without it, the active tab turns gray.) There are other places where removing the `setBackgroundMode()` didn't seem to have any visible effect. But I have yet to find a place where it actually _is_ necessary and removing it causes a problem, on Linux.

**Comment by TuxPaper** [comment]
There might be some good use cases for setBackgroundMode on linux unrelated to buttons, but I'd have to check.  One thing I remember is, if I have a Composite with a Label on it, the label's background by default is painted, instead of left for the Composite to paint.  So if I change the Composite to green, the label sticks out with a gray box. I'm not sure if this is a Windows-only thing, or all OS thing, so I'd have to test it out.

**Comment by ferdnyc** [comment]
Hah! And after upgrading to Fedora 30 / BiglyBT 1.9.0.1_B15, the default button style has changed again, making the selected tag button even more readable. So, that's cool.

![image](https://user-images.githubusercontent.com/538020/57050523-f973b400-6c4a-11e9-9d9e-51ba694c283a.png)

**Comment by glaubersm** [comment]
This bug is fixed with BiglyBT 2.0 on my two systems.
Arch + Gnome 3.32.2
Arch + KDE Plasma 5.15.5

**Comment by ferdnyc** [comment]
@glaubersm (Feel free to Close this issue, since you're the reporter.)

**Comment by glaubersm** [comment]
Closing then.
Thank you all.
