### ISSUE TITLE
Low Disk Space with so many Torrent problem 

### ISSUE THREAD

**Issue by almozayaf** [BiglySoftware/BiglyBT#1061]
I set so many torrents on BiglyBT now my Win10 won't stop telling me that I have low space even that most the torrents are 0.00% !

I was thinking of few Solutions but need help with them 

1. **Delete the date some how!** Just keep the Torrent in the Download taqp and delet the info from the disk , How I don't know maybe Manual.

2. Back up all the .torrent  I search for a way to copy all the *.torrent files to another folder then used them again later 

3.  is there a way to add a torrent without taking a space before it start downloading for real ?

**Comment by PrototypeZero** [comment]
Under Options->Files check the "Use sparse files when supported by the file system", this won't save space already allocated but helps newly allocated files (usually at the cost of fragmentation of the said files).

But the real solution is to make more space by either getting more storage or moving stuff elsewhere (and also not to have so many torrents active at once!).

For (1.) quickest way is to delete to torrent and unselect "delete torrent file" on the confirmation.  If you've set a save location (below) the torrent file will there, double click on it to add it back when you like (Bigly will complain you've already downloaded it but will let you add it).


For (2.) enable Files->Torrent->"Save Torrent Files" and point it to where you want to save them.

For (3.) just add the file in a stopped state, Use Files->"When opening a torrent, show options dialog" set it to always and set it to instead of queued.
