### ISSUE TITLE
Any way to totally limit the client to I2P OR Tor or only I2P AND Tor?

### ISSUE THREAD

**Issue by IITFA** [BiglySoftware/BiglyBT#1098]
I am a total noob with BiglyBT. Literally just grabbed it a few minutes ago for testing and there seems to be no documentation or examples anywhere?

Usage scenario: A user wants to use the client ONLY on anonymous networks (I2P/Tor), how would they set it up so that there is zero clearnet traffic (all traffic forced to go through I2P and/or Tor) except for maybe updates to the client itself and plugins.

How would a user do this?

**Comment by parg** [comment]
There's the Help -> About dialog which gives you some links - e.g. https://github.com/BiglySoftware/BiglyBT/wiki

As BiglyBT is the evolution of Vuze you can also get useful information from the Vuze wiki.

If you want to force downloads through I2P then set the download's network to I2P only. Tor isn't recommended for torrent data.

There is no 'force all data through X' in general, if you want that then I would recommend a solution outside of BiglyBT such as setting up a VM and routing at the network level.

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
You can configure it to not do anything directly.

> As BiglyBT is the evolution of Vuze you can also get useful information from the Vuze wiki.

yes, basically here to find:

https://wiki.vuze.com/w/Proxies_And_VPNs#SOCKS_Proxy_Configuration
https://wiki.vuze.com/w/UG_Options#Connection_options
https://wiki.vuze.com/w/I2PHelper_HowTo
https://wiki.vuze.com/w/I2P_HowTo_(Deprecated,_see_I2PHelper_documentation)

But no DHT except I2P only DHT can be used in this case (UDP). No µTP Plugin Transport, No UDP Peer data. No public UDP Tracker except http/-s tracker possible through proxy. Plugin and Updates can go through both of them too. Tor isn't recommended for torrent data from torproject itself, only because of clients that still do leak your public IP over anonymously connection.

Put back `Tor `into `Torrent`.

Sadly the torhelper plugin doesn't give you the incoming connection availability with onion services yet like the very final I2P does give you by making client on b32 address connectable through it.

A Step by Step documentation section in wiki for a user wants to use the client on anonymous networks (I2P/Tor) only might would be increasing this users base.

Well there is two usecases actually? Only on anonymous networks versus that and any additional clearnet traffic forced through them i think.
