### ISSUE TITLE
any character in url will stop downloading the link FROM RSS/feed

### ISSUE THREAD

**Issue by Artbabe** [BiglySoftware/BiglyBT#1131]
when a file name contains character , in rss/feed , like 

{content removed}

Bigly can not download the url

this is a known bug which many clients fixed it

Thank you

**Comment by PrototypeZero** [comment]
Not doubting you, but I've downloaded many torrents with "exotic" characters in their folders, filenames and torrent names and have never had a problem (except for very occasional misinterpretations of UTF-8 IIRC).

You tried experimenting with options in "Options->Files->Decoding Character Sets"?  Personally usually have nothing selected there and Default set to "None".

What character exactly is causing this?  Any links to this "known bug"?

**Comment by Artbabe** [comment]
hello
thank you for reply
You can count on my report
a friend who saw my case ,asked me to report it here
in my case ,its always " ' "

it just missed these:

No Man's Land 2019 HDRip
No Man's Land 2019 1080p AMZN
Angels' Alley 1948 DVDRip
Dead Man's Curve 1998 DVDRip
Outlaws Don't Get Funerals 2019 HDRip
Outlaws Don't Get Funerals 2019 1080p AMZN
Men Don't Leave 1990 DVDRip
Don't Drink the Water 1994
Gulliver's Travels 1996
The Night Won't Talk 1952
Where There's a Will 1955
Man from God's Country 1958
The Queen's Corgi 2019 720p
For Heaven's Sake 1950
The Queen's Corgi 2019 1080p
The Queen's Corgi 2019 1080p BluRay
There's Something About a Soldier 1943

**Comment by parg** [comment]
Please give an exact example of a failing link (e.g. http://a.b.c/My's%20URL%FAILS.torrent) and the exact place within Bigly that the problem is occurring (subscription, manually entered in search box, subscription...)

To be legal in a URL many non-basic characters need to be URL encoded. For example, a space should be encoded as %20 - https://www.w3schools.com/tags/ref_urlencode.asp

**Comment by Artbabe** [comment]
sorry for late
I own an alexa 2000 site 200k uniq ip/day from usa/UK and it leaves me , not much spare time ,
about giving you exact link:

I only add private trackers to rss/feed
I can't give you the exact link
but
open ipt

whatever CMRG or DVDRip or [some categories  which don't remove " ' "
you see which have " ' " , are the item I mentioned

Bigly can't download them

I'll Take You There 1999 DVDRip XViD
https://iptorrents.com/download.php/3428696/I&#39;ll Take You There 1999 DVDRip XViD.torrent?torrent_pass=whatever

No.Man's.Land.2019.HDRip.AC3.x264-CMRG
https://iptorrents.com/download.php/3426171/No.Man&#39;s.Land.2019.HDRip.AC3.x264-CMRG.torrent?torrent_pass=something


that &#39;  is '
the tracker I use , is NOT ipt but , almost all the private trackers which I use , have this issue

.........

a very known programmer asked me to come and ask you to solve this problem

**Comment by PrototypeZero** [comment]
Well the links you give do get an error response from the server, but that's almost certainly because the content is for registered users only.  Bigly doesn't even get a chance to load them for me.

So unless you could provide either a public example link elsewhere, I'm afraid I can't look any further.

p.s. I've just tried a number of torrent links containing ' expressed as ' or &#39  in the torrent filename and didn't see any problem with bigly "picking them up", so I'm sorry I don't know exactly what is causing you problems.

I'll leave this to you and Parg.

**Comment by parg** [comment]
I'd love to look into the issue but as PrototypeZero says, those links don't really help. Please feel free to email links that you know should work to paul@users.sf.net and I'll explore more!

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
sample:

![image](https://user-images.githubusercontent.com/46166740/60548856-7262bb00-9d23-11e9-9626-b29d2fa62fd0.png)

**Comment by parg** [comment]
You're telling me you can download that .torrent file in a browser using exactly that link?
