### ISSUE TITLE
BiglyBT Leap for linux

### ISSUE THREAD

**Issue by legacychimera247** [BiglySoftware/BiglyBT#115]
i was a long time vuze user but some time ago i left the app for Transmission because i didn't like the direction vuze was taking, in the meantime i switched over to linux where java is more of a resource hog than windows...i was really happy when BiglyBT was out and with with linux support day 1, but unfortunately it still eat too much ram in linux for my old 3 gb...what about creating a BiglyBT Leap client (like Vuze Leap)?i know it's not powerful as biglybt classic but it would be a nice idea for those who have less ram but still want the power of bigly/vuze under the hood...

**Comment by parg** [comment]
How much ram would you consider reasonable....?

**Comment by legacychimera247** [comment]
a premise first, i am not criticising your work at all, i love your idea and the app you are giving us...just to clarify... :)

now, i am no coder and i don't know how much ram would be reasonable...as i've already said i've made various tests and biglybt eats lot more ram than the others...for example, deluge uses 60 mb of ram after 20 minutes with 4 active torrents, while BiglyBT after an hour may use even 350 mb and growing with just 2 active torrent...i don't know how much ram would be reasonable but i can feel that after some time of biglybt usage the pc feels sluggish, until i close the app, and by the way, system monitor tells me is using even more ram than the gnome shell itself...and maybe something could be done about it...

**Comment by parg** [comment]
Thanks :) The main memory usage comes from the Java virtual machine infrastructure rather than the BiglyBT code itself - unfortunately the benefits of being able to write code that runs (fairly) unmodified on Windows, OSX, Linux and Android comes with the overhead of the JVM. There's not much we can do to reduce it although you could peg the heap to 64MB and make sure you're not running the I2P plugin to reduce things a bit.

Vuze Leap was actually nothing to do with the Vuze developers, it was built by a separate team and is just a simple UI on top of libtorrent.

**Comment by legacychimera247** [comment]
don't think it's a real solution since i tried setting the heap on 128 yesterday...the app was somewhat slower, still after 30 minutes i was at 250 mb used...shame java on linux is really that crap...

oh and shame even on vuze leap then :P

**Comment by TuxPaper** [comment]
Closing as we'll never have a BiglyBT Leap
 (╯°□°）╯︵ ┻━┻
