### ISSUE TITLE
Private tracker issues.

### ISSUE THREAD

**Issue by fusk-l** [BiglySoftware/BiglyBT#1166]
Staff from a private tracker contacted me and said biglybt is generating events and reports from unusual actions which makes the client appear suspicious. Tracker uses multiple announce url's.
I don't know what that could be, and hoping it makes more sense to you would that might be.

I had opted in for the beta program, and therefore don't know if there were changes to tracker behaviour from 2.0 to beta.

**Comment by parg** [comment]
Nope, nothing changed. 'appear suspicious' isn't much use - can you find out more of their concerns?

**Comment by fusk-l** [comment]
They don't want to spend time on it, the only info i managed to get was. 
"that client reports wrong speeds to the tracker which flagged our Anti-Cheat System. Usually this happens when DHT, PEX are enabled."

And those were off in my case. I hope that helps, even if just a bit.

**Comment by parg** [comment]
Clients don't report speeds to trackers, they simply report the amount uploaded/downloaded in the current 'session'.

If the tracker uses private torrents (which it has to if it expects any kind of control over them) then PEX and DHT are automatically disabled.

Oh well.

**Comment by SUCM** [comment]
just some thoughts. some of these PT uses NexusPHP to run PT and NexusPHP seems to come with some tests to check whether a given BT client is true and accurate. perhaps some of those tests or the tests PT staff developed on their own see something suspicious from Bigly? otherwise, most of them allows Vuze, so Vuze probably passed the tests

**Comment by parg** [comment]
Or the PTs have the clients they like and don't have the time to consider others. 

So far no PT that has banned BiglyBT has given an objective reason as to why - if they had one then I would address it.

**Comment by SUCM** [comment]
the latest one I heard is that some feature of BiglyBT conflicts with accuracy of upload/download tracking and anti-cheat mechanism. no other details were provided, so not sure how/why/what feature conflicts

**Comment by parg** [comment]
Exactly, there are never any details...

**Comment by SUCM** [comment]
well, I would imagine with things like [this](https://www.nulled.to/topic/708995-biglybt-extreme-mod-1900-bittorrent-leecher-client/) and  [this](https://hellwich.nl/shu/forums/viewtopic.php?f=34&t=2127) in the wild. it's wise to not expose how and what you can detect as cheating/abusing. as a result, we suffer from insufficient info as well

**Comment by parg** [comment]
You mean things like https://ratioghost.com/ and https://www.sb-innovation.de/showthread.php?33029-RatioMaster-Plus-2-1  ?

**Comment by SUCM** [comment]
yup, except those simple ratio cheating similar to ghosting can be caught easily in the PT world. there are some cheating that's probably very hard to catch due to limited torrent protocol and PT staff most likely develop their own secret sauce over time to try to catch the more sophisticated cheating

back in ed2k days, many mods are for adding extra security, stability, fairness and banning the bad/fake peers. in BT world, it seems to be the opposite

**Comment by parg** [comment]
If the PTs are that clever then they can work out how to spot BiglyBT mods pretending to be other clients, can't they?

**Comment by SUCM** [comment]
don't know how clever PTs are. was just saying those qB, uTorrent and Bigly/Vuze mods could the reason why PT don't give out sufficient details. so the client mods can't learn how to dodge the detection mechanism. in any case, I still don't know why Bigly failed the test for some PTs but Vuze doesn't

**Comment by parg** [comment]
NOBODY KNOWS! Anyway, nothing can be done about those mods - open-source is good right?

**Comment by SUCM** [comment]
don't think open source is the problem. even the closed source uTorrent has quite a few cheating mods. quite a few newer versions of uTorrent are also banned too

the official qBittorrent releases have been adding feature/behaviour where PTs take as bad reporting, so newer version of qBittorrent are also banned as well

though PT users have been filing bugs asking qBittorrent to fix the problem to get unbanned, I'm not knowledgeable enough to know whether Bigly can pick from qBittorrent's current situation to figure out the part that is failing PT's test

**Comment by as-muncher** [comment]
> Clients don't report speeds to trackers, they simply report the amount uploaded/downloaded in the current 'session'.
> 
> If the tracker uses private torrents (which it has to if it expects any kind of control over them) then PEX and DHT are automatically disabled.
> 
> Oh well.

Will BiglyBT still swarm merge with a privately tracked torrent?  I definitely would want it to.  I've got a few such torrents, and because my sharing ratio is so low, I can't get downloading to happen.  I want to share, sharing at full speed, not 5 kb/s, but need the files first.  I would be happy to share these files to the world, too, and would wand the torrent to show up on some bittorrent database (know of some good ones?).  I would love if biglybt shared them with whomever and shared those files to me from wherever.  Could you get back to me about that please?

**Comment by parg** [comment]
The swarm merging process in-client will works with any downloads. What won't happen is the discovery of private torrents that are potential swarm-merge candidates. That is because they are PRIVATE!
