### ISSUE TITLE
Android Freezes While Hard Disk Space is being Allocated

### ISSUE THREAD

**Issue by noamgat** [BiglySoftware/BiglyBT#1278]
* OS and version
Fire TV Stick 4K (Android TV)
* BiglyBT Version Number
Latest Android from Google Play (As of 2019/09/30)
* For *nix: Desktop Environment

I set up BiglyBT on my Fire Stick, set the download directory to be an attached USB Pen Drive, to bypass the low storage capability of the fire stick.
It works, but after adding a torrent, I think the client preallocates all of the storage required for the torrent. This would be fine, however the entire fire stick 4k is not responsive during this time, nor is the web interface on LAN.
Is there any way to get this work in a more stable way?

**Comment by ferdnyc** [comment]
The 4K doesn't have expandable storage, so you're probably using an OTG splitter cable to attach the storage device, yes?

There are numerous reports 'round the web of freezes and hangs when accessing USB-OTG connected storage, unfortunately — not too surprising, really, since the stick has to use the same port to communicate with both the storage device and its host device (TV). Not sure if they can really do anything about the hangs when writing large amounts of data. The preallocation that causes it, _maybe_?

You're probably correct that BiglyBT is preallocating storage — I know that when torrent downloads are stored on FAT32, there are restrictions on how received data can be managed. FAT32 doesn't support all of the block-allocation and -management algorithms BiglyBT normally uses. Not sure if it'd be safe to turn that off, though IANADeveloper so don't take anything I say as official. (Or even necessarily all that well-informed, I've never dealt with set-connected devices like the Fire Stick.)

**Comment by noamgat** [comment]
Thanks for the response. It is indeed a USB-OTG, and that may be the issue.

**Comment by ferdnyc** [comment]
@noamgat Even though it's pure coincidence and wasn't intentionally targeted to your situation, the 2.1.0.2_B22 beta build of BiglyBT brought a new feature that _might_ theoretically be of some help to you:

**Option to download to temp folder and move to original dest when done** (  8b09a9ce2bb9eb3717b4fed8d16423c050a2e461 )

If there's _any_ internal storage at all available on your Fire Stick, enough to use as just a temporary working directory for _active_ downloads, then it's possible setting things up that way and only pulling in the USB-OTG storage device once the torrent has completed transferring might bring some relief from the freezing issues during storage access.

(Or at the very least, it might save you from having to wait on a tedious, disruptive preallocation run over external disk sectors that you _know_ are all going to end up getting re-written with the file's actual contents anyway.)

**Comment by FakeJoe** [comment]
Don't think it is related to OTG, I have Nvidia Shield 2017 with 250GB external SSD drive attached to it.
Exactly the same thing happens to it when I start new torrent. Freeze time is proportional to the size of downloaded file.
I know BiglyBT has many settings, especially in advanced mode, is there a setting disabling allocation on start?
And why BiglyBT does that? Never seen other torrent apps did that...
