### ISSUE TITLE
Feature Request: Option: Seeding / Ignore Rules: Ignore torrents with less than X downloaded

### ISSUE THREAD

**Issue by Farxial** [BiglySoftware/BiglyBT#1319]
There are situations when the user downloads only a very small part from the whole share, and there is no reason to try to seed it.
X may be flexible. For example, for share of hundreds GBs even few percent is valuable, but not <1% for few GBs share (if the share has other seeds, of course).

**Comment by parg** [comment]
You can create a Tag with a constraint of (say) "isComplete() && downloaded < 10mb" and then set its 'execute on assign' action to 'stop'

**Comment by parg** [comment]
Here's some input from the BiglyBT beta chat - chat:?BiglyBT%3A%20Beta%3A%20Chat

[02:24] Droo
In response to Mr Farxial of GitHub (Issue 1319).  Can I suggest instead of stopping the torrent just set the upload to a low rate in the tag with constraints say:
share_ratio>1 && percent <1
[02:31] Droo
Improved constraints so it dosn't go slow straight away:
share ratio>1 && percent <1 && downloading for>h2s(6)
[02:39] Droo
...and dopn't slow if no seeds:
share ratio>1 && percent <1 && downloading for>h2s(6) && seed_count>1
