### ISSUE TITLE
Feature Request: Download to temporary location, copy when finished

### ISSUE THREAD

**Issue by Flole998** [BiglySoftware/BiglyBT#1333]
I am downloading from Windows to a Share on a Linux Server running SMB but I am not even getting close to the maximum speed of my connection. When I download to a local HDD this doesn't happen. I would need an option to specify a temporary download path where everything is downloaded to until its finished, then it's moved and seeding will be from the new Location which should be the destination specified by the user, so basically the "Move finished files" option but "the other way around" so unfinished files are moved to my local HDD, downloaded and then moved over to the Linux Server.

I'd really appreciate it if someone has some time to look into this so I could get faster downloads.

**Comment by parg** [comment]
Not sure I understand why the existing 'move on complete' feature doesn't do the job for you - just set the default download location to a local folder and then 'move on complete' them to the network drive. If you already have files being downloaded to the network folder then manually move them to the local folder by right-clicking on them and selecting Content->Move Data Files...

Hmm, perhaps I understand - is it that you are selecting different 'destination locations' for each download? If there is a pattern to this (i.e. there is one of 'n' destinations you normally select) then you could set up 'n' Tags with the various per-tag move-on-complete set appropriately, then assign the appropriate tag when adding the download in the add-torrent-options dialog. Not ideal but something that might work.

**Comment by parg** [comment]
Oh, and there's also an option to set explicit move-on-complete when adding a download in the open-torrent-options-dialog (far right of the save location stuff, under the 'more' menu)

**Comment by Flole998** [comment]
> Oh, and there's also an option to set explicit move-on-complete when adding a download in the open-torrent-options-dialog (far right of the save location stuff, under the 'more' menu)

Thats exactly what I need! Just unfortunate that it's a little "hidden". Does the "guessing" of the File path still work for that? Also is there any way to "swap" them so specifying the target location is possible in the field where currently the "temp" location is specified? Then it'd be perfect and exactly what I need.

**Comment by parg** [comment]
Hmm, I'll think about adding a separate option - that dialog is a bit overloaded...

**Comment by parg** [comment]
Beta version B22 is out with a new option under Tools->Options->Files->Completion Moving

Please test and see if it does what you want.

**Comment by FinlayDaG33k** [comment]
I've come across this issue since I've ran into the same problem (Bigly 3.4.0.0 on W10).
I've set the option in `Completion Moving` but sadly, it still allocates and downloads directly to the "real" target rather than even bothering to download to the "temporary" target.

So:
- Expected: Download to `E:\BiglyBT Torrents\downloads` first then move it to `W:/folder/file.ext`.
- Reality: Bigly downloads directly to `W:/folder/file.ext`

![afbeelding](https://github.com/BiglySoftware/BiglyBT/assets/13424273/525b8ca5-4002-48a8-90f8-7a5ea6cc5d52)

**Comment by parg** [comment]
Hmm, Works For Me (tm)

Check the DiskOps_1/2.log files in the "logs" folder, it should have a few clues about what is going on.

**Comment by FinlayDaG33k** [comment]
In the `DiskOps_1.log` I found the following lines:

```
[23:19:43] addDownload: [HASH]: isMagnet=false
[23:19:43] createNewDownload: starts for [HASH], E:\BiglyBT Torrents\[TORRENT].torrent,E:\BiglyBT Torrents\downloads, null
[23:19:43] createNewDownload: [HASH]: isMagnet=false, newIsMagnet=false
[23:19:43] addDownloadManager: [HASH]: actually adding
[23:21:47] Torrent target for "[FILENAME]" with regard to "Download-specific Move on Completion" is not enabled.
[23:21:47] Determined path for "[FILENAME]" with regard to "Download-specific Move on Completion" - W:\Anime\[FOLDER];null.
[23:22:15] Move active "[FILENAME]" from  E:\BiglyBT Torrents\downloads\[ORIGINAL FILENAME] to W:\Anime\[FOLDER] starts
[23:22:15] File linkage prohibits move: W:\Anime\[FOLDER]\[FILENAME] / E:\BiglyBT Torrents\downloads\[ORIGINAL FILENAME]
[23:22:15] Move active "[FILENAME]" from  E:\BiglyBT Torrents\downloads\[ORIGINAL FILENAME] to W:\Anime\[FOLDER] (files accepted=0, skipped=1, done=1; bytes total=0, done=0)
[23:22:15] Setting completion flag on "[FILENAME]", may have been set before.
```

Replaced the actual filenames and folder names with placeholders just to be safe.

I wonder, since it mentions the `file linkage prohibits move`, may it have to do something with `W:` being a network drive and `E:` being a local drive?

**Comment by parg** [comment]
From that log it appears that it downloads it to the temporary directory (E:\BiglyBT Torrents\downloads) and then fails to move it to the target (W:\Anime\[FOLDER]) ? 

Your original post said that it ignored the temporary directory and download it directly to W:\Anime\[FOLDER]

Does this problem only occur with "simple" torrents - i.e. those containing a single file rather than multiple files?

Are you in any way altering the download, for example renaming a file?

The reason I ask is that the "download to temporary location and then move to target" feature is implemented by using the "move on complete" feature in biglybt - the initial download location is amended to the temporary one and then "move on complete" is used to move it when it finishes.

"move on complete" is sensitive to file links (this is used when renaming a file for example) - it doesn't like moving files that appear to have been linked to unexpected locations, hence the "file linkage prohibits move" log.

**Comment by parg** [comment]
Reproduced this when I rename the file...

**Comment by parg** [comment]
If you try the latest beta (3401_B05, see the Help menu to join the beta program) then it is hopefully fixed

**Comment by FinlayDaG33k** [comment]
> If you try the latest beta (3401_B05, see the Help menu to join the beta program) then it is hopefully fixed

Currently getting a read time-out when trying to use the updater.  
Will try again later tonight.
![afbeelding](https://github.com/BiglySoftware/BiglyBT/assets/13424273/3acd27bc-746f-44c1-b975-97ff99c4667e)

**Comment by FinlayDaG33k** [comment]
Downloaded `3401_B05` and can confirm this fixed the issue for me.

**Comment by parg** [comment]
Great :)
