### ISSUE TITLE
Tag "View In Sidebar" Setting Also Controls Showing of Tag Filter Buttons

### ISSUE THREAD

**Issue by brazenvoid** [BiglySoftware/BiglyBT#1347]
Just discovered this unexpected issue; the view in sidebar setting should just control the tag button shown in the sidebar but it also controls the tag filter buttons in the library views. 

Meaning that I have to live with them being shown in the sidebar to have them as torrent filter options... 

In the pics, all the "Seed for *d" tags are set to not show in sidebar.

![Annotation 2019-11-12 204429](https://user-images.githubusercontent.com/8722533/68686674-cd3bd700-058d-11ea-9317-148088d401d9.png)

![Annotation 2019-11-12 204428](https://user-images.githubusercontent.com/8722533/68686677-cd3bd700-058d-11ea-8132-c86a497a4ceb.png)

Please either rephrase the option or add another to hide it as a filter option.

* Windows 10 1903 x64
* BiglyBT Beta v2.1.0.1 B24

**Comment by parg** [comment]
If you don't want them in the sidebar then you can turn all tags off via 

Tools->Options->Interface->Tags

Alternatively you could put them all into a 'Tag Group'  and have that collapsed in the SideBar.

Not ideal I know

**Comment by brazenvoid** [comment]
Why does it seem that the above option's function does not strike you as misleading though I do understand that the function of the sidebar option is also another kind of filtering but still it should not be linked to the filter options in library views.

Also your solutions can be good for someone desperate, I only wanted to point out the issue. 
My use case is just to hide the tags that I am using as comments or indications for future actions.

**Comment by parg** [comment]
It is misleading, I didn't say it wasn't :) It is a historical thing, when tags were originally developed there weren't any filter buttons, there was just 'visibility in the sidebar'. When filter buttons were added the visibility was inheritted but the option wasn't renamed.

I suppose the best solution would be to create a 'visible as filter' option independent from the existing (global) visibility.

**Comment by brazenvoid** [comment]
Yes it would. You will have my thanks, if you choose to do that.

I don't know but I still get the vibe that the tag system must either be an archaic piece of software or just too deep inside with many unknowns that you seemed reluctant at first... though it would be perfectly understandable if so :)

**Comment by parg** [comment]
heh, nah, it is more that if people are generally happy with the way things are (or don't bother complaining) then they tend to stay that way :)

**Comment by parg** [comment]
Added a tag setting to mark it as a 'filter' tag and also one to Interface->Tag to restrict tags shown in the Library to only be ones marked as filters. 

Doesn't change things for existing users but at least gives control for those that might want it.

**Comment by brazenvoid** [comment]
Ok so got the changes, and it does not work yet... 

Also I hope that the filter setting is not dependent on the View on Sidebar as then the convolution will only be transferred to another aspect. Though it should be set dynamically dependent on user's setting of View on sidebar to cater BC. I do not know of your update mechanisms, but I assume there should be some routine to handle such updates.

**Comment by parg** [comment]
It works under all my testing. When you set

Tools->Options->Interface->Tags:
     Show Tag Buttons in Library
     ---- Onlyshow Tags marked as Filters

both to 'checked' then only Tags that have had their 'Is Filter' property checked will be shown as buttons in the Library views.

**Comment by brazenvoid** [comment]
So there is a universal enabler now. Cool :)

**Comment by brazenvoid** [comment]
Though it should not show up if the "Only Show Tags marked as Filters" is not enabled, Otherwise someone else will come report the same issue again... Considering it does not do anything otherwise.

**Comment by ferdnyc** [comment]
> I don't know but I still get the vibe that the tag system must either be an archaic piece of software or just too deep inside with many unknowns that you seemed reluctant at first... though it would be perfectly understandable if so :)

Funny thing is, that's not really true at all. Tags are actually the New Hotness™, which _replace_ (or, augment) and greatly surpass the functionality of the previous, very limited Categories feature. (I say "augment" because Categories are somehow **_still there_** even though I was really hoping they'd finally die off with 2.0.0. There definitely **is** a massive amount of technical debt in BiglyBT's codebase, I don't think Parg or anyone else would deny that — it's just that Tags aren't part of that. :smile: )

If anything is old and crusty about all of this, it's the tag filter buttons, which despite @TuxPaper 's very nice visual refresh recently are nevertheless a holdover / reimplemented feature originally born with Categories, and sometimes they show the cracks of their evolutionary development process over the past 10+ years — has it really been that long!? actually I think closer to 15! — that they've been banging around the interface in one form or another or another or another.

Plus, things did go kind of wonky a little bit when tags were added to the sidebar. Because suddenly the visibility control _was_ co-opted to control their presence there, as well as the corresponding filter buttons, **AND** if you were using the classic interface, it _also_ (or, instead) controlled whether a **tab** was permanently opened for each visible tag (because there's no sidebar to show them in).

That sucked (tab real estate is valuable!) and ultimately drove me away from the classic interface for good, which was maybe the plan all along!

**Comment by brazenvoid** [comment]
Well you misunderstood, I meant exactly what you wrote in the second para and onward. I perceived the implementation as archaic, not the design nor goals.

**Comment by TuxPaper** [comment]
I'm not going to add anything useful to this conversation, other than to say "Show in Library" checkbox is not only outdated, but pretty useless ever since BiglyBT started remembering all sidebar entries across restarts (ie. once a tag view is in the sidebar, it would show up on restarts without any extra coding effort, if it wasn't for the "Show in Library" stuff taking over).  Someday I'll probably remove the checkbox all together.

**Comment by brazenvoid** [comment]
At these times I always have the urge to contribute. If I only had ever learned Java in my life... yeah... hard to believe I know...
