### ISSUE TITLE
I'd like to be more specific but the last update broke Bigly BT

### ISSUE THREAD

**Issue by MisterFixIt1952** [BiglySoftware/BiglyBT#1352]
Before the upgrade, I would typically get 4MB/s download, my network (max). Now I am lucky to get 7-20kB/s. On top of that, my Computer has bluescreened 3 times today withy Bigly BT active. I just added some fresh torrents from a frequently used source, which always start quickly and continue at close to the maximum until complete. Now, zip, nada, bupkis. The fastest thing that happens now is a bluescreen. Nothing else on my computer has changed except the update. I am picking up 0 seeds from new torrents from always active sites. My network analysis does not show any obvious problems and my VPN is functioning as normal. I just added a torrent from my subscriptions that says there are 1063 seeds & 304 peers. I'm getting 0/0

* Windows 7 premium
* BiglyBT Version Number
* Java 11.0.1 (64 bit)
  Oracle Corporation
c:\program files\java\jdk-11.0.1

SWT v4922, win32, zoom=100, dpi=120
Windows 7 v6.1, amd64 (64 bit)
B2.1.0.0/4 az3

**Comment by parg** [comment]
Bluescreens are usually caused by network driver issues, an application such as BiglyBT should not be able to cause an OS crash. Perhaps check the drivers are up to date? Nothing in BiglyBT has changed recently (or not so recently) that would change the fundamental way in which it uses the network.

If you go to a download's 'Sources' tab what is being reported by trackers? If you go the 'Peers' tab are you seeing any connection attempts?
