### ISSUE TITLE
Beta28 Very Slow Display Updates

### ISSUE THREAD

**Issue by brazenvoid** [BiglySoftware/BiglyBT#1354]
So the beta28 which just got installed has I guess made some changes to UI refresh/redraw calls. All UI updates are noticeably slower. 

The right click context menu is now slower by little over a second and this happens on entry, menu switch or exit sequence. It visibly gets drawn on the screen, I mean I can see the lines appearing and box getting drawn. 

When the app is opened from a minimized state, it now shows a black background first and then things get drawn on it. Previously there was never any black, though it did draw the screen again and I could for few moments see some drawing steps.

**Comment by parg** [comment]
Nothing changed regarding refresh rates - is it possible you are running low on (Java) memory? When that happens things can get sluggish due to increased garbage-collection activity.  If you want you could generate a 'debug.zip' file (Help menu, last option) and send it over to paul@biglybt.com - you might need to rename it to, say, debugzip, as some AV programs don't like .zip attachments.

**Comment by brazenvoid** [comment]
Yes it seems to have corrected itself, perhaps as you said due to GC activity.
