### ISSUE TITLE
Very slow moving files

### ISSUE THREAD

**Issue by Gatak** [BiglySoftware/BiglyBT#1407]
Hi!

Is there a way to improve the transfer speed when moving files between storage locations? I wanted to save some space and move some files to a NAS disk. If I copy/move the files with Windows Explorer I maximise the network speed (1Gbit). But if I right-click a torrent and choose `Content->Move Data Files` It is very slow. Only about 1/10th of the transfer speed. 

Is there a way to make BiglyBT use any available disk speed?
Would it also be possible to move files in the background, similar to file re-checks are done?

```
Java 12.0.1 (64 bit)
  Oracle Corporation
c:\program files\biglybt\jre

SWT v4922r17, win32, zoom=100, dpi=96
Windows 10 v10.0, amd64 (64 bit)
B2.2.0.1_B03/4 az3
```

**Comment by parg** [comment]
I think you can close the move-progress dialog (small-x on dialog header) and the move will continue in the background.

Unless you have enabled Tools->Options->File->Completion Moving: Copy and then delete the original data rather than move it in one operation

then there's not much you can do to speed things up within BiglyBT.

Worst case, stop the download, manually move the files to the NAS, restart the download (it'll go into an error state with 'missing data files') and use the 'Search for existing datafiles' context menu option to fix things up
