### ISSUE TITLE
Use the XDG configuration directory on Linux

### ISSUE THREAD

**Issue by ebourg** [BiglySoftware/BiglyBT#1432]
Hi,

Currently BiglyBT writes its configuration files in the `~/.biglybt` directory on Linux, it would be nice to support the [XDG directory layout](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) where the configuration files are written under `~/.config/biglybt` instead (or under the base path specified by the `XDG_CONFIG_HOME` environment variable if it's defined).

**Comment by TuxPaper** [comment]
Reminder to self: I think there's another Github Issue related to the startup script hardcoded to read a custom java.vmoptions file from `~/.biglybt/java.vmoptions`

**Comment by rindeal** [comment]
I don't think this is workable. BiglyBT currently stores all kinds of data in `~/.biglybt/`, while `XDG_CONFIG_HOME` is intended solely for small configuration files (plain-text preferably). The current `~/.biglybt/` would have to be split among all the standardized dirs, `XDG_{CONFIG,CACHE,DATA,RUNTIME}_HOME`, in order to be compliant. And even if the split was implemented for XDG-based platforms, it would have to be implemented for other platforms as well to keep things portable. The work needed is too great for little to no benefit.
