### ISSUE TITLE
Missing resources

### ISSUE THREAD

**Issue by ebourg** [BiglySoftware/BiglyBT#1433]
Hi,

It looks like several resources used by in the binary packages are missing from the git repository. For example the application icon (png and svg), the startup script on Linux, the `.desktop` file, etc. Would it be possible to add them please?

**Comment by ebourg** [comment]
The startup script is actually in `core/src/com/biglybt/platform/unix/startupScript`.

**Comment by TuxPaper** [comment]
I'll spend some time first pondering and discussing what directory structure to use in Github for these assets, and then throw them up.  If you have any strong opinions, or know of any standards path structures used by other linux, let me know.

We have a bit of a unique repository structure in that core and uis are separate, with UIs usually containing everything UI related.  Linux package support files are sort of both, so the first decision will be whether to put it in one of those two paths, or to create a new one in the github root.  My initial thought it to put it in root as something like `/assets/linux/*`

**Comment by ebourg** [comment]
I don't think there is a standard location for these files. For my projects I usually have a Maven module dedicated to the generation of the instalation packages. For BiglyBT we could imagine a `dist` module that generates the all in one jar (using the shade plugin) and creates the .exe, .dmg and Linux binaries. The images could go in `dist/src/main/assets`, and the scripts in `dist/src/main/scripts`.

**Comment by TuxPaper** [comment]
Yeah, we have a similar private repository for our installer builders.  Making it public isn't an option right now.  The amount of time it would take to assess which files can or should be public (ie. binaries, signing files, tools, blobs of embarrassing data or code) is far greater than the simpler solution of moving the linux assets to this public repo.

`/dist` might be a good name, though  `src/main` might be overkill for us :)  Still leaning towards `assets/linux` since I have non-dist assets I plan on adding someday.  Maybe even `assets/dist/linux` ;)
