### ISSUE TITLE
JSONJava is non-free

### ISSUE THREAD

**Issue by ebourg** [BiglySoftware/BiglyBT#1435]
The JSONJava class has a clause in its license that renders it non-free ("_The Software shall be used for Good, not Evil_", this is a field of use restriction that goes against the [Open Source Definition](https://opensource.org/osd)). This file can't be redistributed by Linux distributions such as Debian, Ubuntu or Fedora. It would be great to replace it with an alternative JSON implementation.

**Comment by TuxPaper** [comment]
Can we philosophically argue that good and evil are artificial constructs that change based on perspective, and what's evil to one person, is not evil to others, so, therefore, nothing is truly evil? :sweat_smile:

**Comment by TuxPaper** [comment]
arg, found a relevant link https://www.synopsys.com/blogs/software-security/json-license-limitations/

**Comment by TuxPaper** [comment]
fwiw, we use org.json.simple for most of our JSON needs. It's LGPL.
I believe JSONJava was added because it supported XML->JSON parsing.  It's used only by the "rssgen" plugin, so finding an alternative may not be too much of an issue.

I tried removing the RSSGen plugin source from BiglyBT, but unfortunately several places access it directly instead of grabbing it from the plugin interface manager and checking if it's there and enabled. 

However, the approach I'll be taking for the Android release will be to remove these lines [RSSGenerator.java lines 335-375](https://github.com/BiglySoftware/BiglyBT/blob/v2.2.0.2/core/src/com/biglybt/plugin/rssgen/RSSGeneratorPlugin.java#L335..L375) (and the import line), as well as [org/json/jsonjava folder](https://github.com/BiglySoftware/BiglyBT/tree/v2.2.0.2/core/src/org/json/jsonjava).  Note: this may make the plugin useless (I'm not sure)

Thanks for bringing this to our attention, especially since I'm working on an Android release soon and it needs to be FOSS.

**Comment by ebourg** [comment]
Thank you for looking into this.

**Comment by TuxPaper** [comment]
I made a simple replacement for our JSONJava usage (XML->JSON), which we'll be testing (next beta probably) for a while before removing the old one.
https://github.com/BiglySoftware/BiglyBT/blob/master/core/src/com/biglybt/core/xml/util/XMLConverter.java

**Comment by TuxPaper** [comment]
JSONJava no longer part of the newest release 2.3.0.0
