### ISSUE TITLE
Command Line Options to Control Start of BiglyBT in Windows?

### ISSUE THREAD

**Issue by ms52538** [BiglySoftware/BiglyBT#1461]
Hey Gents! 

I've been looking around, and may not have found the resource yet, but thought I'd ask: are the command-line options to control the initial start/launch of BiglyBT in Windows? I'm specifically looking for an option for setting all active torrents in "Forced" mode to NOT start on some occasions; i.e. having 2,500 active torrents in Forced Mode and set to start those in the options, there are times I want to shut down the client and restart it without having to wait 20 minutes for all of those 2,500 torrents to initialize and set active before I want to restart the client again. For example; let's say my PC hangs, I have to do a hard power reset, and I already know that some of my BiglyBT script files will be damaged or corrupted and I want to get into an immediate 'restore backup' sessions FIRST before the client attempts to restart Forced active torrents.

Thanks!

PS - I've not closed that last issue I raised (appreciate your looking into it and feedback), I'm waiting to see if I can duplicate the problem with the pop-up window gui going screwy.

:)

**Comment by parg** [comment]
There's no command line options to do that - you could try hitting the File menu's Transfers->Pause option to pause everything that is running. When you resume them via Transfers->Resume it remembers the 'forced' state of downloads from before so you get back to where you were.

**Comment by ferdnyc** [comment]
@ms52538 
The other thing you could do for that _specific_ scenario, honestly, is just do the restore-from-backup operation yourself, manually, by just copying all of the files from your most recent backup directory over the ones in your BiglyBT config directory.

Parg will correct me if I'm wrong, I'm sure, but my understanding is, that's really all BiglyBT's "Restore from backup" operation does anyway (effectively, at least). So, if it's not running (and you wouldn't ever want to do this if it _is_ running) and you know the only reason you need to launch it is to have it perform the restore operation, might as well just not even involve the application itself in the process.

I've had the same experience with corruption due to system freezes (a dodgy power supply was causing them regularly, for me), and I could guarantee every time that I'd need to restore from the most recent backup — I had them running every 4 fours, at one point — because my tags would all be lost due to the constant updating of `tag.config` (which virtually guaranteed file corruption on hang). So, that's what I was doing (the manual copying) before launch, and it worked well in my experience.

**Comment by parg** [comment]
The 'restore' process also deals with patching the config as needed to fixup a restore to a different folder location from where the backup was taken, along with handling the 'pause after restore' option if enabled. 

If you are restoring to the same place then a manual copy will do the job (as pointed out, obviously when BiglyBT isn't running!)
