### ISSUE TITLE
plugin not moved over

### ISSUE THREAD

**Issue by getuslocal** [BiglySoftware/BiglyBT#1490]
So I just updated my Vuse to this but the one plugin that I rely on shows a red dot next to it and I cant access. Please add this plugin.. its the only one that works. 

http://plugins.vuze.com/details/autocat

**Comment by parg** [comment]
I took a quick look and some things have changed that make porting it a bit of an effort.

What features of the plugin are you using? Tags support regular-expression auto assignment and other things so it may be possible to achieve what you want using them.

**Comment by getuslocal** [comment]
I use Tags to auto sort my auto RSS feed and downloads by file name.  

I entered a keyword, chose the tag I wanted and chose by file name. 



Thank You,



Venessa West

Business Consultant/Web Designer/Marketer

venessa@getuslocal.com

815-269-5111
 




ZohoUS Small Business Network

Facebook Group · 11 members



	Join Group


This is a new group for Zoho Users or those interested in learning more about Zoho and are located in the US. Use this group to ask questions, get ad...




---- On Mon, 10 Feb 2020 04:38:04 -0600 notifications@github.com wrote ----



I took a quick look and some things have changed that make porting it a bit of an effort.

What features of the plugin are you using? Tags support regular-expression auto assignment and other things so it may be possible to achieve what you want using them.

**Comment by parg** [comment]
You can match by file name with a Tag by

1) create a new Tag (button top right in View->Tags Overview)
2) click on the new Tag in the Tags Overview top table to show its settings below
3) go to the 'Tag Constraint' entry and add (for example) `contains( name, "linux", 1 )` - this will match any download name that contains 'linux' ignoring case (the third parameter, 1, means case-insensitive)

you can use `matches` instead of `contains` if you want to use a regular expression to match.

See https://github.com/BiglySoftware/BiglyBT/wiki/Tags#Constraints

Does this do what you need?
