### ISSUE TITLE
Changing JRE path for a Portable Install without launching directly from Java

### ISSUE THREAD

**Issue by zellchristensen** [BiglySoftware/BiglyBT#1513]
* Windows 7
* BiglyBT Version 2.2.0.2/4

Following the directions at ( https://wiki.vuze.com/w/Portable_Vuze ) for an attempted portable version, I installed using the Installer64_WithJava.exe but after copying the folder, the new version always references the absolute path for the JRE during the original install ( C:\Program Files\BiglyBT\jre\bin\ ) instead of a relative path ( jre\bin ).  This happens no matter where I bring the portable version and then fails to launch when the directory doesn't exist.  

I can manage to launch from java directly using the Command Line options here ( https://github.com/BiglySoftware/BiglyBT/wiki/Command-Line-Options )

> "java -cp "BiglyBT.jar;commons-cli.jar;swt.jar" com.biglybt.ui.Main"

But then it seems to ignore the BiglyBT.exe.vmoptions file with the portable flag and writes to user data folders.  Plus I would prefer to not have the extra cmd window running.

**Comment by parg** [comment]
The .vmoptions file is only applicable when launching via the .exe - however you can supply the option by using a -D"<option>=<name>" on the command line.

To start without a command prompt use "javaw" instead of "java" (and perhaps a "start javaw...")

**Comment by TheBestPessimist** [comment]
I have a suggestion here, to make portable install super easy to use:

Can you make `BiglyBT.exe` search for java in the folder `./jre`? 
Basically, one downloads a jdk or jre zip (from adopt open jdk), copies it into the folder BiglyBT, and renames that folder to `jre`.
The path to `java.exe` would be `./jre/bin/java.exe`.

In this case, all one has to do is add the string `-Dazureus.portable.enable=true` into `BiglyBT.exe.vmoptions` (maybe also other java flags like `-server`, `-Xmx`, etc.), copy the jre, and basta! BigltBT is portable and can be shared with any other person.

Here's a picture:
![image](https://user-images.githubusercontent.com/4482210/103140761-501ce400-46f3-11eb-8c1a-9e54eb0372fe.png)

**Comment by TheBestPessimist** [comment]
More suggestions for portable option:

### Support at least these relative paths for java:

- `./java/` - i think this is the best simply because people know "oh i have to donwload java and put it there. which java? i don't care. it's java. so i'll name the local folder `java`"
- `./jre/`
- `./jdk/`

### User data should not be stored in local folder

Right now, when setting `-Dazureus.portable.enable=true` inside `BiglyBT.exe.vmoptions`, the user folder set by BBT is the same folder where `BigltBT.exe` exists. 
I think this is bad, because I cant simply copy my user data someplace else, as all user-related stuff is not kept separate from the program itself.

I think enabling portable mode should change the default folder to `./UserData` to achieve this.


For now, i added the following to my `BiglyBT.exe.vmoptions` config:

```
-Dazureus.portable.enable=true

-Dazureus.config.path=UserData

-include-options UserData/java.vmoptions
```

and `java.vmoptions` is empty.
