### ISSUE TITLE
Display delay on adding / moving in GUI

### ISSUE THREAD

**Issue by MagnumGR** [BiglySoftware/BiglyBT#1538]
With the latest Beta i notice some delay on Adding / Completion-Moving / Starting Downloading  Torrents !   The delay is several minutes.

I have adding 10 torrents,  separately and i saw all of them in the Library (GUI) after 3+ minutes.
Also the same problem appears on the completion, the move from Downloading window to Completed of the finished it Torrent or when the Torrent starts to transfer actual some data after i saw Downloading in status (with several seeders or Peers be available )

Restarting several times the BiglyBT the problem insist. 
(There is no heavy CPU load or Disk activity at that time and with previous Betas all this actions was instantly )
 

* OS and version
Java 1.8.0_242 (64 bit)
  Oracle Corporation
/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.242.b08-0.fc31.x86_64/jre

SWT v4922r17, gtk/3.24.13, zoom=100, dpi=305
Linux v5.5.8-200.fc31.x86_64, amd64 (64 bit)
B2.3.0.1_B06/4 az3
* BiglyBT Version Number
2.3.0.1 B6
* For *nix: Desktop Environment
Fedora 31

**Comment by parg** [comment]
I can't think of anything in recent betas that might have caused this - are you adding the new torrents via a magnet URI (which may be taking some time to download the actual torrent)?

**Comment by MagnumGR** [comment]
It not a Magnet URI.  It's normal torrent files.

In first attempts to Add the files, i try to add it thru the menu : File > Open and i get the information message "Media is already add it "(I don't remember the exact message) but i have not see it, in D/L window.
After 1-2 min of seeing nothing in the D/L window, i force quit BT and then i tried again and again until i waited for 4+ minutes, then sudden all the torrents appears at once!

I also notice : I move the completed torrent on another disk and i close normally BT, before i let approx the some time (4+ min), when i reopened, i get several error messages because the BT had the previous location if the moved files and i needed to specify the correct location.
And the last torrent appears on the D/L window, not in the completed window when it was when i close BT.

**Comment by parg** [comment]
Can you create a deb.zip file (Help menu, last option), rename to debugzip and email it over to paul@biglybt.com? I'll take a look see if anything obvious is going on

**Comment by parg** [comment]
Thanks - I sent a reply. 

One other thing you can try is to grab a thread dump when the problem is occurring. Take a look at 

https://github.com/BiglySoftware/BiglyBT/wiki/Diagnostics

At the top where it talks about BiglyBT hangs/slow response there is a URL you can load that will dump the current threads in BiglyBT into the debug_1/2.log files.

Please try the following:

1) Open a torrent file and get BiglyBT into the state where you are waiting for the download to appear in your library.
2) Before the download appears navigate to that URL references in the Wiki article ( [http://127.0.0.1:45100/setinfo?name=AZMSG&value=AZMSG;0;config;log-diags;;](http://127.0.0.1:45100/setinfo?name=AZMSG&value=AZMSG;0;config;log-diags;;) )
3) Once the page 'loads' go to BiglyBT and generate a new debug.zip file and email it over

Thanks!
