### ISSUE TITLE
Error 301 on all torrents

### ISSUE THREAD

**Issue by OzoneHoyle** [BiglySoftware/BiglyBT#1545]
this started on new update, tried reloading/changing status of all torrents no fix
* windows 7 professional
* BiglyBT 2.3.0.0

**Comment by brazenvoid** [comment]
It is because private trackers have banned BiglyBT because it is possible to botch seed ratios through it. Apparently there are guides on the internet to do it and many people are doing it.

@parg Can this feature be restricted entirely or a torrent which has a private tracker or just per private tracker?

**Comment by parg** [comment]
No it isn't possible to botch seed ratios. 

Where is such a guide? 

Nobody has ever informed me about such a thing.

All we ever get is vague claims, like yours.

**Comment by brazenvoid** [comment]
Ok, I'll ask the private tracker admin.

**Comment by parg** [comment]
Good luck - if you can actually get some details of whatever it is causing this then I'll make a special thankyou page on our Wiki :) If anyone needs to talk to me privately about things then I'm always available at paul@biglybt.com

**Comment by OzoneHoyle** [comment]
Thanks for the inffo, guess I'll go back to Vuze...

**Comment by parg** [comment]
Thanks for the support, not.

**Comment by abixalmon** [comment]
https://github.com/BiglySoftware/BiglyBT/issues/1551
