### ISSUE TITLE
Reason BiglyBT is banned on most private Trackers

### ISSUE THREAD

**Issue by abixalmon** [BiglySoftware/BiglyBT#1551]
BiglyBT Extreme Mod

https://www.sb-innovation.de/showthread.php?33697-BiglyBT-Extreme-Mod-by-SB-Innovation-1-4-0-0-Beta-rev1

**Comment by abixalmon** [comment]
https://www.sb-innovation.de/showthread.php?34530-BiglyBT-Extreme-Mod-by-SB-Innovation-2-3-0-0-Beta

**Comment by TuxPaper** [comment]
I'm not sure what you want us to do about it. We didn't write it, we don't promote it, we can't stop people from using it.  Perhaps they could figure out a way to just detect the mod version and only ban that? (unlikely I know)

But if that's the reason, then they must have banned qBittorrent because of its leecher mod too? 

If No, then why haven't they?  Why single only BiglyBT out when every other open source client has this problem?

---

There is a solution that would make everyone happy:

Have the tracker owners write up a tracker/peer spec that is spoof-proof and all clients that want to use those trackers can implement it.  No more client blacklists or whitelists needed, either your client follows the spec and thus the rules and they are allowed, or they don't follow the spec, and they are banned.

**Comment by parg** [comment]
Also mods can spoof other clients whereas BiglyBT can't - so by banning BiglyBT they are in fact completely missing the target.

**Comment by hatewesterncivilization** [comment]
And that's why rutracker, kinozal.guru, so on, returning >1 hr announce time, and even do not collecting correct Bigly's data of uploaded-downloaded. Kaztorka.org, so on sites looks like doing similar. So, I'm pretty missing from true sending/receiving from them. They just some of strange persons for me.

**Comment by hatewesterncivilization** [comment]
Today I was uploaded 219 GB over 10 h 11 min, most of torrents in Bigly - rutracker, kinozal.guru, and kinozal.guru showing just - "(cегодня: 0 КБ )" uploaded by me, rutracker only - 20.54 GB+4 GB on rarely.

**Comment by hatewesterncivilization** [comment]
![image](https://user-images.githubusercontent.com/31370882/77420164-c2bf0300-6df3-11ea-83a7-295785ec25ab.png)
![image](https://user-images.githubusercontent.com/31370882/77420187-cbafd480-6df3-11ea-829a-2e265d7a9557.png)

**Comment by hatewesterncivilization** [comment]
Hope, Paul, Tux on the way to solve this problem.

**Comment by parg** [comment]
Make sure you're running the latest beta and then check a torrent's "reported sent" and "reported received" columns in the 'Sources' tab - that shows what has been reported to the trackers. Also in 'All Trackers' view the same data is shown for the tracker overall.

**Comment by parg** [comment]
I might look into adding some explicit tracker logging so you can see what's going on at a tracker level in more detail.

**Comment by hatewesterncivilization** [comment]
Thanks, I replaced Java 15 to default, will see in parallel if helps.

**Comment by abixalmon** [comment]
If you need any data or information from a tracker host: Ping me @ irc.rizon.net #AvistaZ (same username)

**Comment by hatewesterncivilization** [comment]
Ok, thanks.

**Comment by parg** [comment]
B10 is out. The 'All Trackers' view has a new right-click context menu to enable logging for a tracker and another one to take you to the log file. There are two types of log 

* failure - when the tracker doesn't respond or returns an error
* success - when upload/download statistics have successfully been communicated to a tracker.

Remember that tracker stats work on 'sessions' - when a download starts running it creates a new session and the stats reported against that session are relative to the session as a whole. So, for example, the uploaded data might be reported as 100k the first time the tracker is updated and 200k the next time. This doesn't mean that 300k has been uploaded, it means that 200k has been uploaded (with an additional 100k betweek the updates).

Whenever a download becomes inactive (stopped, queued, paused) or BiglyBT closes the session is completed - next time the download starts it will start a new session and count from 0 again,

**Comment by hatewesterncivilization** [comment]
Good trick, Paul, many thanks from all of us, I always use last beta, you was asked. Absolutely gotta use this addition for information.

I gotta switched to AdoptOpenJDK, https://adoptopenjdk.net/releases.html?variant=openjdk8&jvmVariant=openj9

Memory footprint now is much smaller than usual Java. Also client start work completely lightweight-responsiveness.

**Comment by token0** [comment]
Thumbs up for AdoptOpenJDK!

**Comment by parg** [comment]
B11 has a 'latency' column under All Trackers that gives you an idea of how long requests to trackers are taking.

There is also a new option under Options->Tracker->Client to specify how many seconds BiglyBT will wait for when updating trackers on closing BiglyBT.

During close there is a new 'progress' dialog that shows you what's going on during closedown.

**Comment by hatewesterncivilization** [comment]
Paul, first of all, big thanks, it's very kindly by you, appreciate your big programming. I'm don't saying work, okey.

Just look here, for example. tor1.tor4me.info announcer last update time - 08.13 PM, but local time - 10.50 PM. It's not Bigly himself making those logics in announcing? If not, then what? Update time, administrated by kinozal.guru, by the way, - 1h 00m (1h 00m). Rutracker also like those. 

But others, say, global announcers works normally as I seeing unlike this two, kinozal.guru and rutracker. I don't know what I should think now, maybe this is some of types of outside intrusion right to Bigly on PC?

**Comment by parg** [comment]
Hmm, it is very odd that the 'Next' column is entirely blank - are all your torrents showing that?

**Comment by parg** [comment]
Could it be you've had a large change in system time on your system since starting BiglyBT?

**Comment by parg** [comment]
Or did you edit the trackers associated with the download? I'm seeing some odd behaviour when editting trackers that's I'm looking into.

**Comment by hatewesterncivilization** [comment]
1. Maybe all torrents showing the same behavior, but I'm think mainly kinozal and rutracker. Another thing, Paul, most of those torrents in force running states, but after couple of time lots of torrents goes disappearing from the list of seeding torrents on this sites. 

2. Recently I was changing the time on PC, but this was quick and correct, it cannot be shift things in Bigly at this meaning. It is true?

3. Most of editing was adding this two global announcers as you see, but that editing had maded long time ago, if this important. Is this matter in things?

Hope, we can eliminate those problems once and for all.

**Comment by parg** [comment]
I think your problem is caused by the very large number of active torrents you have and slow-to-respond trackers. Currently if the tracker update timer gets delayed the 'Next' column shows blank - I've changed it to show how much delay there is (negative values).

There is also a limit of 32 active tracker operations at any one time. If you have 3000 active torrents, many with multiple trackers (let's say 10,000 active in all) and they need updating every 30 minutes then that is 10000/(30*60) = 5 updates per second. If you have some slow-to-update trackers then this can easily clog up the 32 active operations and cause your updates to start lagging. For the moment I'll add a config option so you can increase the number of active operations.

**Comment by parg** [comment]
You can see your tracker latency in the All Trackers view - take a look

**Comment by parg** [comment]
B13 has a new view under Statistics, the 'Tracker' tab - it shows tracker update rates and lag. The 'Next' column now shows lagging updates as negative numbers and in a warning colour.

I haven't added config to control concurrency yet, I'll look at that tomorrow - might be interesting to check out the next things though.

**Comment by hatewesterncivilization** [comment]
It's great, Paul, you was made powerful changes, very comfortable and demonstrative for catching and seeing of all the things.

That's my summary with new system for watching tracker farms. Surprisingly, update rate at pretty high level (can reach it or peak to). 

So, I think I should wait configurable update rate you are noticed, because as before most of torrents still in blank and inactive negative values of Next time update.  

![image](https://user-images.githubusercontent.com/31370882/77841338-42145400-71b1-11ea-99d1-4873f1812012.png)
![image](https://user-images.githubusercontent.com/31370882/77841475-4a6c8f00-71b1-11ea-8d2b-410ddac995dc.png)

**Comment by parg** [comment]
B14 has an option to increase the concurrency of announces under Options->Tracker->Client.

It also has separate public and private tracker task pools.

The Tracker view has a new graph, the number of scheduled announces.

What you need to do is increase the announce concurrency until the displayed lag values are around zero. Don't do this just after starting BiglyBT as there will be a spike during startup as all torrents are started. Rather, wait for things to settle down and then experiment.

**Comment by hatewesterncivilization** [comment]
Paul, it completely fixed now, just setting up new option to 1000 value. All thousands torrents now present at private profiles of those sites. So, data transfers in fullness in mind.

I got look to maximum value in maded coding section, it is 1024? What 8 in command? 

add(new IntParameterImpl(ICFG_TRACKER_CLIENT_CONCURRENT_ANNOUNCE,
				"ConfigView.section.tracker.client.conc.announce",8,1024),
				Parameter.MODE_ADVANCED);

**Comment by hatewesterncivilization** [comment]
As I see max value - 1000. By the way, update lag just close to 0.

![image](https://user-images.githubusercontent.com/31370882/77898538-1cfd0f80-729d-11ea-98df-87a127607832.png)

**Comment by parg** [comment]
8 is the minimum. Each active update task will run on a separate thread and can take a few MB of memory, so if you set it to 1000 make sure you have enough memory!

**Comment by hatewesterncivilization** [comment]
Ah, understood. 3885 seeding torrents in active state, 16 GB RAM, 2,4 GB free in the row.

Thanks to AdoptOpenJDK, Bigly works very reflect.

**Comment by hatewesterncivilization** [comment]
Announces and scrapes got getting in equal. What a beatiful. Many thanks, dear Paul. It is monument like progress.

**Comment by brazenvoid** [comment]
@parg @hatewesterncivilization is this issue universal or user specific? Meaning is there a need for a wiki or something?

@parg This issue got taken over by this announce/scrape sync issue, could you move it to a more appropriately named issue and keep this to what it was, regardless if it is realizable or not?

**Comment by parg** [comment]
It is a general issue in that if you are overloading the tracker announce system by running a large number of active torrents then announces will lag. Features have added to BiglyBT to warn the user of this and offer remedies.

No idea how to split the issue, just have to live with it.

**Comment by hatewesterncivilization** [comment]
Absolutely, Paul, brazenvoid, one of the best features for years.

**Comment by hatewesterncivilization** [comment]
Just think, say, you got one big drive with terabytes, then you get thousands torrents, and you got seeding those thousands. And then this feature help you successfully transfer statistics to sites, that keep records and ratio.

**Comment by hatewesterncivilization** [comment]
After ignoring lags below 500 I got getting 10-15 torrents lag, from showing in the sites.

Before this addition been better and in fullness.

**Comment by esabol** [comment]
Hi. I recently upgraded from Vuze to BiglyBT because Vuze doesn't seem to work with some modern HTTPS TLS ciphers. The transition went well, except I soon found out that BiglyBT is banned on a couple of sites for "reporting bad stats". Has anything changed since March in this regard? Just wondering if I have any hope of convincing these site admins to change their minds. Thanks!

**Comment by brazenvoid** [comment]
@esabol 

Their remarks are due to some scripts and plugins in the wild that modify BiglyBT and compromise said stats. There are similar scripts and plugins for few other clients as well. Thus such is out of BiglyBT's control. 

Moreover, the correct counter necessitates some rework of the tracker code. In fact solutions have already been researched and proposed. Just that the trackers themselves do not want to undertake said changes. 

Suffice to say, they are shirking their own work but as the vulnerability exists, so for now they have instead turned to block the effect rather than the cause.

**Comment by parg** [comment]
Given that the cheat tools very often allow you to change the client-id reported to the trackers the only people the tracker admins end up blocking are the legitimate users. 

There are tools out there that allow you to spoof ANY client simply by proxing tracker communications through a proxy that modifies the stats, go figure.

**Comment by TuxPaper** [comment]
fwiw, I think since March, parg added some closedown wait logic to ensure sending the last calls to the trackers, so they'd have a more accurate report. This would only affect slow trackers, and I believe it's setup by default to wait up to 20 seconds for the trackers to respond before finally shutting down BiglyBT.

**Comment by brazenvoid** [comment]
I know not much about BT but I know a lot about network proxies. 

I have led development of a LAN game client which essentially replaced network layers of connected games and spoofed communications to make them believe they were on the internet.

I must say the games did not have any say or control on such. Unless the said games employ some complex detection logic which changes patterns truly randomly can they detect such manipulation, but addressing such a niche would be completely unprofitable.
