### ISSUE TITLE
Issues since moving from Azures 

### ISSUE THREAD

**Issue by Dog-Pack** [BiglySoftware/BiglyBT#1571]
I recently finally upgraded from azures about 3 weeks ago, so far there are 2 issues i have with this program over it, 

1st if this program is not open then the 1st torrent i down load fails, it shows up in the downloaded window as the file is missing and i have to delete it and re down load it, every time with out fail, this was not and issue with azures, 

2nd I did the thing you suggest to change the player to vlc player, but i do not get subtitles and there is no way to turn them on, I can not right click on the video, where as in azures they just worked, i watch a lot of anime so i need the subs, and now i keep having to browse to the file and open it in vnc instead to get the subs to work.

Java 1.8.0_202 (64 bit)
  Oracle Corporation
c:\program files\biglybt\jre

SWT v4930r7, win32, zoom=100, dpi=96
Windows 10 v10.0, amd64 (64 bit)
B2.3.0.0/4 az3

**Comment by parg** [comment]
1. Can you go to Tools->Options->Files and set the option near the top "Whan opening a torrent, show options dialog" to "every time" to see if that helps in any way

2. The built in player in Azureus/Vuze/BiglyBT is very old and doesn't support more recent formats which is why the recomendation is to configure it to use VLC. As you say, this means you don't get to select subtitles within the player. You don't have to follow the advice to configure it to use VLC, in which case it should work as before. However you might have issues with more recent formats if you do this.

**Comment by Dog-Pack** [comment]
Thanks, that seems to have sorted the 1st issue out, and will change back for the 2nd.


________________________________
