### ISSUE TITLE
router.silotis.us

### ISSUE THREAD

**Issue by taps2** [BiglySoftware/BiglyBT#1628]
Not sure if this is normal behavior or not, but seems off to me. Seems to be constantly querying router.silotis.us multiple times a second. Still queries multiple times when whitelisting. Blacklisting the domain doesn't seem to have any noticeable effect.

![image](https://user-images.githubusercontent.com/21356994/81007118-4833cb00-8e16-11ea-89b1-9854e1a20275.png)

**Comment by parg** [comment]
Version etc? It is the mlDHT plugin but not sure of cause.

**Comment by taps2** [comment]
Version B2.3.0.0/4 az3   Windows 64 bit. I believe the only plugin that is not stock is is the BiglyBT Web Remote which is version 0.95. 
Seems to happen irregardless if I am currently torrenting or not.

Thanks for the quick reply and sorry I didn't check for a reply sooner. Also thanks for the great program.

**Comment by parg** [comment]
That host is used to bootstrap the mlDHT plugin when the mainline DHT is too small - take a look at the mlDHT views/logs and see if there are any clues

**Comment by raspher** [comment]
Same issue, _hot-fixed_ by disabling :
- [ ]"Restore node ID on restart" <- **this probably was the issue**
- [ ] Enable IPv4 multihoming
- [ ] Enable IPv6 multihoming

**Comment by nokti** [comment]
It looks like I had a related issue with the mlDHT plugin. When watching videos on Facebook my computer would regularly freeze, leading sometimes to the windows blue screen. The last message in the windows event log was a warning related to "router.silotis.us" (that's what led me here). I've since disabled the mlDHT plugin in BBT and my computer isn't freezing anymore (fingers crossed).
