### ISSUE TITLE
BiglyBT kills my home LAN

### ISSUE THREAD

**Issue by Knocks** [BiglySoftware/BiglyBT#1634]
Something in BiglyBT completely slows down my LAN, to the point where small video files fail to stream smoothly over a wired network and enter buffering every few minutes.

This happens even when there are as few as 2 torrents downloading.  I suspect (but haven't confirmed) that this happens when a torrent is finished and enters the "checking"/seeding stage.

This has gotten so bad that I shut down BiglyBT and reboot my router and set-top box (Nvidia Shield) every time I want to watch a movie over LAN.

* Windows 10
* BiglyBT Version 2.3.0.0

**Comment by NaPurHab** [comment]
Turning off the following options can help. There may be others that someone can suggest. These are found in Options/Files.

![image](https://user-images.githubusercontent.com/37715552/81446337-b0511c80-9148-11ea-9320-6b2af5210fa9.png)

NVidia Shield supports PLEX. If you install PLEX as a Media Server on your computer you can stream to your NVidia Shield and any other device (Phone, Tablet, Laptop) that is on your Home Network for FREE. If you want to stream PLEX on the go (WiFi Hotspot or Cellular Data {Not recommended}) then you need a PLEX Pass.

The Important Bit here is that PLEX is a Media Server and when on the same computer as BiglyBT can adjust Load to ensure PLEX can Keep up with the stream it is sending.  It should help with your buffering issues. And I know NVidia Shield supports PLEX as a client device.  But if you need to reboot your Router, it may be part of the problem. Especially since you say you have it all Wired.  Wired is usually the most reliable. Only thing there would be a flakey cable. I have a ISP provided Modem/Router and go months between reboots.

And finally a tip.  When post a report here always include as much detail as possible.  Version of BiglyBT and OS/Version are usefully to the team.  If you open Help/About you will see:

![image](https://user-images.githubusercontent.com/37715552/81447525-c9f36380-914a-11ea-91d2-2498afaeabd9.png)
the text in the System Box is selectable so you can Copy/Paste it to your report.  So from the above a Copy/Paste would produce:

Java 14 (64 bit)
  AdoptOpenJDK
c:\program files\adoptopenjdk\jre-14.0.0.36-openj9

SWT v4930r7, win32, zoom=100, dpi=96
Windows 10 v10.0, amd64 (64 bit)
B2.3.0.1_B33/4 az3

**Comment by Knocks** [comment]
Thanks @NaPurHab 

I run Kodi, not PLEX, and access files via SMB.  I reboot the router for good measure, not sure if it was actually helping.  The LAN cable is brand new and is not the problem.  None of these problems occur when I use another bittorrent client.

As far as "Perform low resource re-check when seeding," is that really a good solution?  Large torrents take a long time to re-check as it is.  I don't want them to take a century to re-check if "low resource" is enabled.  Some torrents you just want to quickly download/recheck and delete without seeding.  There should probably a middle ground or a sliding scale to set resources versus performance for this option, as opposed to either/or.

I will still try your solution to try to confirm that the problem is caused by CPU during re-seeding.

This is from the About box:

Java 1.8.0_202 (64 bit)
  Oracle Corporation
c:\program files\biglybt\jre

SWT v4930r7, win32, zoom=100, dpi=96
Windows 10 v10.0, amd64 (64 bit)
B2.3.0.0/4 az3

**Comment by NaPurHab** [comment]
I did say Turn Off the 2 options I showed.

**Comment by Knocks** [comment]
Yes, and I did respond "is that really a good solution?" and added a whole paragraph to explain my point. 😀   Turning off checking completely does not seem wise when you download huge files in thousands of small pieces that have a high possibility of corruption.
