### ISSUE TITLE
BiglyBT Causing PC Audio to Stutter, Glitch, Pop, & Buzz

### ISSUE THREAD

**Issue by fpellert** [BiglySoftware/BiglyBT#1639]
Windows 10 64-bit pc (HP workstation 420z) running BiglyBT B2.3.0.0/4 az3,  PC has been having audio issues for the last month or so just playing audio from hard drive, or streaming audio (or video with audio) - frequent audio buzzing, pops, clicks, stutters, dropouts, etc - several times per minute.  Issue happens no matter what software I'm using to play audio or video.  All my drivers and the BIOS have been updated.  Finally traced the problem to BiglyBT.  When I close BiglyBT, problem is fixed.  When BiglyBT is running, problem occurs.  I have not changed any BiglyBT settings - it is whatever the default install settings were at.  I previously ran Vuze for many years and never had this issue.  Looking for assistance on whether there are any BiglyBT settings I can change to fix this issue, or whether I should go back to Vuze.

**Comment by parg** [comment]
Try reverting and see.

**Comment by StephKoenig** [comment]
I've also experienced this on 2.3.0.0 and 2.4.0.0. Anecdotally it happens when you have torrents with many files (say >50 files in them) and doesn't occur immediately (unless it's already occured during that boot). When stuttering, freezing etc kicks in it then occurs every few seconds thereafter - even freezing the mouse. It seems to build up during the day to the point when the the system becomes unsuable.  Goes complete on app closure. Most noticable when playing media the the audio goes crazy and if Bigly is really in the mood, video and everything stops for several seconds... typing can be hilarious.

In the past I'd happily play the Division 2 with Bigly doing it's thing and have a tv program to side eye, that's impossible now if Bigly is in a mood.

I thought it was something with my setup (and maybe it still is) but it seemed fine until recently and noticed it more since I've been locked in. Updated Java, Bigly (to 2.4.0.0), x64 version on win x64 1909 build 18363.836 w/Intel 8700k and 32GB ram, wired via an intel nic on a small 70Mbps connection, also I'm using an nvme ssd. I set file checking to 1 at a time just in case something there was causing issues. Like fpellert I'm using current drivers (within a month anyway).

I'm my limited knowledge something is generating a ton of interupts on a regular basis once it enters this mode. Task manager shows BiglyBt hitting 10-15% CPU when it's doing it's stuttering thing.

I'm trying just running with the dashboard (minimized) showing - having never viewed the library/torrent status - so we'll see if that seems to help it.

I've already tried killing the config and starting fresh but that didn't seem to change any behaviour. With no torrents it doesn't occur and with a few single file torrents it doesnt' seem to get triggered either.

**Comment by StephKoenig** [comment]
I think I sorted my issues out... the answer was to reduce the memory I gave the JVM and set aside for caching etc. The clue was running latencymon and seeing many hard page faults from Biglybt...and then lots of stalls from the ndis driver.

For the memory stuff I found this thread (thanks parg) https://github.com/BiglySoftware/BiglyBT/issues/92

I have 32GB of ram so a while ago I figured giving Bigly more wouldn't hurt but I hadn't thought about java's memory management...maybe something recently made Bigly sensitive to thise

In startup/Shutdown I set my jvm to max 256, min 16mb.  (previously was 512MB and default)
In performance options I reduced cache to 16 from 48, Max Write to 8 from 16 and max read to 4 from 8 (not sure if any of those would have an impact)

It seemed to help as those were the only changes I made and now seem to have no stuttering.

**Comment by StephKoenig** [comment]
Sorted it... the issue wasn't Bigly it was a bandwidth monitoring tool. I switched from Networx to NetMeter (both by Softperfect) becuase NetMeter give you traffic/ports etc per app. I hadn't thought that to dso this it needs to inspect each packet but that what it was doing...

So when Bigly started doing it's thing and there's were 400 i/o connections and all the other stuff somethign int he way netmeter's packet inspection caused interupts to skyrocket which I think cascaded once packets accumulated..

Switched back to Networkx and everythign smooth as butter...kept the JVM changes I made as well...

**Comment by parg** [comment]
Nice, one to remember for the future.
