### ISSUE TITLE
option to have installer not download jre?

### ISSUE THREAD

**Issue by SUCM** [BiglySoftware/BiglyBT#1646]
I already have a working JRE on the ystem and BiglyBT is able to pick up after install. is it possible to tell installer not to forcefully download a broken/bad/not-working jre so I don't have to waste download bandwidth and manually delete that broken/bad/not-working jre every time I do a full re-install?

**Comment by TuxPaper** [comment]
If the installer can detect a java with a high enough version, it should use it, but detection varies from OS to OS.  Which OS are you using?  What version of Java is already installed on your system?

**Comment by SUCM** [comment]
below captured by BIglyBT client. somehow installer (only tried many 2.x versions so far) can never detect java. I migrated from Vuze to Bigly when I had jdk 8.x. I don't remember Bigly ever not downloading jre when I run Bigly's installer
```
Java 11.0.7 (64 bit)
  Oracle Corporation
c:\program files\java\jdk-11.0.7

SWT v4930r7, win32, zoom=100, dpi=96
Windows 10 v10.0, amd64 (64 bit)
B2.4.0.0/4 az3
```

**Comment by TuxPaper** [comment]
If you run the installer with the `-manual` command line, it should pop up a Download/Locate/Cancel, but my experience so far is that the installer just gives an error that it can't use the JRE, when I select one that should work :(

**Comment by SUCM** [comment]
the confusing part is that installer can't locate the java.exe, but installed client is able to and runs just fine. the listed max/min java version by installer seem quite ancient too. is that max java version actually older than Win10?

the installer downloaded jre doesn't work properly on current (and probably newer) Win10. whenever I tried to use the installer downloaded jre, it frequently freezes the whole Bigly client for 5-20 seconds whenever I scroll or try to do something useful (ex. add new torrent, delete/move torrent data)

**Comment by TuxPaper** [comment]
I've put up a new installer at https://github.com/BiglySoftware/BiglyBT/releases/download/v2.4.0.0/GitHub_BiglyBT_Installer64.exe which should use your current JRE (up to and including Java 13).

**Comment by SUCM** [comment]
just tried this new installer and it doesn't require downloading jre
using the `-manual` option shows that it does accept the current installed java

thanks

**Comment by urbenlegend** [comment]
Can we have an option to ignore the max JVM limit? The Bigly 2.6.0.0 installer is currently limited to 13 even when using the `-manual` flag, but I've ran it successfully on 14 and 15 by removing the jre folder in the install directory.

**Comment by parg** [comment]
Can the JVM developers have an option whereby they don't release a new major version of Java every week?

**Comment by urbenlegend** [comment]
@parg 🤣 I totally understand the feeling of keeping up with rapid release schedules, but:
1. every 6 months is hardly every week.
2. the option to use your own JRE is hidden behind the `-manual` flag anyways, which normal users don't know about and won't use, and advanced users like me will understand that breakages can occur. All we want is just the option to use our own JRE. If we break Bigly, its our own damned fault!
3. Bigly installer by default downloads Java 8 and a lot of performance improvements to the JVM have happened between 8 and 15, including things like VM boot up times. It'd be nice to be given the option to use whatever JVM is available.
4. I've been using Bigly on Java 14 and 15 just fine and if anything, allowing this opens up Bigly to be "beta-tested" by other users so that you can be aware of any potential problems with upcoming JVM versions.

**Comment by altsu93** [comment]
Totally. Add that as default.
