### ISSUE TITLE
HTTP outbound not going over VPN

### ISSUE THREAD

**Issue by bradmurray** [BiglySoftware/BiglyBT#1667]
* Windows Server 2016
* BiglyBT Version Number 2.4

When using a VPN (PIA) in split tunnel mode TCP and UDP are picking up the correct outbound IPs, but HTTP is going over the the non-VPN connection which causes a problem with trackers that require that you use a single IP.

**Comment by TuxPaper** [comment]
Tracker http traffic from BiglyBT will be going through the Bind IP address, which should be set to your VPN if you are using the VPN Helper plugin (or if you set the config option manually).

What's the problem that's being caused? Is it related to you looking at your account from a web page? My first thought would be that maybe the tunnel splitting is causing your browser to use the non-VPN IP and since BiglyBT uses the VPN ip, the tracker gets angry.
