### ISSUE TITLE
Why is torrent showing "downloading + swarm merge" when it is only a single file and there are no other torrents with that file?

### ISSUE THREAD

**Issue by david-bakin** [BiglySoftware/BiglyBT#1678]
(BiglyBT Beta 2.4.0.1_B10 on Windows Server 2016.)

I've got a torrent being downloaded showing "Downloading + Swarm Merge" even though the torrent has only one file and I'm definitely positively not downloading that same file in any other torrent (nor have I downloaded this file in the past).  What's up with that?

**Comment by parg** [comment]
Must be another file in your BiglyBT library with the same size - enable the 'Swarm Merge' column and hover over it for info or go to Tools->Plugins->Log Views->Swarm Merge and unpause the logging.

**Comment by david-bakin** [comment]
Same size?  So the block checksums aren't used to match content at this point?

**Comment by TuxPaper** [comment]
Unfortunately, we can't use block or piece checksums.  Identical files will have different block checksums due to piece size and at what files preceded it in the torrent (ie. a one byte file prior to the identical file will shift all bytes over one, making the checksum different, even though the file is the same)

Some torrents include a file hash, but it isn't standard and not very helpful unless every torrent contains them.  File size is just about the only good reference we have that a file might match. 

I believe when the same-size files aren't identical, the merger stops trying after a few hash check fails.

**Comment by david-bakin** [comment]
Interesting. Well here's apparently an advantage of the new v2 torrent file support - if I understand it correctly in v2 torrents files are aligned and filled, and you can use the top level merkle hash for the file hash.   (But I wonder if v2 torrents are actually found in the wild (I asked that in an earlier question) - I wonder if biglybt can collect stats on that or if anyone has done a census based on torrents logged in the DHT or something?)

**Comment by parg** [comment]
v2 torrents have separate hash trees (and root hashes) for each file so there isn't actually any padding/aligning to do. I've never seen a wild v2 torrent but then support is limited - someone with a DHT crawler could try and grab some stats but I doubt it'd be impressive.

Hybrid torrents that support both v1+v2 concurrently can be constructed. Unfortunately you can't just add v2 info to a v1 torrent (in general) without changing the v1 hash as the v1 torrent has to have pad files in the right places to make things work.
