### ISSUE TITLE
Windows 10 - Full Disk Encryption - Performance Tweak Suggestions?

### ISSUE THREAD

**Issue by ms52538** [BiglySoftware/BiglyBT#1679]
I recently discovered a friend had his Plex NAS with 45 TB of data hijacked. Based upon his data, they set a ransom of $5,500 US in Bitcoin. He had an open port, supposedly, for remote control of the NAS with a simple password and that is how they got it. Which got me to thinking. I'm sure I'm not alone in my use of private trackers for my torrents - and keeping those torrents in a forced state for availability - while at the same time aligning the torrent content through PLEX on my PC for streaming on my network. So I began checking into file and disk encryption and option to turn on Window's BitLocker on my drives. BiglyBT seems to be performing a tad slower as a result but I've not seen any 'show stopper' events that have made me reconsider my decision (thus far). The last drive, 7 TB, is still encrypting (5 days in so far and only 60%) but the other smaller drives have completed successfully. I've limited BiglyBT 'forced' active torrents on the drives that have been fully encrypted, and those on the large drive still in-process are stopped until encryption is completed.

With all this said, I'm not seeing much in the way of "disk encryption" here in the GitHub, so I thought I'd raise the topic.

What are your thoughts re: full disk encryption with BiglyBT? 
Are there any tweaks or suggestions you may provide in the pursuit of better performance?
Have you heard of others doing this as well?

Thanks!
M

**Comment by parg** [comment]
Heyup,

I have no experience of this - I've asked in the beta chat channel to see if others do.

cheers

**Comment by parg** [comment]
FYI

[14 12:50] Droo
Firstly, disk encryption is only useful in the case when your physical HD falls into someone else’s hands. ie. they can’t just plug it in and access the data. That’s why I used bitlocker on my laptop when travelling overseas.  It absolutely doesn’t prevent a network intrusion the OP described. So unless you have a real risk that someone will enter your house and take your hard drives, then bitlocker is useless which is why I took it off my laptop when I returned home.
[14 12:53] Droo
I aslo did not encrypt my C drive, only my data partition and made sure to keep all my personal stuff in the data partition. This will minimize any performance impacts.
