### ISSUE TITLE
Missing ppp1

### ISSUE THREAD

**Issue by tonywr71** [BiglySoftware/BiglyBT#1741]
Win 10 Pro N Version 10.0.19041 Build 19041
BiglyBT Version Number 2.4.0.0

Hi, I was wondering if anyone knew why the ppp1 vpn bind has disappeared from my BiglyBT Advanced Network Settings screen. It's has been there for months and working fine, now its just disappeared. I use PureVPN. I've rebooted my machine, restarted PureVPN and restarted BiglyBT, but it hasn't turned up. I am now binding to eth4 (TAP-Windows Adapter V9) but I shouldn't need to do that. How do I get ppp1 back?

**Comment by NaPurHab** [comment]
I use PureVPN and have experienced this problem.  It occurs when PureVPN connnect with a protocol that doesn't support PPP1.   You need to specifically select IKEV as a protocol.  Even then sometime the server your connecting to will not connect on IKEV and will switch to another protocol ( TCP/UDP, L2PT, SSTP). IT can also happen if your set to Automatic for Protocol.   Even then I have seen a few countries that can still cause problems for me. Netherlands used to be fast and stable. But recently even with IKEV, it falls back to another protocol, and I end on on (TAP-Windows Adapter V9).  

So make sure your using IKEV in PureVPN. And a country that is stable.  I use Germany mostly.

BiglyBT TIP.   You can fill the bind to with '(PureVPN)' instead of ppp1. So even if Windows does something odd like switch to ppp0 or ppp2, it can still find it. And if you get a connection on a protocol that switches to the TAP-V9 port, the error Message will say can't bind to (PureVPN).

@parg I don't understand the Regular Expressions.   Is there a way to have (PureVPN) or (TAP-Windows Adapter V9).     That would solve this. Then if it connects to the (TAP-Windows Adapter V9), BBT will still work correctly.  The ppp1 or (PureVPN) connection is preferable as it means an IKEV connection. But failing that, the (TAP-Windows Adapter V9) conection has encryption, just not as good as IKEV.

**Comment by parg** [comment]
You should be able to enter

`(PureVPN|TAP-Windows\sAdapter\sV9)`

**Comment by NaPurHab** [comment]
Thanks, RegEX gives me a headache.  But it solves @tonywr71 problem.  And demonstrates a solution for other VPN users.  Perhaps something for a Wiki.

**Comment by NaPurHab** [comment]
@parg I Spoke too soon. It seemed to work, then I head to bed. When I got up it shows the following:

![image](https://user-images.githubusercontent.com/37715552/92156076-6de9d480-edf6-11ea-8c7c-19455d824c43.png)

So it can't resolve that RegEx. I cut/paste so no typos.  
Perhaps make the BOX a bit wider for easier reading as below:
Lots of room on the right.
![image](https://user-images.githubusercontent.com/37715552/92157268-32500a00-edf8-11ea-806f-c22a6cd35021.png)

**Comment by parg** [comment]
What's the exact name of the interface as listed on that config page? You can copy+paste from the list there

**Comment by NaPurHab** [comment]
![image](https://user-images.githubusercontent.com/37715552/92158545-16e5fe80-edfa-11ea-86cd-54d26badc1a0.png)

![image](https://user-images.githubusercontent.com/37715552/92158598-29f8ce80-edfa-11ea-9962-6472f54dd10f.png)

**Comment by NaPurHab** [comment]
Oh the contents of the Bind to is:

(PureVPN|TAP-Windows\sAdapter\sV9)

I'm wondering if each needs both ( ) s.  (this)|(that)

**Comment by parg** [comment]
Currently if the expression matches > 1 interface then thingss fail - looks like you have both PureVPN and TAP present at the same time

**Comment by parg** [comment]
if you want to match against both then you would need

`(PureVPN);(TAP-Windows\sAdapter\sV9)`

**Comment by NaPurHab** [comment]
> Currently if the expression matches > 1 interface then thingss fail - looks like you have both PureVPN and TAP present at the same time

Actually, only the ppp1 has an IP associated with it. The eth3 is just a place holder line with no IP.



> if you want to match against both then you would need
> 
> `(PureVPN);(TAP-Windows\sAdapter\sV9)`

Could it be:

`(PureVPN)|(TAP-Windows\sAdapter\sV9)`

remember the original was:

`(PureVPN|TAP-Windows\sAdapter\sV9)`

**Comment by parg** [comment]
yah, currently it doesn't check for associated addresses - I'll make it do so

**Comment by NaPurHab** [comment]
Here is what I see.

![image](https://user-images.githubusercontent.com/37715552/92164776-e5723080-ee03-11ea-9cc8-22a20f15c588.png)

**Comment by NaPurHab** [comment]
@parg Just tested and the version that works is:

`(PureVPN|TAP-Windows\sAdapter\sV9)`

So @tonywr71 the above is now working in B31. You can now set it to Both ppp1 and eth4 as you listed the ports involved for you.  You use the Names as above, and there is a OR between them. 
So _one or the other_. Issue solved thanks to the fine work of @parg
