### ISSUE TITLE
[Feature Request] Ability to search for folder names, and not just file names. 

### ISSUE THREAD

**Issue by Apocalypse612** [BiglySoftware/BiglyBT#1752]
Having the ability to search for folder directories instead of just file names would be highly useful. The file search is great, but as of right now it completely ignores folder names. Often times in large torrents, the Folder name is a lot more useful and relevant than the file names inside.

Please consider, and thanks for the hard work.

* OS: Windows 10 Pro x64 Version 1909 (OS Build 18363.628)
* BiglyBT Version Number: 2.4.0.0
* For *nix: Desktop Environment

**Comment by parg** [comment]
If the filter expression contains a file separator then matching is done against the full file path. This does include the file separator in the matching so you would need to use a prefix match.

**Comment by Apocalypse612** [comment]
Seems kinda complicated, definitly not user friendly.

**Comment by parg** [comment]
I suppose it could be changed so that if a folder separator is entered (back slash on windows, forward slash on others) then the rest of the matching would be done via 'contains'

for example, if you have files

/fred/jim
/fred/tony
/bill/peter

then entering '/ed' would match the first two.

That is, if you start your filter with a file separator then this causes full path matching against whatever comes after the separator.

**Comment by Apocalypse612** [comment]
That does sound like an improvement.

**Comment by parg** [comment]
I'll add that for beta B31

**Comment by Apocalypse612** [comment]
Thank you sir!
