### ISSUE TITLE
Priorities are honored backwardly

### ISSUE THREAD

**Issue by freMea** [BiglySoftware/BiglyBT#1780]
Java 14.0.1 (64 bit)
  Oracle Corporation
d:\programmes\biglybt\jre

SWT v4930r7, win32, zoom=100, dpi=96
Windows 10 v10.0, amd64 (64 bit)
B2.4.0.0-00/4 az3

![Screenshot](https://user-images.githubusercontent.com/22337329/93113876-1c74fb80-f6ba-11ea-96f9-a4b59d457280.jpg)

Each and every time I select files > set priority > numeric auto-decreasing, although the numerical priority is well applied, the least priority file start to download. Same if I applied other priority type than numerical. The lowest is downloaded first. Every time. Of course, I expect to be the opposite. Highest number is downloaded first.

**Comment by parg** [comment]
You don't have it set for sequential downloading as well do you?

**Comment by freMea** [comment]
> You don't have it set for sequential downloading as well do you?

Where can I check that ? I can’t find the option.

**Comment by parg** [comment]
If you don't know then you probably don't have it set :) Just trying to figure out why you're seeing that. In general pieces are downloaded by their priority - not just the file's priority but one calculated based on various things such as rarety, sequential settings etc. In your example the low priority ones that are downloaded are towards the front of the torrent which is why I asked.

In the 'Pieces View' (and Piece Map view) you can see the piece priority.

**Comment by freMea** [comment]
> If you don't know then you probably don't have it set :) Just trying to figure out why you're seeing that. In general pieces are downloaded by their priority - not just the file's priority but one calculated based on various things such as rarety, sequential settings etc. In your example the low priority ones that are downloaded are towards the front of the torrent which is why I asked.
> 
> In the 'Pieces View' (and Piece Map view) you can see the piece priority.

Yes, my screenshot was misleading because it make one think files are sequentially downloaded. It’s just that I inverted the priority of files so they do so. Before that, the tenth file (lowest priority) was downloaded before the seventh one (highest priority).
