### ISSUE TITLE
Biglybt secondary windows do not register in the taskbar on 2.5.0.1_b02

### ISSUE THREAD

**Issue by kotenok2000** [BiglySoftware/BiglyBT#1794]
Java 14.0.2 (64 bit)
  Red Hat, Inc.
c:\program files\redhat\java-14-openjdk-14.0.2-1

SWT v4930r7, win32, zoom=100, dpi=96
Windows 10 v10.0, amd64 (64 bit)
B2.5.0.1_B02/4 az3
* OS and version
* BiglyBT Version Number
* For *nix: Desktop Environment
![Снимок экрана (87)](https://user-images.githubusercontent.com/8822292/94184020-fd414f80-feab-11ea-9b93-51d1cf9093c6.png)

**Comment by parg** [comment]
Nothing has changed in this area recently - is this something that has just started occurring?

**Comment by NaPurHab** [comment]
Java 1.8.0_261 (64 bit)
  Oracle Corporation
c:\program files\biglybt\jre

SWT v4930r7, win32, zoom=100, dpi=96
Windows 10 v10.0, amd64 (64 bit)
B2.5.0.1_B02/4 az3

@kotenok2000 Note that I am running the same version of Windows 10.  The difference is your running RedHat Java.  I tested this twice, I was running Java 1.8.0_202, and the issue you report does not show.  Then I updated it to the latest 1.8.0_261  and still no sign of your issue.

I recommend you test by uninstalling your RedHat Java, and installing the [Oracle Java](http://www.java.com), then test your issue.  If it goes away, it is probabaly caused by the Redhat Java.  Note that the Oracle Java is what would be installed by a clean install of BiglyBT.

**Comment by kotenok2000** [comment]
checked wuth oracle jre
![Снимок экрана (88)](https://user-images.githubusercontent.com/8822292/94212014-ace1e600-fedb-11ea-85c2-34288aaafdbf.png)

**Comment by NaPurHab** [comment]
Hmm, we have the same setup, except that your taskbar looks non-standard.  Are you using a replacement taskbar program?  I use Fences and CursorFX from Stardock. Fences organizes desktop icons, while CursorFX replace the Mouse Pointer with something nicer.  If your using a Taskbar replacement.  Try disabling it, and see if that clears the issue.

Java 1.8.0_261 (64 bit)
  Oracle Corporation
c:\program files\biglybt\jre

SWT v4930r7, win32, zoom=100, dpi=96
Windows 10 v10.0, amd64 (64 bit)
B2.5.0.1_B02/4 az3

**Comment by kotenok2000** [comment]
Still happens on 
3.4.0.1_B12

Will it be fixed?
I want chat windows to be in taskbar.
![image](https://github.com/BiglySoftware/BiglyBT/assets/8822292/8563f585-c161-40bf-9f91-4b6b8c4ccd55)

**Comment by parg** [comment]
I'll take a look

**Comment by parg** [comment]
When I enable "Use independent windows for pop-out chats" in the View->Friends settings I get chat windows that minimize to the task bar. Having said that the pop-out chat windows created when double-clicking a sidebar entry don't get that property.
