### ISSUE TITLE
Request: release API class, source and Javadoc jars, on a publicly accessible repo, and provide plugin dev. docs too.

### ISSUE THREAD

**Issue by rwperrott** [BiglySoftware/BiglyBT#1800]
I found no BiglyBt jars on the main public Maven repos, for possible API use, no proper docs for the Bigly API (not obsolete Vuze), and nothing (decent) for how to develop/assemble plugins for Bigly, other than BiglySoftware plugins source code, with possible better Maven ones not found on "BiglySoftware".

I think that the parent pom.xml of this Maven project, should have this
```xml
            <plugin>
                <groupId>io.takari.maven.plugins</groupId>
                <artifactId>takari-lifecycle-plugin</artifactId>
            </plugin>
```
changed to this
```xml
            <plugin>
                <groupId>io.takari.maven.plugins</groupId>
                <artifactId>takari-lifecycle-plugin</artifactId>
                <configuration>
                    <sourceJar>true</sourceJar>
                </configuration>
            </plugin>
```
so that source jars are also generate.  Adding Javadocs would also be useful to replace source code noise with higher level interface details and documentation, which may be more useful for Javascript dev.

I note that the parent pom has `<version>2.1.0.1-SNAPSHOT</version>`, thus the module jar version too, in the released source zip for Bigly 2.5.0.0, which is a number mismatch and it also seems off having a SNAPSHOT suffix, and this could be confusing.

It would be even better if all the module class, source, and Javadoc jars were released to a publicly accessible Maven repo., so that we don't have to download and build the BiglyBT project locally, only to get a Maven registered jar for the API.

Maybe someone could look at plugin dev. guides too, for how to use the API, and what resources need to be bundled and how to bundle them _automatically_ e.g. via Maven, possibly only on, or prototyped on the wiki.

**Comment by TuxPaper** [comment]
The maven config has been built by the community (mostly by @Shusshu) , and none of the main devs use it, or keep it up to date.  If you have time to spare, we'd accept most Pull Requests related to it.

Back in Azureus/Vuze days, on a release, we'd build a jar with just the Plugin Interface classes, and provide a javadoc for it only.  The plugin dev guide still can be found on [Vuze's Plugin Development Guide Wiki](https://wiki.vuze.com/w/Plugin_Development_Guide). Since the root path class names have changed, the javadocs and pluginapi JARs there are useless for IDEs that utilize them.  However, any remaining guides and overviews over there are probably 90% the same.  I can't speak to the quality of them though -- I'm sure the same code contains embarrassing and outdated methodologies, not to mention they were probably written for Java 5 and lack all the new Java language features that make things more readable.

If we had extra time to spare, we'd build those again. Since there's already a mostly working maven config, I imagine it would be easiest to extend it to build the javadoc jars, and even write out the javadoc html files which could be commited to a website (maybe even using github's website feature).  Writing new tutorials and API overviews would be an enormous task of writing. 
 Fixing bugs and keeping up with user's feature requests always end up getting top priority, which, sadly, is very unfortunate for would-be plugin developers (but fortunate for people with bugs).

**Comment by rwperrott** [comment]
At least the main project is provided as a Maven project, and does seem to build enough to install the core and ui modules in my local repo, so look usable as Maven dependencies for the plugins I looked at.

From looking at some plugins I found, including Shusshu's (via an Issue comment), and it appears that there isn't a proper abstracted API, because the plugins I looked at had dependencies on stuff in both the core and ui modules, including classes, so BiglyBT is the "API".  I expect that some plugins break or behave unhelpfully after BigBT changes, to fix bugs or add features.  The hacked-in Maven "API" jar of Shusshu's looks flakey, but may have been necessary before the main project modules could be build with Maven.

I'll have a look at that Wiki and see how much use it is.  Assuming no copyright blocks, maybe it could be copied to a legacy branch on the wiki here, with modified sections added to a BiglyBt plugin branch as time permits, and marked as a work-in-progress when iffy.

**Comment by Shusshu** [comment]
@rwperrott I never got to build this plugin jar using maven directly but instead I made a profile in the maven pom.xml to run ant to do the job exactly as how @TuxPaper uses it

https://github.com/BiglySoftware/BiglyBT/blob/master/uis/pom.xml#L102

**Comment by rwperrott** [comment]
There doesn't seem any point in leaving this open anymore, because the community development culture seems stuck on (legacy) Ant.
