### ISSUE TITLE
Error: Existing data file length too large

### ISSUE THREAD

**Issue by andrius4669** [BiglySoftware/BiglyBT#1824]
What was done & what happen:
Tried to upgrade ${big_torrent_which_happens_to_have_a_lot_of_stuff} to newer version, which involved renaming dir & rechecking with new torrent file.
On check, got error:
![image](https://user-images.githubusercontent.com/4699695/96047055-2a669980-0e7d-11eb-9c4a-a856b56637c4.png)
(with full filename omitted)
Which probably means that relevant file got re-encoded or something else changed in it.
I tried removing that particular file by hand, but there were more than that.

What should've happened:
Since the file is too large, it should probably be removed and recreated or truncated.
This isn't all that different case from data in files being simply different, that would get overwritten too.

Configuration:
* ArchLinux amd64, oracle jdk 15
* BiglyBT 2.5.0.0
* SwayWM

**Comment by parg** [comment]
Well it warns you because it would be a mistake to silently overwrite a file if it detects that the file is incompatible with the download (too small, perhaps the file hadn't been fully allocated yet, but too large? something's odd). 

There is an option -  Files: truncate existing files that are too large

If you enable that then it'll go ahead and trash files that are bigger than expected.

**Comment by andrius4669** [comment]
Found an option, thanks. Didn't knew it existed.
Yeah, I guess cases like these happen less often, where existing file is too large, but here I stumbled upon it.
Maybe error message could include mention of option? Though current way it's represented (only single line, file name barely fit into that!) may make that sorta hard..
