### ISSUE TITLE
How can I migrate with all accumulated info, statistics etc. to other computer and other platform?

### ISSUE THREAD

**Issue by iav** [BiglySoftware/BiglyBT#1838]
BiglyBT serve hundreds of torrents, running on windows.
How can I move part of torrents (for example, 1000 of total 2000) to other computer on Linux/ARM, keep statistics, notes, tags, editions in trackers, file storage structure?

**Comment by parg** [comment]
BiglyBT has a backup & restore function but

1) I'm not sure how well it works across Windows -> Linux due to the different directory separators
2) It doesn't migrate torrent data

That being said you could try it - use Tools->Options->Backup & Restore to backup the Windows setup, copy the resulting backup data to linux and attempt to restore it into BiglyBT there. Note that you will lose everything in your Linux BiglyBT set up when you do this as it will overwrite.

In the event that it works (all file data will be missing but possibly the torrents, tags etc will be there with existing settings) then you can remove the unwanted torrents, copy the torrent data for the ones you want to the Linux file system and then use 'Search for existing data files' to match them up.

Good luck!

**Comment by iav** [comment]
thank you, will try this way.




---- On Tue, 27 Oct 2020 12:36:08 +0200 parg <mailto:notifications@github.com> wrote ----




BiglyBT has a backup & restore function but

I'm not sure how well it works across Windows -> Linux due to the different directory separators

It doesn't migrate torrent data


That being said you could try it - use Tools->Options->Backup & Restore to backup the Windows setup, copy the resulting backup data to linux and attempt to restore it into BiglyBT there. Note that you will lose everything in your Linux BiglyBT set up when you do this as it will overwrite.

In the event that it works (all file data will be missing but possibly the torrents, tags etc will be there with existing settings) then you can remove the unwanted torrents, copy the torrent data for the ones you want to the Linux file system and then use 'Search for existing data files' to match them up.

Good luck!
