### ISSUE TITLE
Two (marginally related) questions on download priority

### ISSUE THREAD

**Issue by david-bakin** [BiglySoftware/BiglyBT#1860]
[BiglyBT Beta 2.5.0.1_B23]

1. Is there a way to set an entire torrent's download (or upload) bandwidth priority relative to other torrents (similar to the way that _within_ a torrent you can set a file's download priority relative to other files in that torrent)?
  
   (My desire is to increase that torrent's use of bandwidth relative to the other torrents in case bandwidth down (or up I guess) is oversubscribed.  Not a request to pick torrents off of the "queued" state in a priority order.)

1. On the "pieces" pane of a torrent being downloaded there's a "priority" column with 4 digits numbers shown.  What do those numbers mean, and how do they relate to the file's priority as shown/set on the "files" pane (if they do relate)?

(In case you're wondering, these questions are related because they both contain the term "priority".)

**Comment by parg** [comment]
1. An attempt was made a while back to bias upload by applying upload limits and automatically varying them to attain prioritization

See https://github.com/BiglySoftware/BiglyBT/wiki/Speed-Limit-Scheduler#UploadDownload_Priority

However by its nature it is somewhat non-optimal as it has to restrict one set of torrents in order to try and 'push' upload bandwidth to another. It was created for a user who had a lot of seeding torrents and was keen to push bandwidth to private trackers ahead of public ones.

There is a Tag option called 'upload priority' - this works at a low level, giving torrents with it set priority at the network dispatch level, might help a bit

2. the piece priority is constructed from various things such as
a) rareity in the swarm
b) file priorities
c) 'prioritize start/end pieces' option
d) sequential down settings
e) ...

The higher the number the more likely it is to be scheduled for download

**Comment by david-bakin** [comment]
Thanks!

**Comment by david-bakin** [comment]
I decided to open this again (after I closed it) to ask another related question.  

I sometimes have a lot of torrent downloads in the queue, typically I keep 5 operating at once.  Most are very well seeded but some have only 1 or two seeds, or worse, you get to 100% only by a bunch of peers none of whom are seeds.  And in these torrents too the seeds come and go.  (You're familiar with all of this, of course.)

Anyway, when I notice a torrent in this condition - downloading slowly, few seeds or the one seed comes and goes - I set it to "forced downloading".  

What I'd like is for those torrents to have a higher _download_ priority, so that if anything at all is available for them, it gets sucked down.

Is that sort of thing accounted for in the "piece priority" calculation?

**Comment by parg** [comment]
Piece priority only works within a download, there is no cross-download piece level prioritisation (although someone once started working on this many years ago I believe but abandoned it).

That being said, downloads are normally prioritized on their order in the download queue (Options->Queue->Downloading), the  higher up the list (lower index) the more download network resources they should get.
