### ISSUE TITLE
BiglyBT did not shutdown tidily [It was TOLD TO by Signal from Windows OS]

### ISSUE THREAD

**Issue by dbareis** [BiglySoftware/BiglyBT#1870]
If BiglyBt is running and you ask Windows to "**shutdown**" or "**restart**" the Operating System asks all applications to close.  BiglyBT seems to ignore the shutdown signal as after the reboot it displays a warning alert:

`BiglyBT did not shutdown tidily. Check for any diagnostic log files. Also read the wiki article BiglyBT Disappears for more information.
`

BiglyBT 2.5.0.1.B26 (latest beta) on 2004 Windows 10 x64.
```
Java 1.8.0_202 (64 bit)
  Oracle Corporation
c:\program files\biglybt\jre

SWT v4930r7, win32, zoom=100, dpi=96
Windows 10 v10.0, amd64 (64 bit)
B2.5.0.1_B26/4 az2
```

_The about info could be more specific, my exact version is_: **10.0.19041.630**
**The last 10 years of WIN10 would look the same as it currently stands**.

![BiglyBt shurtdown](https://user-images.githubusercontent.com/295230/99613511-cc286a00-2a6b-11eb-90b4-31e74a6b5f6a.png)

**Comment by soroosh-chabi** [comment]
I've a similar problem and will be working on a fix for it.

**Comment by soroosh-chabi** [comment]
I haven't been able to find the time to work on this lately and it is unlikely that I will in the foreseeable future. For anyone wanting to take up this issue, the following is a synopsis of what I have found.

During shutdown, [Windows sends a couple of shutdown related messages to every message queue](https://learn.microsoft.com/en-us/windows/win32/shutdown/shutting-down#shutdown-notifications). The first is `WM_QUERYENDSESSION` which BiglyBT doesn't handle and that would mean that it doesn't mind the system shutting down. BiglyBT does handle the second, `WM_ENDSESSION`, by asynchronously exiting. Since Windows expects the shutdown work to be done synchronously to the receipt of `WM_ENDSESSION` message, it will assume that BiglyBT is ready for the system to actually shutdown. This might not be a problem when there are no active torrents but if that is not the case, then BiglyBT will wait 20 seconds before exiting so their tracker updates are finished during which time, the system will likely shutdown and the next time it starts up, BiglyBT will report that it did not shutdown tidily.

It might be worth noting that BiglyBT probably [doesn't have to actually exit when it receives a `WM_ENDSESSION` message.](https://learn.microsoft.com/en-us/windows/win32/shutdown/wm-endsession#remarks) Stopping all network activity and saving all unsaved data should be enough. Windows will take care of killing the process. But stopping network activity and saving data should be done quite quickly ([probably less than five seconds](https://learn.microsoft.com/en-us/windows/win32/shutdown/wm-queryendsession#remarks)) so BiglyBT doesn't end up blocking system shutdown.
