### ISSUE TITLE
Unmounted filesystems in Linux containing data are not mounted, resulting in "Error: Data Missing" when seeding and "Save location is invalid" when downloading

### ISSUE THREAD

**Issue by Clae224** [BiglySoftware/BiglyBT#189]
Ubuntu 17.10 (Technically Pop! OS but it's pretty much ubuntu 17.10)
BiglyBT 1.2.0.0
GNOME 3.26.2

I currently have set BiglyBT to download and seed files on a NTFS partition. In Ubuntu (and I assume other distros) NTFS partitions aren't mounted by default, and aren't mounted until the user mounts it or another program like a file manager wants to access it. BiglyBT therefore cannot read or write and data on startup, requiring torrents to be restarted/redownloaded once the user manually mounts the filesystem(s).

Currently, BiglyBT doesn't mount filesystems for data, and will produce "Error: Data Missing" when seeding and "Save location is invalid" when downloading if the data is pointed to an unmounted filesystem.

BiglyBT should detect and mount NTFS or other unmounted filesystems for torrent data when it is needed. 

A workaround is to add the filesystem(s) in question to /etc/fstab to be mounted on startup.

**Comment by parg** [comment]
It isn't really BiglyBT's job to go around mounting file systems.

**Comment by Clae224** [comment]
Hmm - I hadn't though about it that way. You can close this bug or mark as an enhancement, but I was confused for a day while trying to figure out why my file manager could access the files but BBT couldn't. 

A warning message might be nice, just scan if the file location is listed in /etc/fstab, and warn the user if it isnt mounted by default.

**Comment by ferdnyc** [comment]
> A warning message might be nice, just scan if the file location is listed in /etc/fstab, and warn the user if it isnt mounted by default.

One issue, I think, with that suggestion would be that if an NTFS filesystem isn't automounted, by default it's _not_ listed in `/etc/fstab`. And if it **is** listed in `/etc/fstab`, as you say, it can be configured to automount (if it isn't already). My system has three NTFS partitions on it, and the only one listed in `/etc/fstab` is `/boot`.* 

(There's also the issue that if the filesystem isn't mounted, the directory where BiglyBT is configured to work won't exist... but it also most likely won't match the mount point. BiglyBT would have to walk its way up the directory path, testing if each level matches any of the configured mount points in `/etc/fstab`... like @parg says, that doesn't really seem like its job.)

I'm not sure there's really anything practical that BiglyBT can (let alone _should_) be doing here.

\* – (Yes, I have Grub on an NTFS partition. It works surprisingly well! And I can change the default or next-default boot selection from Windows, which was the whole reason for doing it. My `grub.cfg` uses `savedefault` to update the default boot target to the currently-selected one, so that rebooting Windows to install updates doesn't automatically go back to Linux. But then I had to worry about missing/forgetting the Grub prompt when I _wanted_ to switch back from Windows to Linux. Now I can just update `G:\grub2\grubenv` before rebooting. I keep meaning to make a Windows app that will let me do it in one click, but haven't gotten around to it yet.)

**Comment by gr88** [comment]
gr88 referenced this issue 3 minutes ago
Change Data Directory instructions #1309
