### ISSUE TITLE
[Linux] UI starts rapidly flickering

### ISSUE THREAD

**Issue by txtsd** [BiglySoftware/BiglyBT#1899]
Just going about my day adding RSS Feeds and torrents, and this starts happening:
[Video of issue](https://0x0.st/ihmi.mkv) (1.7MB)

* OS: Arch Linux
* BiglyBT Version Number: 2.5.0.0
* For *nix: Openbox, no DE
* System info:
```
Java 14.0.2 (64 bit)
  N/A
/usr/lib/jvm/java-14-openjdk

SWT v4940r23, gtk/3.24.23, zoom=100, dpi=96
Linux v5.9.12-2-ck-zen, amd64 (64 bit)
B2.5.0.0/4 az3
```

**Comment by Zaiju-code** [comment]
I just had a similar issue. Manjaro Linux i3wm. Sometimes the UI will just start flickering oddly (the text will appear and disappear, the rest of the UI stays visible and appears to still respond. This issue is the only other place I'm seeing anyone discuss the problem. Any idea what I could do to try to resolve the issue?
