### ISSUE TITLE
Plugins

### ISSUE THREAD

**Issue by Shusshu** [BiglySoftware/BiglyBT#19]
I'd like to migrate my plugins to BiglyBT.

Could you provide the API jar on the github repo maybe as a side module that can act like a maven repository ? or publish to maven central ? or worse case a jar and I'll do as before ;) 

https://github.com/Shusshu/azureus-plug-globalinfo
https://github.com/Shusshu/azureus-plug-timedautostart 
Note: This is extremely ugly code from 10-12 years ago 

I'll try to figure a way to produce the API jar via maven and the current code base.... (assuming I only export the package ...plugin...  only interfaces) (Probably with http://maven.apache.org/plugins/maven-assembly-plugin/plugin-info.html )

**Comment by TuxPaper** [comment]
@parg  does the API jars, so I'll let him handle that.

But I do have a TimedAutoStart with changes, since the source was under http://svn.vuze.com/public/plugins/TimedAutoStart as well.  I've attached a diff, and can probably do a pull request once I figure out how that actually works in IntelliJ ;)

[TimedAutoStart.diff.txt](https://github.com/BiglySoftware/BiglyBT/files/1212357/TimedAutoStart.diff.txt)

We never had the GlobalInfo plugin on http://svn.vuze.com/public/plugins/ so unfortunately, it didn't get into the refactoring tool or manual migrations I made.  (fwiw, all the plugins in http://svn.vuze.com/public/plugins/ are ready to be biglybt plugins, we just chose to limit the biglybt plugin list to ones we knew people used, since there's a lot of dead ones in that list)

**Comment by Shusshu** [comment]
I don't mind updating it myself, well I won't cleanup the dirty ugly code but at least make it work on BiglyBT.

I couldn't figure a way to do the plugin-api.jar with maven

**Comment by TuxPaper** [comment]
I imagine we'll be using something similar to what's in https://svn.vuze.com/public/client/trunk/build.xml

Most importantly,
`
	<patternset id="pluginapi.inc">
		<include name="org/gudy/azureus2/plugins/**" />
		<include name="org/gudy/azureus2/ui/swt/plugins/**" />
		<include name="org/gudy/azureus2/ui/swt/views/*IView*" />
		<include name="org/gudy/azureus2/ui/swt/IconBarEnabler*" />
	</patternset>	
`

Which is all now `com/biglybt/pif` and `com/biglybt/ui/swt`.. although I don't think we need the last two anymore.

And here's the relevant jar bundling snippet
`
		
		<jar destfile="${dist.dir}/${build.name}_pluginapi.jar" level="9" >
			<fileset dir="${build.dir}">        <patternset refid="pluginapi.inc"/> </fileset>
			<fileset dir="${azureus2.dir}/src"> <patternset refid="pluginapi.inc"/> </fileset>
		</jar>
`

( Note, I wrote this comment probably more for me than you :P )

**Comment by Shusshu** [comment]
Well I can also have a try, because I think we shouldn't add an ant script but convert this to maven :)

**Comment by akidburn** [comment]
Wrote a fix for autostop. perhaps integrate it into the website?

greetz akidburn

https://github.com/akidburn/BiglyBT-plugin-autostop

**Comment by parg** [comment]
See https://biglybt.tumblr.com/ for details of published plugins
