### ISSUE TITLE
Add to vote improvement: IP Filter selectable refresh quicker than the default of 7 days

### ISSUE THREAD

**Issue by user8446** [BiglySoftware/BiglyBT#190]
There would be quicker catch performance on the IP filter if we could select something other than the default seven days as some lists are updated every few days. I do realize you can "load now" to do it manually but that's what automation is for :)
Thanks for the development!

**Comment by parg** [comment]
Check out B23 (join the beta program, see the Help menu to do this)

**Comment by user8446** [comment]
Thanks! I see the option in the latest v1201_B23. While on topic, the "clear filter when reloading. During the reload process IPs will not be blocked..." option seemingly would allow IP's that we're on the blocklist through until the next list reloads. All it takes is one time for your IP to leak through if there are downloads/seeding running when an autoload initiates. Is there a way for the current list to persist while the new list is loaded?

**Comment by parg** [comment]
With this option enabled there is a small window in the filter reload process when there is the possibility of an IP not being blocked. This is because during the reload the existing filters are cleared and then the new ones added. Due to the potentially large amount of memory used by the filters (a lot of work was put into minimizing the memory usage when there are millions of blocked ranges) it was deemed best to avoid loading two sets of ranges into memory at the same time during the process.

If you disable this option then the newly loaded ranges are loaded "on top of" the existing ones - duplicates are discarded when found so memory usage isn't impacted. However the draw-back of this approach is that if the existing filters had, say, 1.2.3.4 blocked, and the new ones didn't, the address won't be unblocked until you restart and things are loaded afresh.
