### ISSUE TITLE
Quick Rename of sole file in Queued or Stopped torrent fails

### ISSUE THREAD

**Issue by david-bakin** [BiglySoftware/BiglyBT#1917]
(BiglyBT Beta 2.6.0.1_B01, Windows Datacenter 2016)

Quick Rename of a file in a Queued or Stopped torrent fails for me now in the exact use case where it used to work.  This possibly started just before 2.6.0 - I'm not sure.

Scenario:

Given a single-file torrent in Queued or Stopped state, select the file from Files tab and use Quick Rename.  Get an error dialog which says "The operation failed, probably due to invalid target selection: move operation already in progress".  There is no move or any other operation in progress: these are torrents just waiting patiently for their turn, way down in the list.

However: Quick Rename _does_ work for a file in a torrent with multiple files!

**Comment by parg** [comment]
Darn it, why do people discover these things just after a release!!!! I'll take a look :(

**Comment by parg** [comment]
Fixed in B02 when built! Thanks

**Comment by david-bakin** [comment]
So I confirm this is fixed in B02.  

But then I took a look at fcac6bef6027d15182a0bcddf4356e8ef5c5f7e3 to see what the fix was.  And I don't know what _broke_ this bit that used to work, but how could it be that the _fix_ took so much code, including a new singleton?  Software is weird.  And I say that after a 45yr career writing code as a highly paid software engineering professional (and not yet finished doing it either) ...

**Comment by parg** [comment]
Well it isn't really a singleton, it is a thread-local variable, but yeah, I don't particularly like it either.

**Comment by parg** [comment]
Bit more detail if you're interested...

Before I introduced the 'disk operations' view in 2.6 file-move operations (either manual or due to 'move on complete' etc) were pretty uncontrolled. Manual moves used to lock the UI during operation so you couldn't manually start a second one for the same download in parallel and cause a mess. But of course an automatic one could possibly kick in and do so. 

So when adding disk-ops I thought I might as well add a test to prevent a second move kicking off before an active one had continued. I did this by testing for an existing move operation being active for the same download.

All seemed well.

What I didn't know was that under a specific circumstance (file level rename of a single-torrent download) this lead to a recursive move operation being created, The UI created one and then the core did so (because the core turns the file rename of a single file torrent into an overall torrent rename). My added test to prevent multiple operations being active for the same download caused this to fail.

Now I could have rewritten things to avoid the recursive move operation but that would require quite a bit of hackery and testing, so I took the lazy (but I admit somewhat fragile) approach of permitting recursive operations to be created by adding the code you see.

**Comment by david-bakin** [comment]
Thanks for that explanation ... very interesting in itself and also when considering how all the different features interact with each other to increase complexity - yet you make it all work.

I'm a back-end guy myself - so when I think "bittorrent client" I'm thinking of the bittorrent protocol, handling all those IP and UDP connections and flow, tracking timeouts, regulating speed, choosing among peers, and so on, the DHT, writing the data efficiently to disk or reading it, etc. etc.  And there's _a lot_ of that in a bittorrent client with a lot of technical challenges (as the libtorrent blog points out from time to time).

But when considering BiglyBT as a very satisfied user I am always **amazed** that in addition to all that mechanical stuff I like so much in finding peers and talking to them and transferring data - BiglyBT is astonishingly _feature-rich_ - not just the UI itself which is very impressive in how it surfaces _so much_ information, but just ... all the features!  Just ... a cornucopia of useful options!

I don't use them all but the ones I use I _really_ like, and together, the features I use really set BiglyBT apart from other b.t. clients.  (Not to mention that it is just totally reliable and nearly trouble-free - and I'm not ignoring the various issues I've posted when I say that, I mean, considering everything it pretty much always just works.)

There's just one or two features left I'm looking for. (Haven't even bothered to mention them as they're not even really that important.)  And if there was a up-to-date tutorial-style introduction to writing plugins, and maybe a small reference guide to the available APIs or object model (whatever it is that plugins use) then I'd actually learn enough JavaScript to write my little feature requests myself...

Thanks for BiglyBT - and as it is the end of the year again - time to hit the contribution button too ...  -- David

**Comment by parg** [comment]
Thanks for your support and input as always! I must admit that the UI side of things is my least favourite - the other stuff is way more fun. The UI library we use is effectively single-threaded, in fact virtually all UI operations have to be performed on the 'UI Thread' otherwise they throw an error. This is good for performance (apart from the constant 'is this the UI thread' tests) as internally no locking is required. However it can make things complicated to arrange. To prevent the UI hanging any significant operations started in the UI need to be taken off the UI thread - e.g. a file move operation.  We have a clear separation between UI(s) and the core - the UI components generally listen for events generated by the core and then switch back onto the UI thread to update the UI. In theory not that complex but the reality is a bit of a mess :)

**Comment by parg** [comment]
(you should tell me what features you want adding sometime, I'm a bit bored at the moment stuck in a new lockdown and with the horrors of a potential lettuce shortage looming due to port closures)

**Comment by david-bakin** [comment]
OK, @parg, but remember you asked for it!  #1920

**Comment by mputtr** [comment]
I'm on v b2.6.0.0/4 az3 and I'm still having this trouble.
I can't quick rename or rename/target without getting the same error.  I tried doing this during leeching, when seeding, after pausing, and stopping. Same error messages :(

**Comment by parg** [comment]
Try the latest beta - see the Help menu for an option to join the Beta Program

**Comment by mputtr** [comment]
Thanks! the beta version works!
