### ISSUE TITLE
Moving option windows after searching for stuff make move slow 

### ISSUE THREAD

**Issue by pseudo555** [BiglySoftware/BiglyBT#1919]
* Win 10 20h2 + Radon rx580 (catalyst 20.12.1)
* BiglyBT Version 2.6.0.0

Clicking on Tools > Option open the options windows.
Staying left click pressed on the windows's title and move your mouse : the window moves normally.
In search filter, type "clipboard"
Wait a bit for the filter to be applied.
Staying left click pressed on the windows's title and move your mouse : the window moves slowly.
Removing the filter doesn't solve the issue.

Don't know if this is a java or a gpu driver bug.

**Comment by parg** [comment]
That's a weird one indeed, I'll take a look

**Comment by parg** [comment]
No idea - doesn't happen on Linux or my Windows 7 VM, just on Windows 10

**Comment by parg** [comment]
Theory is that the way things are currently implemented, in order to filter things BiglyBT has to create all of the config sections (including ones that aren't visible) in order to match their text content against the filter expression. Seems that on Windows 10 this subsequently causes performance issues as there must be some issue with dragging around a window with a lot of (mainly invisible) components. Even clearing the filter doesn't destroy the components.

Not really a high priority thing so marking as feature request, thanks!
