### ISSUE TITLE
Download speed crashes to 0 for minutes on end.

### ISSUE THREAD

**Issue by Lucienne1984** [BiglySoftware/BiglyBT#1974]
The download speed of all my torrents always goes up and down, essentially downloading with a kind of "duty cycle" where it goes really fast, then to 0, over and over. I am using BiglyBT version 2.5.0.0/4. Does anyone know how to fix this.

**Comment by parg** [comment]
Saving to a slow drive such as USB or networked?

Does this happen at the start of a download but then go away or is it constant?

**Comment by david-bakin** [comment]
How fast does it "cycle", and how often?  For me this does happen from time to time - all network traffic from BiglyBT will stop for a period of between 30s to 2-3 minutes.  And then it resumes without me touching anything.  Sometimes this will happen several times an hour, but usually I can go days without seeing it.

I have a belief that some of these pauses can be attributed to an overloaded disk - too much usage by other processes of the same disk that BiglyBt is writing new torrent content to.  Especially if there is a torrent being "checked" too, while torrent transfers are happening.

And I also have a belief - supported by nothing at all - that the shorter pauses are some kind of "recycling" going on where it suddenly - but only very occasionally - decides it needs to mix things up and choose new connections for each torrent.  I have no idea whatsoever how I got this thought and, @parg , if you can debunk it, maybe it'll get itself out of my head.

**Comment by ibra6969** [comment]
same issue here :(

**Comment by david-bakin** [comment]
I would like to add something to my previous comment:  It may not have so much to do with disk pressure as _memory pressure_.  It can show up as disk pressure because I happens during large file copy as follows: If you're doing a large file copy/move between two separate disks - from a _fast_ disk to a _slow_ disk - then Windows can cache quite a large amount of data in memory that has been read but not written.  When it reaches a certain threshold network transfers stop.  When it drops below a much lower threshold they resume.  (You can see this behavior by comparing the Statistics view side-by-side with Task Manager's Memory view while copying multi-gigabyte files from fast disk to slow disk.)

**Comment by parg** [comment]
Update to the latest 2.6 beta (see Help menu to join the beta program) - there is a new Library column called 'Disk Latency' - this shows the torrent's read/write disk latency. Check the values when one of these 'cycles' occurs to see if it coincides with an increase in disk latency. 

You need to enable the column by right-clicking in the table header and selecting 'column setup'

There are also two graphs at the bottom of Statistics/Cache that show total read/write bytes from/to disks that are outstanding.

**Comment by david-bakin** [comment]
I'll check.  Also in the "pieces" view (which is quite mesmerizing to watch ...) when it starts going red (and more and more pieces are started but not completed) that indicates slow writing, correct?

**Comment by parg** [comment]
yup!
