### ISSUE TITLE
Apple 1M MacOS11 and the ARM Java problem

### ISSUE THREAD

**Issue by xeoron** [BiglySoftware/BiglyBT#1983]
Currently, Java is not supported by Oracle on Apple's Arm M1 chips

The Problem:
BiglyBT installer auto downloads and tries to install Java if it is not installed. 

There are some open Java implementation that are built for macOS11 M1 machines such as BellSoft JRE and Azule's OpenJDK, but BiglyBT does not recognized these versions of Java at install time despite being registered in the system as the default java environment. BiglyBT, at run time, will not work right using the version of Java it installed itself with no method to point it to other versions that are fully supported.

**Comment by david-bakin** [comment]
I understand that for simplicity of installation for nearly all users, and possibly also to get a consistent environment for it to run in to reduce trouble reports, BiglyBT installs its own Java.  But I would like to experiment with other JVMs than BiglyBT's preferred one.  (Low priority for me, just for fun.)

**Comment by parg** [comment]
I've had reports that it works fine on the M1 (Mac Mini) with Rosetta 2.

Regarding using different JVMs, check out

https://github.com/BiglySoftware/BiglyBT/wiki/Command-Line-Options

**Comment by deus0ww** [comment]
Could you update install4j to a version that support Arm on Mac natively? It's much nicer to launch from an app bundle instead of CLI and use an ARM JVM.

i4j info: https://www.ej-technologies.com/blog/2020/11/support-for-macos-on-arm-apple-m1/

**Comment by parg** [comment]
@TuxPaper is the person you want, he handles all the build stuff

**Comment by deus0ww** [comment]
Instruction on how to package an app bundle:

Requirements:
- ARM64 JDK >=14 (I used Azul JDK16 from https://www.azul.com/downloads/ )
- ARM64 SWT (I used swt-4.20M1-cocoa-macosx-arm64.zip from https://download.eclipse.org/eclipse/downloads/index.html )
- Files from normal BiglyBT bundle: BiglyBT.jar, commons-cli.jar, Info.plist, app.icns


Working Directory Structure:
- bigly.sh  <- jpackage command
- lib  <-  folder for jars
    - BiglyBT.jar
    - commons-cli.jar
    - swt.jar   <- renamed to swt.jar
- resources
    - app.icns
    - Info.plist  <- remove java/install4j stuff and change CFBundleExecutable to BiglyBT

Example bigly.sh:
```sh
#!/bin/sh

jpackage \
  --type app-image \
  --app-version 1.8.0.0 \
  --description "BiglyBT is a feature filled, open source, ad-free, bittorrent client." \
  --name BiglyBT \
  --dest release \
  --vendor "Bigly Software" \
  --verbose \
  --input lib \
  --icon resources/app.icns \
  --main-class com.biglybt.ui.Main \
  --main-jar BiglyBT.jar \
  --mac-package-identifier com.biglybt \
  --mac-package-name BiglyBT \
  --resource-dir resources \
  --java-options -Dazureus.app.name=BiglyBT \
  --java-options -Dazureus.nativelauncher=1 \
  --java-options -Dfile.encoding=UTF-8 \
  --java-options -Dhttp.maxConnections=512 \
  --java-options -Djava.library.path=\"/Library/Application\ Support/BiglyBT/lib\" \
  --java-options -Dsun.jnu.encoding=UTF-8 \
  --java-options -Duser.country= \
  --java-options -Duser.dir=\"/Library/Application\ Support/BiglyBT\" \
  --java-options -Duser.language=en \
  --java-options -XstartOnFirstThread \
  --java-options -Xms512M \
  --java-options -Xmx2G \
  --java-options -XX:+UnlockExperimentalVMOptions \
  --java-options -XX:+UseZGC \
  --java-options -XX:+ExplicitGCInvokesConcurrent \
  --java-options --illegal-access=permit

```

Notes/Limitations:
- Shared plugins are here: /Library/Application Support/BiglyBT/plugins
- JNI lib (libOSXAccess_10.5.jnilib): /Library/Application Support/BiglyBT/lib
- On Apple Silicon, functions that uses libOSXAccess (notifications, etc) doesn't work.
- Auto update doesn't work.

**Comment by TuxPaper** [comment]
I'll see how easy it is to upgrade install4j and make a 1M installer.  Their latest version even has a universal mac installer, but first I have to request a new open source license.

Thanks for your alternative. if install4j doesn't go well, I'll definitely borrow your work.

**Comment by deus0ww** [comment]
Please fix/update libOSXAccess build on macOS 11.0, too.  I opened the xcode project, saw the amount of warnings and... gave up.

**Comment by deus0ww** [comment]
@TuxPaper Thank you for the recently updated libOSXAccess. From very brief testing, it's loading normally on both Intel and M1 Macs (no warning on startup). When I have time, I'll test functionality.

**Comment by deus0ww** [comment]
libOSXAccess tested on both x86-64 and aarch64:
- Notification works
- Disabling AppNap works
- Launchservices - I don't know what this does.

Note: macOS 11.4 killed all aarch64 JDK >11. See:
- https://github.com/Homebrew/homebrew-core/issues/77954
- https://bugs.openjdk.java.net/browse/JDK-8267235

If you're going to test aarch64 JDK on macOS >= 11.4, OpenJDK17 Early Access build 24 is the only one that works at the moment.

**Comment by TuxPaper** [comment]
We now have an OSX M1 installer at https://github.com/BiglySoftware/BiglyBT/releases/tag/v2.8.0.0

It has Zulu Java 8 for arm64 (M1) included, but, in theory, might use the system java if it's arm64 as well.  The SWT Library and libOSXAccess jnilib are for arm64 as well

I have no way of testing the installer, so I have no idea if it works.  If anyone wants to test the installer, we'd love to hear the results!

**Comment by deus0ww** [comment]
I uninstalled and reinstalled on both Intel (macOS 10.14.6) and M1 (macOS 11.4). The Intel version is working fine except for corrupted folder icon. The M1 version is not installing the app bundle (but the folder icon is showing correctly).

**Comment by TuxPaper** [comment]
> I uninstalled and reinstalled on both Intel (macOS 10.14.6) and M1 (macOS 11.4). The Intel version is working fine except for corrupted folder icon. The M1 version is not installing the app bundle (but the folder icon is showing correctly).

:(

Can I assume it shows the installer UI?  Does the installer pop up any error message?

If you still have the M1 install, can you look for a installation log in /Applications/BiglyBT/.install4J ?  You may have to turn on hidden files (Command + Shift + dot) if you use Finder.  If you can attach it here or e-mail it to tux@biglybt.com, that would help a lot!

**Comment by deus0ww** [comment]
Log files from M1 Installation:
[files.log](https://github.com/BiglySoftware/BiglyBT/files/6805893/files.log)
[installation.log](https://github.com/BiglySoftware/BiglyBT/files/6805894/installation.log)

**Comment by rottegift** [comment]
@deus0ww @TuxPaper The recipe for jpackage in https://github.com/BiglySoftware/BiglyBT/issues/1983#issuecomment-839860902 basically works with a couple additional steps.

1. Install a recent enough arm64 JDK, and a sufficiently old arm64 JDK, for example

```
$ brew install corretto coretto11
$ /usr/libexec/java_home -v 11
/Library/Java/JavaVirtualMachines/amazon-corretto-11.jdk/Contents/Home
$ /usr/libexec/java_home -V
...
    17.0.4 (arm64) "Amazon.com Inc." - "Amazon Corretto 17" /Library/Java/JavaVirtualMachines/amazon-corretto-17.jdk/Contents/Home
    11.0.16 (arm64) "Amazon.com Inc." - "Amazon Corretto 11" /Library/Java/JavaVirtualMachines/amazon-corretto-11.jdk/Contents/Home
...
```

2. Add --runtime-image with the older arm64 JDK to the jpackage invocation in the recipe

```
jpackage ... --runtime-image /Library/Java/JavaVirtualMachines/amazon-corretto-11.jdk/Contents/Home
```

You'll need an arm64 swt.jar from <https://eclipse.org/swt> for example <https://download.eclipse.org/eclipse/downloads/drops4/S-4.26M1-202209281800/download.php?dropFile=swt-4.26M1-cocoa-macosx-aarch64.zip>

in the "lib" subdirectory in the recipe.

I also changed the invocation itself a bit, mostly changing paths.  Here is the exact jpackage invocation I am using now, installed into /Applications/BiglyBT/ (replacing the installer's x86_64 BiglyBT.app) with good results:

```
$ jpackage --type app-image --app-version 3.1.0 --description 'BiglyBT is a feature filled, open source, ad-free, bittorrent client' --name BiglyBT --dest release --vendor 'Bigly Software' --verbose --input /Applications/BiglyBT/.biglybt --icon Resources/app.icns --main-class com.biglybt.ui.Main --main-jar BiglyBT.jar --mac-package-identifier com.biglybt --mac-package-name BiglyBT --resource-dir Resources --java-options -XstartOnFirstThread --java-options -Dfile.encoding=UTF-8 --java-options -Dazureus.app.name=BiglyBT --java-options -Dsun.jnu.encoding=UTF-8 --java-options --illegal-access=permit --java-options --class-path=/Applications/BiglyBT/.biglybt/BiglyBT.jar:/Applications/BiglyBT/.biglybt/commons-cli.jar:/Applications/BiglyBT/.biglybt/swt.jar --java-options -Duser.dir=/Applications/BiglyBT/.biglybt --java-options -Xms128m --java-options -Xmx8G --java-options -Xgcpolicy:balanced --runtime-image /Library/Java/JavaVirtualMachines/ibm-semeru-open-11.jdk/Contents/Home
```

This appears to be working with two small plugin issues. This setup can update from one beta release of BiglyBT to another. There is no reason to use IBM's JDK rather than any other, and likewise, there is no need to used the balanced garbage collector rather than the default; these are just personal preferences that happen to work.

The plugin issues are the Tor plugin and the I2P plugin, both of which have x86_64-only dylibs and trigger a rosetta2 exception when invoked.  My workaround is to use a standalone I2P (they now have an Apple Silicon native beta) and Tor Browser, with the appropriate ports configured in BiglyBT's plugin settings.

There are other plugins that are likely to fail because they are x86_64 only.

```
$ find ~/Library/Application\ Support/BiglyBT/plugins/ -type f -exec file {} + | grep Mach-O
```

Should reveal the relvant dylibs, which will include the transcoder (which I don't use) and possibly the built-in player (likewise).

There may be other small details I haven't discovered yet.

Before doing this I had luck with CLI invocation, using for example

```
# Defined in ...fish/functions/gobigly.fish @ line 1
function gobigly --description 'start biglybt with arm java 11'
set -l BIGLYBT /Applications/BiglyBT/.biglybt
set -l jav /Library/Java/JavaVirtualMachines/amazon-corretto-11.jdk/Contents/Home/bin/java
$jav -XstartOnFirstThread \
-cp $BIGLYBT/BiglyBT.jar:$BIGLYBT/commons-cli.jar:$BIGLYBT/log4j.jar:$BIGLYBT/swt.jar \
-Duser.dir=$BIGLYBT \
com.biglybt.ui.Main
end
```

(set -l makes a local variable, the rest should be fairly obvious from context)

Unlike the jpackage approach, the CLI invocation's BiglyBT cannot restart itself, so one has to quit BiglyBT and run the function above (or comparable script) again.  This is also the case when BiglyBT wants to restart after an update: one has to say "Restart BiglyBT Later" in such cases, then quit BiglyBT and re-invoke the function/script.  One also doesn't get the benefit of the BiglyBT icon with the CLI invocation.

**Comment by parg** [comment]
Actually I got 3DView working

**Comment by deus0ww** [comment]
The Apple Silicon installer seems to be working perfectly for me. Thank you! Now I don't have to manually replace the jar to update anymore.

**Comment by parg** [comment]
Hmm, for me the Tor Plugin worked as it is run as an external process and the Rosetta thing did its magic
