### ISSUE TITLE
Allow Configuration of the Toolbar

### ISSUE THREAD

**Issue by dbareis** [BiglySoftware/BiglyBT#201]
I would like to add options to the standard toolbar (OPTIONS: View->Toolbar), for example "Check Files Exist". 

Vuze used to do that semi-automatically but it (and BiglyBT) don't any more, I want to be able to set up buttons for at least that and possibly other options from the right click context menu.

**Comment by parg** [comment]
Hmm, what do you ,mean by 'semi-automatically'? You've never been able to manually add items to the toolbar AFAIK...

**Comment by dbareis** [comment]
I wasn't talking about add to the toolbar but performing the now lengthy
process of checking files, simply right clicking on a torrent to bring up
the context menu used to perform the test.

**Comment by parg** [comment]
Might be because I only just got up but I still can't figure out your last post :) 

You're saying that right-clicking on a torrent and selecting the 'recheck icon' is a simple task already but you also want to be able to do that by selecting a torrent and then clicking an icon in the top toolbar area to do the same? And possibly other actions that are currently found on the right-click menu?

**Comment by dbareis** [comment]
Hi,

I would like to be able to set up my own toolbar icons.  That's it.

The right click menu is a pain to use and simply right clicking to bring up
the menu used to do what I wanted (as a side effect) at some stage in the
past.

Thanks Dennis

**Comment by parg** [comment]
Check out the latest beta (B30) - under Tools->Options->Interface->Display you can configure which toolbar icons are visible and there are new entries for recheck/files-exist

**Comment by dbareis** [comment]
Thanks, not a generic solution but does the trick for me, thanks
