### ISSUE TITLE
Why is torrent checking so slow for me?

### ISSUE THREAD

**Issue by gabtzi** [BiglySoftware/BiglyBT#2072]
I'm trying to understand why biglybt is so slow at checking a torrent when it completes downloading it. 
I have an AMD Ryzen 9 3900X CPU
My torrents are downloaded on an SSD with about 500mb/s   Read/Write speed. 
The CPU is used by BiglyBT at around 3-4% while checking a single torrent. 

I've tried changing this option to all 3 modes with no difference. 

![image](https://user-images.githubusercontent.com/20220341/113666850-96052300-96b8-11eb-9ba2-52c753733d79.png)

* OS and version: Windows 10 x64 
* BiglyBT Version Number: BiglyBT 2.7.0.2

Any ideas how to improve this?

Compared to other torrent clients (e.g. qbittorrent) this is a very slow procedure.

**Comment by parg** [comment]
The recheck-on-complete isn't optimised for speed (you might be streaming the freshly completyed video and need CPU for other things for example). How about if you force a recheck (right-click option)?

**Comment by gabtzi** [comment]
I'm getting pretty much the same speeds during force re check

**Comment by parg** [comment]
Make an estimate of how many bytes/sec it is hash-checking?

**Comment by gabtzi** [comment]
I think it's much faster when no other torrent is active as it reached approx  85mb/sec. Is it possible that it's throttled when any torrent is active?

**Comment by parg** [comment]
There's obviously contention for disk+cpu although given your specs I wouldn't expect an active torrent to affect things much

**Comment by parg** [comment]
I can speed it up if you're bothered, it is just designed not to max out your system at the moment.

**Comment by gabtzi** [comment]
It would be great if I could select it as an option to hog all resources it can :)

**Comment by parg** [comment]
I'll increase the hash scheduler queues in the next beta (B12)

**Comment by gabtzi** [comment]
Awesome :) Thank you

**Comment by magicmana** [comment]
hello   
if can help  , try to make a test :
check  your  antivirus  software , in "real time protection"  option  if you have .    and   generally you can exclude some folder. 
try  to exclude all  folder used  for torrent  (temp folder , finished folder , etc ).
because some antivirus check every XX minutes  all files  who are  modified  from xx min;  (based on the  file windows modifed date  attribute) .
for sample  if   you have a  torrent who size 10go  currently downloading  and  if you have enabled   allocate space on disk ,  in some case some antivirus  totally  read  this  file  of 10go   every minuts  ,  the result is  that  your  disk  all time  busy by  reading this file.

**Comment by parg** [comment]
B12's available - make sure you have 'aggresive' selected and see how it goes
