### ISSUE TITLE
Please add category-based directories or port azcatdest

### ISSUE THREAD

**Issue by gitoss** [BiglySoftware/BiglyBT#209]
Like Azureus/Vuze, BiglyBT has a beautiful category system to sort the torrents. However, if they are dumped into the same directories anyway one kind of wonders what it is all about.

The plugin azcatdest https://plugins.vuze.com/details/azcatdest fixed this, but isn't ported (yet). Btw it wasn't perfect b/c changing categories on an already stared torrent didn't change the directory.

Please add a [x] Sort files into category sub-folders - Thanks!

Running BiglyBT 1.2.0.0 win32 on Windows 7.

**Comment by parg** [comment]
The plugin is now available in BiglyBT - please report if it is working OK (or not)!

**Comment by ferdnyc** [comment]
_Categories_? Seriously? Those haven't been murdered yet?

(I'm being facetious, since there's obviously still people using them, as evidenced by this request.)

However, it feels at least worth pointing out that the Tags system includes this feature natively, since Tags can each be assigned either or both of an Initial Save Location and a Move On Completion path. Applying a tag with paths defined will change the download / completion location. Assuming, in the case of Initial Save Location, that the Torrent that hasn't been started. (That intentional limitation is the same as azCatDest.) No plugin needed.

**Comment by gitoss** [comment]
Thanks for porting the plugin - will test & report back if something is amiss.

@ferdnyc: Thanks for the tutorials, but please go easy on us oldtimers - I have been using Azureus since the days when the world was young and magic still existed. Using tags indeed seems to cover the feature once you stubmle upon the directory options - though a "use tag's name subdirectory on save/move" checkbox would be just fine, too.  The reason I never used the tag system was that cats worked just fine and it isn't intuitive to look for something else with the same functionality.

**Comment by ferdnyc** [comment]
I apologize that my comments came off... however they came off, it was not my intention. I'm frequently surprised by just how great the distance is between how my words sound in my head, and how they're received by others. But that's my failing, and once again I apologize.

_Believe_ me, I understand, @gitoss — I reached something close to 15 **years** of uptime on my install of  "Azureus" (I never got used to "Vuze", and every single time I had to keep reminding myself to call it that in forum postings and the like),  doggedly sticking with the Classic Interface because that new-fangled sidebar nonsense just never made sense to me. 

Heck, I'd probably still be using Categories myself, if not for Parg telling me at some point, "Categories suck, you should use tags. Categories are old and broken. Tags are fresh and powerful." (I may be paraphrasing a bit.  😉 ) I was only trying to repay that kindness in turn.

**Comment by MartiniGM** [comment]
Can you please port this Auto Categorizer plugin also? http://plugins.vuze.com/details/autocat

**Comment by parg** [comment]
What features of that plugin aren't available with tags (https://github.com/BiglySoftware/BiglyBT/wiki/Tags) ?

**Comment by ferdnyc** [comment]
Have you given any thought to finally dumping the Categories feature completely? Maybe for 2.0.0.0?

I'm pretty sure the Tags featureset has been a complete replacement for Categories since we finished hashing out [RSS Feed Scanner's tagging features](http://vote.vuze.com/forums/170588-general/suggestions/3278233-auto-replace-trackers-in-magnet-links-copy-and-pa) — and that was... holy wow, it was back in January 2014! :laughing: 

I strongly suspect the only reason anyone's using Categories anymore is pure inertia — either that, or they aren't aware that Tags can do everything Categories can do and more, far more powerfully and without requiring additional plugins to add functionality. Maybe those users just need a push to finally switch over.

**Comment by gitoss** [comment]
If you dump categories, maybe add a Tags-lite feature for us simple minded folk who just want to, well, categorize stuff into a single category and move it to the respective subdirectory :-)

**Comment by MartiniGM** [comment]
Since you thought my suggestion was the most stupid on yet in 2019 I decided to look into tags. And after checking it out if does make more sense to use tags. The contains(name,"filter")-constraint and Move on complete options does the job of both the azcatdest and the autocat plugin. 👍 

:)

**Comment by parg** [comment]
Nice :)

**Comment by dark-penguin** [comment]
The plugin (azCatDest) does not work - or at least it does not work according to the description:
```
To assign a directory to a category, open the Plugin's GUI tab by choosing
Plugins -> AZCatDest from the top menu.
```
There is no "Plugins -> AZCatDest" in the "top menu", if I understand correctly what "top menu" means. There is only "Tools" - "Plugins", which contains "Get PLugins", "Install From File" and "Uninstallation Wizard".

After a while, I've noticed a new option - "View" - "azCatDest". Clicking it opens an empty grey window.

Also, the only option this plugin has - "Auto open AZCatDest Tab" - also does nothing, or at least I can't find what does it do. The only tabs I see are those on the bottom, and there is no tab called anything like "categories", "directories" or "azCatDest".

There was a plugin for Azureus/Vuze called "SavePath", which allowed assigning download locations based on categories or other things. It was very good, because if you change the category, the files are moved immediately, regardless of what state the download is. Seems like azCatDest only works if you assign a category before you start the download for the first time?

I've tried to figure out how to use tags, but they hurt my brain. And require too much workarounds to do the simplest things uTorrent had back in the 90s.

**Comment by parg** [comment]
What's your problem with Tags? Workarounds? Simplest things in uTorrent back in the 90s? And you expect a reply? Laughable.

**Comment by dark-penguin** [comment]
I did not want to go into complaining about why exactly tags are a bad crutch for a simple workflow - just wanted to report that the plugin is not working.

Then I realized that the answer will be "forget it, use tags", and so I wrote that I know about tags, but they do not provide an easy workflow like categories, without derailing the discussion.

In short, using tags instead of categories is like learning to operate a programmable industrial mill just to drill a simple hole. Sometimes simpler things are better.

**Comment by parg** [comment]
Create a Tag, set its 'Initial Download Location' to X. If you want to change it to Y and affect existing downloads then select the 'apply to existing downloads' option - I don't understand why that is hard.

**Comment by dark-penguin** [comment]
I create and delete a lot of categories, so creating a tag and then creating a folder for it and then applying it is three times more hassle than just creating a category. Also, if a torrent is already downloaded, then it is no longer governed by "Initial Download Location", but by "Move on complete" location. Also, there is no way to disable "Share tag" checkbox being on by default. Also, when you delete a tag, there is no way to move its torrents to the default location (other than moving each one manually). This is all possible, but far less convenient than it was before.

I'm not against tags - I see that it is indeed a powerful tool that most people like. It's just that they are less fit for my case - and for some other people too, seeing that this issue arises from time to time, and figuring out how tags work is not so easy for them too.

**Comment by ferdnyc** [comment]
> Also, if a torrent is already downloaded, then it is no longer governed by "Initial Download Location", but by "Move on complete" location.

That's true if the torrent is already _started_, yes. But adding a tag with an initial download location set to an _unstarted_ torrent (meaning, one where the `.torrent` file is loaded, but Stopped) will still cause the files to be moved to the tag location when you start the torrent. That was one of the things @parg spent a lot of time tweaking way back when, as I recall.

...Does AzCatDest move files when applying categories to already-started torrents!? I wouldn't have thought it would do that. Seems like a dangerous misfeature.

**Comment by dark-penguin** [comment]
I don't know about azCatDest - I couldn't get it to work. But SavePath did - when you change a torrent's category, it's moved immediately regardless of its state. If it's being downloaded, then it will pause, move, and resume. That makes things very simple.

**Comment by ferdnyc** [comment]
Gotcha. I don't believe you'd be able to do that with AzCatDest _either_. It wasn't a function of Categories vs. Tags, it was a function of that plugin. 

AzCatDest operated in that regard just like tags do intrinsically, if memory serves — the intention was that either type of labeling would be assigned _before_ starting the torrent,  since moving files mid-download makes things unnecessarily complicated and fragile.

(A bunch of effort went into making it possible to auto-tag torrents from everywhere they could enter the system, including other plugins like RSS Feed Scanner, all in the interest of ensuring that tags [and/or categories] could be applied **prior** to the torrent starting even in auto-start situations.)

**Comment by ferdnyc** [comment]
(You can, of course, _manually_ move a torrent's data files at any point in its lifecycle with Advanced > Files > Move Data Files. It's merely the **automatic** retargeting as a consequence of Category / Tag application that's limited to pre-start modifications.)

**Comment by parg** [comment]
azcatdest loads fine for me by the way, although I haven't tried using it the UI seems fine. Do you have any debug for the UI problem?

**Comment by dark-penguin** [comment]
@ferdnyc If it does what uTorrent does (assigning a category means move-on-complete to the folder with the same name), that would already be better than tags. I would suggest porting SavePath, because it makes this really simple and because it supports "save path" based not only on categories, but some other things as well - I don't remember what exactly. But I guess the consensus now is "tags do all that and more, there is no need for more tools for the same task" (which actually makes sense).

@parg I wrote what I could find - wrong description, a checkbox that apparently does nothing, and a menu item that opens an empty... what do you call it... "view" in the main window. I can try other things, if you have any ideas. I'm on Debian Buster amd64 with MATE, and the symptoms were the same on two installations (my main machine and fresh installation of MATE in a Docker container). I've tried to reproduce it on Ubuntu Focal or Eoan in virtualbox, but both times the whole desktop environment crashes the moment I click any button on the main menu right after installing BiglyBT with an installer.

**Comment by parg** [comment]
How about a tag-group option to specify a 'root data file location' - any tags created as a member of that group would automatically have assigned downloads' data files stored in root/tag-name and this would be enforced regardless of when the assignment occurred?

**Comment by dark-penguin** [comment]
That seems like a good idea (to have something that is enforced regardless of the torrent state). Although that would probably require even more click-click-clicking to do (not so useful for my situation, but probably useful for someone else), and even more "figuring out non-obvious mechanics" for new users who have not read this.

Actually, I think it would be easier for both developers and users to do a very basic "category means subfolder" mechanic, instead of adding one more layer on top of already overcomplicated tags. This way, both groups can be happy: if you want complex location rules, use tags, and if you just want simple subfolders, use categories. And it would be very obvious for those who come from other clients.

I took a look at other clients, and apparently qBittorrent does those things very well. I'll try using that, though I could still participate in a discussion about accessibility for "category-based users" if anyone is interested. Or try debugging this issue - I'm a sysadmin, so testing on many configurations is easy (and an aspiring Pythonist, hence the "keep it as simple as possible" paradigm).

**Comment by parg** [comment]
Even more click clicking? Create a Tag, assign it to a Tag Group, set that Tag Group's 'root folder' and from then on all you need to do when creating new Tags is (in the create dialog) select the Tag Group and everything else is done automatically. Anyway, enjoy your other clients.
