### ISSUE TITLE
Keyboard shortcuts to raise/lower a file's priority in torrent

### ISSUE THREAD

**Issue by david-bakin** [BiglySoftware/BiglyBT#2090]
(Ok, this is such a minor stupid request I'd almost be hesitant to even suggest it ... but, unfortunately, I'm basically so uninhibited I'll ask anyway though it probably makes me look trivial, because: _you never know_.)

I'd like to be able to raise/lower a file's priority in its torrent without having to right click priority - and then type in an actual number to a dialog.

* I suggest that `+`/`-` raise/lower the (numeric) priority (0, 1, ...) of the selected file(s).

(There. That's it. My suggestion, for what it's worth ...)

**Comment by parg** [comment]
Done in next beta :)

**Comment by ferdnyc** [comment]
Hmmm... Which Files View? Because, I just installed `2.7.0.3_B17` on Linux (Fedora 33), and if I'm on an individual torrent's Files tab, typing `+` or `-` still goes to the search box, even if I've clicked to focus a file row _and_ checked it to ensure the file is downloading.

I can't (easily) try the numeric keypad `+` and `-`, because I have them globally bound to volume controls. But the `+` over the `=` key and the `-` under `_` on the numeric row of my (US QWERTY) keyboard doesn't seem to want to deliver those keypresses to the file list.

Perhaps the issue is that I'm using BiglyBT over a VNC connection to a headless box with no physical keyboard installed?

**Comment by david-bakin** [comment]
Sadly, what @ferdnyc says is true (for the Files tab in the Incomplete page).  Numeric keypad +/- too. (Windows Server 2016 Datacenter, BiglyBT 2.7.0.3_B17.)

**Comment by ferdnyc** [comment]
> goes to the search box

I meant the **filter** box, of course. Though, its placeholder text _does_ say "Search for files...", so I guess calling it the search box isn't really that much of a stretch.

**Comment by parg** [comment]
hmm, well it works on my Windows 10 so pfttttttttt. I added some logic to ensure that key events weren't processed by the filter box but perhaps that didn't work as expected.

**Comment by parg** [comment]
Hmm, actually, the latest is B18...

**Comment by parg** [comment]
keep up chaps

**Comment by ferdnyc** [comment]
\*cough\* Yeah, and that wasn't rushed out or anything. :wink: 

![image](https://user-images.githubusercontent.com/538020/116792741-94006b00-aa90-11eb-8ee0-274e1967f15e.png)

**Comment by ferdnyc** [comment]
`_B18` does indeed fix my ability to `+` and `-` file priorities to my heart's content! Thanks @parg :+1:

**Comment by david-bakin** [comment]
Works great, _thank you very much!, @parg!
