### ISSUE TITLE
Small visual/scale issue, Icons smaller on sidebar.

### ISSUE THREAD

**Issue by NaPurHab** [BiglySoftware/BiglyBT#2131]
I noticed this and thought I would mention it.  Just one of those things that can be tweaked. Visually annoying to see.

Here are the icons I am using from the icon packs at the top of a view.
![image](https://user-images.githubusercontent.com/37715552/122281272-15348580-ceb8-11eb-8b17-68a1167595d0.png)
and the same from the sidebar:
![image](https://user-images.githubusercontent.com/37715552/122281410-3b5a2580-ceb8-11eb-9b5d-609b43a502ad.png)

The icons in the sidebar are just slightly smaller, and lose detail.  Most noticeable in the `MCU` icon and the `Atom` icon for TV Sci-Fi. They are already small, and getting smaller on the sidebar loses the limited detail available.

So, can they be made the same size as across the top? Please.

**Comment by parg** [comment]
The problem is that the icons at the top are scaled to fit to a 14px height (they all need to be the same height otherwise it looks ridiculous), 

The sidebar icons however are scaled to fit to a 20px width (looks a mess if they don't vertically align, particularly as the text to the right is positioned relative to the icon)

If your icons aren't a multiple of 20x14 then scaling differences will result.

**Comment by NaPurHab** [comment]
The icons in the packs on the **Tag Icons** Wiki page, do not all conform to that ratio.   The Alphabet icons are 72*72, and others are taller.  Some are close, I found one that was 500*349. Using the ratio 20*14, if scaled by a factor of 25 would be 500*350.

Please add the info that icons should be a ratio of 20*14 to the Tag Icons Wiki page.
