### ISSUE TITLE
SFEDF "Piece" mode idea

### ISSUE THREAD

**Issue by ferdnyc** [BiglySoftware/BiglyBT#2145]
I had a thought about the new "Piece" mode in SFEDF that, if feasible, might make it more effective / in line with user expectations.

Despite focusing on torrent piece blocks, the mode is still intrinsically bound to download files. (Primarily because it will only copy pieces that exist entirely in a single output file; any pieces that are shared between two or more files are lost.)

Given that, would it be possible for it to be used as a "fallback" option for the full-file Copy mode, instead of as an either/or choice? I'm thinking something like this:

1. The user chooses "Copy" mode, and scans a set of possible torrent data files
2. Any matches that checksum as 100% complete are copied to the destination in their entirety.
3. If the "fallback to piece mode" checkbox was selected, any candidate files that _aren't_ 100% matches are scanned for matching pieces, which are copied to the destination dir.

If I'm envisioning this correctly and it's feasible for it to operate that way, it should avoid the "piece mode does worse than Copy mode when scanning completed files" issue I brought up in a comment on #2139, and enable a kind of "best-of-both-worlds" approach to SFEDF scanning in Copy mode.

Of course, at a minimum there's a possibility it would require scanning every candidate file _twice_, which might be a deal-breaker if necessary. And there may be other difficulties I'm not even aware of. But, I thought I'd throw it out there.

**Comment by ferdnyc** [comment]
Pinging @parg on this one, sorry to be a pest. 

And like I said, if it's not doable (or even if you'd just _prefer not_ to do it this way), I can totally understand and accept that.

**Comment by parg** [comment]
Sorry for delay in reply, I hadn't forgotten :)

I can understand the desire to make things super optimal in terms of this feature, but there are limits to my interest in working on it :)

The only time someone realistically would use 'piece mode' is when they are importing partially complete downloads from a different bittorrent client (which is where the request for the mode came from). In this instance, as pointed out, you would probably want to initially do a 'copy mode' scan to grab completed files and the follow it up with a 'piece mode' one to grab remaining pieces. Not that this is 100% optimal as it will still miss partial pieces at the end of partially completed files.

Personally I would just point the download at the existing files and do a recheck.

Unless you have an alternative scenario where piece mode is of use?

**Comment by as-muncher** [comment]
> Personally I would just point the download at the existing files and do a recheck.
> 
> Unless you have an alternative scenario where piece mode is of use?

But just pointing the download at the existing files and do a recheck - would the recheck find as much data if the downloaded files have an additional extension?  for instance, files that are .jpg are .jpg.!qB

**Comment by parg** [comment]
SFEDF would work for files larger than a piece, I suppose I could add some logic to ignore additional extensions for smaller files

**Comment by parg** [comment]
Actually there is already logic there to pick a file that is the correct size regardless of name - that should work in 99% of cases I'd have thought...

**Comment by parg** [comment]
Anyway, even if it could fix up to your blah.!qB files, you'd end up with those files being permanently named like that (i.e. BiglyBT wouldn't magically remove the .!qB extension when the download completed). So I'm afraid you just need to manually rename the files to remove the .!qB before attempting to fix them up.

**Comment by parg** [comment]
How about if I added a feature under "Help->Advanced->Remove File Extensions" that given a root folder and an extension (e.g. !qB) it would go through that folder hierarchy and remove that extension from any files it finds?

**Comment by as-muncher** [comment]
Well, I have noticed that BiglyBT WILL change the file extension to the proper one that is described in the .torrent file after the file has completed downloading.  

The reason I want to use the copy mode and then the piece mode to check for existing completion, is just because if I try to copy the files over into the download directory from their original directory, and then have biglyBT do a forced recheck, is that when I do a copy, Windows will do a full copy, so only if 1 MB is downloaded of 1 GB, that whole 1 GB is going to be copied to my biglyBT directory.  

I recently tried it out with doing a copy mode check, then a piece mode check, and because I have the "add .!qB extension" enabled, when biglyBT does a copy mode check, or at least when it does a piece mode check, it renames those files with the .!qB extension, and I'm just talking about screenshots/thumbnails right now out of a larger torrent.  The problem, then, is that when I go back to do a copy mode check, I think biglyBT doesn't look for the original extension (like .jpg) described in the .torrent file, but instead (I think) now starts looking for those thumbnails with a .!qB extension, and I would like it to look for both extensions, say .jpg and .jpg.!qB (.!qB is an example - I mean whichever additional extension is chosen in the biglyBT options).  I had downloaded the entire screenshots folder in my one torrent, and so biglyBT did a search, and I think it was a recursive search (hopefully - maybe that might be nice to indicate that the search will be recursive), and so even though I had downloaded all the screenshots, and I did a copy mode search, then a piece mode search, biglyBT said that it would need to still download a number of screenshots.  Maybe that one 4 MB piece included a lot of those screenshots.  But when I selected 1 specific .jpg file, and did a copy mode search and a piece mode search, and pointed it to my original directory which was fully downloaded (the screenshots directory), biglyBT couldn't find that one file, even though it was right there in the directory.    So if you could check that, if biglyBT is actually searching for a file with the extension as indicated in the options, rather than the one described in the .torrent file.  My request is that biglyBT would search for the .torrent file one and also the .torrent file one with the one in the options menu.  

The only reason that I added that .!qB extension, is because I was hoping that biglyBT would automatically search the file, if it's an exact match for size, but just has a different extension, whether .!qB or whether the transmission extension or whether the utorrent extension, and will do a recheck or a check for existing data files, and find that data, so that I don't have to go through and delete all those extensions myself using Rename Master or other program.  I'm looking for an easy way to transfer files over.  I would probably anyways add an extension for biglyBT like .!bg or something like that just because I don't like when I think I've got a full file when really I don't.  

I've noticed when I have done a copy mode check and then a piece mode check for larger files too, large video files, that biglyBT will still say that there are 2 pieces missing, even though those files were downloaded fully.  I thought that biglyBT did a hash for every file described in the .torrent file.  If so, then it would make sense to compare that value for each file when doing a check, so I'm not sure why it would still say that there are 2 pieces for each large video file missing.

**Comment by parg** [comment]
It changes the file extension if you have configured BiglyBT to use an incomplete file extension at the time the download was started, not if you happen to have some random other additional extension already applied to the files.

**Comment by as-muncher** [comment]
Well, thanks for that information.  I hope that you will look into the other issues I mentioned about biglyBT not finding the files it needs to find and incorporate.  and thank you for your work

**Comment by parg** [comment]
You need to understand the fact that pieces generally span file boundaries. When matching a file it is most likely the first and last piece of that file include other files in the torrent - hence you have 2 pieces "missing" (start and end). If the other files are also fixed up correctly then things will work out OK.

**Comment by as-muncher** [comment]
Couldn't you write it so that the whole file will remain untouched, as a complete file?  Doesn't each file have its own hash?  Even though in my mind, I know the file is complete, at least the hash would say that the file is complete, even though the beginning and end are "incomplete", that incompleteness could be applied to the other files included in those pieces.

**Comment by as-muncher** [comment]
If I copy the downloaded files from my other torrent client into the biglybt download directory, I'm copying the full file as if fully completed.  If I do a copy mode search first, then a piece mode, I find that I'm missing pieces.  I just don't want it to be where I'm stuck at 99.8% because biglyBT couldn't find the proper files, the pieces, or whatever, and then there are no seeders.  I just want as complete a transfer as possible, and as easily as possible.  But I'll say that having this feature to check by pieces and to integrate it from various copies of the same file downloaded at different times by different torrent clients, is a big reason why I started using biglybt, and I think the ability to use the i2p and tor networks is a big big plus, too.

**Comment by parg** [comment]
No, each file does not have its own hash - that is one of the aspects of the original torrent file format that makes things complex...

**Comment by as-muncher** [comment]
So, it's best if I just copy the files over using my operating system, to the biglybt download directory, and then do a recheck?  Or would you do a copy mode then a piece mode search?  Or how would you do it to get the most transfer?

**Comment by parg** [comment]
Yup, copy the files, remove any incomplete suffix (.!qB or whatever) so that the files have the correct names for the torrent and then  add the torrent for 'seeding' in the 'torrent options dialog' (there's a drop down menu for this)

**Comment by as-muncher** [comment]
I guess, ideally, if you have lots of room.  Otherwise, if you've only downloaded 1 MB of 1 GB, the whole 1 GB will be copied into the download directory if you use your operating system to copy it.  
I'll have to keep this in mind - perhaps then if I've downloaded the whole screenshots directory, then I'd just copy that over, and any fully downloaded video files (as an example) to the downloads directory, then add the torrent for seeding, then pause it, then do a piece mode search for everything else that was only partially downloaded, right?

**Comment by parg** [comment]
Not really sure what you're trying to achieve here. If you want to migrate your download from another torrent client (that has downloaded the files to location X) to BiglytBT (which by default downloads to location Y) then either

1) rename files in X\whatever to remove extra extensions and point BiglyBT at X when you add the torrent for seeding

or

2) move the files from X to Y, rename and point BiglyBT at Y

Not sure why you would be copying some files to Y and leaving some in X.

**Comment by as-muncher** [comment]
If you want to do the coding to remove an extension, go for it!  I'm not quite sure yet if I personally would use it.

**Comment by ferdnyc** [comment]
Personally, I 100% regret suggesting this. (And re-opening a thread that, I agree, really doesn't feel worth pulling any father than it's already been pulled.) Any time we're talking about having to re-download _image_ files -- or any files smaller than a piece -- I feel like perspective has been lost.

Any file smaller than a piece, it's best to just assume it will have to be re-downloaded after any sort of file migration. I don't even bother trying to import those, I just leave them incomplete even if I **do** have them because (at this point) I know importing probably won't work. Who cares? We're talking < 0.1% of the total size of most torrents. It's lost in the noise. The communications overhead between the trackers and peers will eat more bandwidth than that.

The only sensible approach, seems to me, is what BiglyBT already does: Optimize for efficient handling of the _other_ 99.9% of the torrent, and don't sweat the small stuff.

**Comment by as-muncher** [comment]
> Personally, I 100% regret suggesting this. (And re-opening a thread that, I agree, really doesn't feel worth pulling any father than it's already been pulled.) Any time we're talking about having to re-download _image_ files -- or any files smaller than a piece -- I feel like perspective has been lost.
> 
> Any file smaller than a piece, it's best to just assume it will have to be re-downloaded after any sort of file migration. I don't even bother trying to import those, I just leave them incomplete even if I **do** have them because (at this point) I know importing probably won't work. Who cares? We're talking < 0.1% of the total size of most torrents. It's lost in the noise. The communications overhead between the trackers and peers will eat more bandwidth than that.
> 
> The only sensible approach, seems to me, is what BiglyBT already does: Optimize for efficient handling of the _other_ 99.9% of the torrent, and don't sweat the small stuff.

Words of wisdom, gives good perspective.  :)
