### ISSUE TITLE
Moving data files to a UNC path

### ISSUE THREAD

**Issue by robgilde** [BiglySoftware/BiglyBT#2177]
My workflow sometimes has me changing the path to the data files of a torrent.  I use the `Torrent > Advanced > Files > Move Data Files...` operation.  Instead of having BiglyBT actually move any files, I specify a new folder where the files already exist.  This works perfectly, except:

If the new folder is a UNC path (a Windows file share), if the files already exist in the new location, BiglyBT fails to change the path to the data files and does not appear to do anything.  In the BiglyBT log, I see:

`renameFile: target file '\\server\path\file' already exists, failing`

* Windows 10 Pro 21H1
* BiglyBT 2.8.0.0

**Comment by parg** [comment]
Hmm, I've done a bunch of testing and it all seems to work fine for me :(

**Comment by robgilde** [comment]
Thanks for looking into this issue.

After more testing I have determined that the error occurs iff the **source** file also exists.  Examples:

move from C:\foo\alpha to \\server\path\alpha:

- if the data files **do not exist** in C:\foo\alpha and **do exist** in \\server\path\alpha WORKS
- if the data files **do exist** in C:\foo\alpha and **do not exist** in \\server\path\alpha WORKS (files are copied)
- if the data files exist in both places then FAILS

Also, this I determined that this behavior has nothing to do with the target being a UNC path.  That was a red herring.

I think this is still unexpected behavior, but there is no strong use case for making this one case work, so I'm happy to let this issue drop.  I apologize for not isolating the fault better before I filed.

**Comment by parg** [comment]
Ah, thanks for clarifying!

An alert actually is raised (yellow triangle icon at right end of status bar) saying

Download data move operation failed
com.biglybt.core.download.DownloadManagerException: rename operation failed
	at com.biglybt.core.download.impl.DownloadManagerImpl.moveDataFilesSupport0(DownloadManagerImpl.java:5567)
	at com.biglybt.core.download.impl.DownloadManagerImpl.lambda$0(DownloadManagerImpl.java:5295)
	at com.biglybt.core.disk.impl.DiskManagerUtil$6.run(DiskManagerUtil.java:2340)
	at com.biglybt.ui.swt.progress.ProgressWindow$4.run(ProgressWindow.java:386)
	at com.biglybt.core.util.AEThread2$threadWrapper.run(AEThread2.java:317)

but is obviously isn't very clear what the cause is.

I think the operation probably should fail in this case as after a 'move' operation you would not expect files to be left in the source location (and you definitely wouldn't want the source files to be deleted on the assumption that whatever was in the target location was the same content).

**Comment by robgilde** [comment]
Makes sense.  Thanks!
