### ISSUE TITLE
Possible run-as-a-service in windows?

### ISSUE THREAD

**Issue by TheBestPessimist** [BiglySoftware/BiglyBT#23]
Hello,

I am using a windows machine @home and at times, when the power dies (that happens way more often than i would like), my router (ddwrt) starts my computer when the power is back on.

I was curious if there's a chance that bigly could be used as a service, so that even though i am not logged in on my machine, i could still seed/download stuff after the restart.

The way i imagine this feature is that i can still use the GUI when i am logged in to manage my stuff, just that there is service that always starts with windows.

Is this a viable option?

Thank you.

**Comment by TuxPaper** [comment]
It's not possible with the native UI, since that heavily relies on direct (same process) access to the core.

With a bit of work, you might be able to get the app to run in console mode as a service (since it's a service, it would have to be told where your config dir is, and have write access to it), and then on login, auto-run a script that shuts down the core, and restart it in with a UI.  That's not the best solution, since it has to reconnect to all your peers again, etc, but it could possibly work.

Another option, which I have a feeling you probably don't want, it to have your Windows machine auto-login on reboot. :)

**Comment by TheBestPessimist** [comment]
It seems like some work is needed for this one to be functional. hmm i might try, but it seems like a headache.

No, autologin is not an option :^).

**Comment by SactoJosh** [comment]
You can just do what I do and have your PC set to auto-login on startup and then also have BiglyBT auto-start with Windows. "Unexpected reboot problem" solved
