### ISSUE TITLE
BiglyBT no longer check complete pieces of existing files

### ISSUE THREAD

**Issue by SUCM** [BiglySoftware/BiglyBT#2322]
not sure if some settings changed after upgrade, but I started noticing BiglyBT no longer perform check on existing files when adding a torrent despite new torrent panel shows a prompt that some files already exists. this caused the newly added torrent to always report 0% complete on all files and tries to download everything from scratch. if I stop the newly added torrent and manually do a re-check, then BiglyBT would correctly identify completed pieces on existing files

I remember BiglyBT used to automatically perform re-check on existing files, so not sure if the behaviour change is a bug or not

* Win10
* 2.8.0.0

**Comment by as-muncher** [comment]
Java 1.8.0_202 (64 bit)
  Oracle Corporation
c:\program files\biglybt\jre

SWT v4942r22, win32, zoom=100, dpi=120
Windows 10 v10.0, amd64 (64 bit)
B2.8.0.0/4 az3

Yeah, that's been happening with mine too, but I think it happens with only certain torrents, not all.  For some, they start checking right away.  I think that I have the option to start torrents stopped or paused, so when I add a torrent and leave it that way, even if I change the directory from x-1 to x, it will start automatically checking, but sometimes, when I change the state to Queued in the Add Torrent dialogue, then it won't check right away, but starts at 0%.  I'm not sure if this happens consistently or inconsistently.  But there is something there to be looked at, for sure.

**Comment by rlbf** [comment]
I'm having this problem as well. Absolutely any action on the torrent causes it to go to 0%. E.g. Windows just forced a reboot and after the reboot all torrents went to 0% and are now downloading all over again. Telling it to re-check them does nothing. The data is still there because I know some were complete, and the files are still present and correct, but it wants to download everything again. Another scenario where it happens is if after completion, a torrent is in a queued state, and I force it to seed, it goes to 0% and again, telling it to re-check doesn't do anything. This is with 2.9.0.0. It's making it pretty unusable as it has just thrown away about 3 days of downloaded data.

**Comment by parg** [comment]
Any errors in the console or debug_1/2.log files in the logs directory?

**Comment by parg** [comment]
(a lot of people are using BiglyBT 2.9 just fine on Windows so it would seem likely to be something specific to your computer/configuration - e.g. a failing disk drive)

**Comment by rlbf** [comment]
I just tried stopping a torrent and forcing a re-check, again it went to 0% and nothing was written to any files in the logs directory.

It was doing this when I was saving files to the main system drive. I recently bought a new SSD and have since been saving files to there instead, and it's still doing it. I've been using it for years without ever having this problem before.

**Comment by parg** [comment]
Turn on logging (Options->Logging), open the console (Tools->Console), double click it in the sidebar to pop it out as a separate window, then force recheck a download.

You should see the results of piece checks in the console at least

**Comment by rlbf** [comment]
Thanks, it was rather busy, so I left all warnings and errors enabled, but only left the pieces category enabled for information. When I told it to re-check a torrent, nothing at all appeared in the console.

There are quite a lot of messages containing the text "peer has sent piece ..... but expired piece block discarded as already written" which might be due to it seeing that the data is already there at that stage?

I looked at both drives with CrystalDiskInfo, and it doesn't report any problems.

I'll perhaps try re-installing BiglyBT once it has re-downloaded everything.

**Comment by parg** [comment]
You could go to the Help menu, select Advanced->Show Configuration Changes...

If you're happy with the contents either paste it here or email it to parg@biglybt.com

Perhaps you have a config setting that is causing issues.

**Comment by parg** [comment]
OK, I've found a setting that you might have changed that can cause this: 

Options->Files: Use Fast Resume mode

This should be set to TRUE - it seems as if setting it to FALSE screws up rechecking

**Comment by as-muncher** [comment]
I have fast resume mode on for a long time.  This error also might happen when I pause the torrent, then show in explorer, then delete the incomplete file which has a .!qB extension, then copy in the complete file, then select the torrent, force re-check, and BiglyBT wasn't checking the file, but said it was at 0 %.  I finally had to "search for existing data files"  copy mode, which found the whole file and copied over, added the .!qB suffix, then found it complete and started seeding it, after removing the .!qB extension.

**Comment by as-muncher** [comment]
Java 1.8.0_202 (64 bit)
  Oracle Corporation
c:\program files\biglybt\jre

SWT v4942r22, win32, zoom=100, dpi=120
Windows 10 v10.0, amd64 (64 bit)
B2.9.0.1_B15/4 az3

**Comment by rlbf** [comment]
> OK, I've found a setting that you might have changed that can cause this:
> 
> Options->Files: Use Fast Resume mode
> 
> This should be set to TRUE - it seems as if setting it to FALSE screws up rechecking

Thanks, I was planning to let everything finish re-downloading then do some experimenting with the settings listed when I show configuration changes. I do have the Use Fast Resume Mode checkbox unchecked, so that will be the first thing I try, and I'll let you know if that fixes it.

**Comment by rlbf** [comment]
Okay, yes, I've just tested and Fast Resume Mode being off is what was causing the problem for me. I've just switched back and forth between on and off, and a manual re-check consistently works with it on, doesn't work with it off. I think what probably happened is that at some point I went through various settings making changes that seemed like a good idea, and didn't notice the problem until enough time had passed that I didn't associate it with having changed settings. Thanks for your help!

**Comment by parg** [comment]
No problem, I've actually removed that option as it obviously causes more trouble than it is worth - indeed, it is from the very early days of Azureus when I think the client didn't save any persistent download state at all. At that time, if you restarted Azureus everything would restart at 0%. Someone introduced the ability to recover the download state and at that time added an option to allow people to select not to do so because, you know, there's always that user out there that hates change.
