### ISSUE TITLE
BiglyBT auto installs plugins even though unchecked at install

### ISSUE THREAD

**Issue by Seeings** [BiglySoftware/BiglyBT#2329]
I recently did a clean install of Windows and just installed BiglyBT again.
During the install I got to choose what plugins I wanted to install and I only selected one the Mainline DHT plugin.
However when I finished installing and started the BiglyBT client it installed all of the plugins.

Now to the bigger issue; trying to remove most plugins makes them auto install on the next startup of BiglyBT.

Please make it so BiglyBT doesn't try to update plugins that aren't installed, since I believe that is what is causing the issue.

**Comment by parg** [comment]
Some plugins are basically mandatory, if they are missing they will be installed. If you really don't want them then go to Options->Plugins and uncheck the "load at startup" option for them, don't uninstall them.

**Comment by Seeings** [comment]
> Some plugins are basically mandatory, if they are missing they will be installed. If you really don't want them then go to Options->Plugins and uncheck the "load at startup" option for them, don't uninstall them.

Oh I understand some are mandatory, but I'm talking about non-mandatory, please re-read my post.. 

as I said if during install I uncheck some plugins during the installation it shouldn't install those plugins when I launch the client.

**Comment by ferdnyc** [comment]
@Seeings 

> I recently did a clean install of Windows and just installed BiglyBT again.
> During the install I got to choose what plugins I wanted to install and I only selected one the Mainline DHT plugin.

You got to choose whether to install **some** optional components; only a tiny subset of all the plugins. I'm not really sure how you selected only one. On my system, using the `GitHub_BiglyBT_Installer64_WithJava.exe` installer, four can't be deselected (their checkboxes are grayed out:)

![Screenshot from 2021-12-18 16-58-20](https://user-images.githubusercontent.com/538020/146656794-3364f72f-95a2-4276-82d0-469fa973e17e.png)

> However when I finished installing and started the BiglyBT client it installed all of the plugins.

That's very strange; as you can see, after install on my Windows 10 system, only the enabled plugins (four of them) plus all of the non-optional built-in plugins are installed. The optional ones that _weren't_ selected (uTorrent Migration, BiglyBT Remote Plugin, Tor Helper, and I2P Helper) are nowhere to be found:

![Screenshot from 2021-12-18 17-03-04](https://user-images.githubusercontent.com/538020/146656846-c231702f-9602-4b4b-b7f2-89d651cc2137.png)

Are you **sure** that optional add-ons which you had unchecked in the installer were installed anyway? I'm just not seeing that here.

Regardless, _even though_ some non-optional "optional" components were installed, as @parg says I can uncheck the box next to them, and they'll not be loaded at startup. That's also true for nearly all of the built-in, mandatory plugins as well.

(I can also click "Unload selected" next to a plugin, and it will disappear from the list. But a "Scan for new Plugins" will bring it back again, but in an unloaded state (red dot). That's a little weird, and I'm not sure why "unload" removes entries from the list instead of just changing the green dot to a red dot.)

Using "Uninstall Selected" isn't very useful with the built-in set, since running as a regular user you can't remove files from the system install. The plugin will just come back again. But you can still uncheck them, to prevent them being loaded.
