### ISSUE TITLE
Memory allocation failed

### ISSUE THREAD

**Issue by as-muncher** [BiglySoftware/BiglyBT#2347]
Java 1.8.0_202 (64 bit)
  Oracle Corporation
c:\program files\biglybt\jre

SWT v4942r22, win32, zoom=100, dpi=120
Windows 10 v10.0, amd64 (64 bit)
B2.9.0.1_B09/4 az3

Memory allocation failed: Out of direct memory space.  To fix: Use the -XX:MaxDirectMemorySize=512m command line option, or upgrade your Java JRE to version 1.4.2_05 or 1.5 series or newer.

As you can see, my Java is 1.8.0_202, so I'm not sure why BiglyBT is saying I should get a newer Java.  Can't BiglyBT just automatically notice these memory errors and ask if I want to enable this option in the command line from now on?  My max heap memory size is 800 MB and the other two boxes are blank.  My size of cache in MB is 32 MB in Performance Options.

**Comment by ferdnyc** [comment]
@as-muncher That message predates the "Java Options" section of Options > Startup & Shutdown. At the time, there was no way to configure memory allocations other than by hand-editing the startup script. [The Vuze wiki entry](https://wiki.vuze.com/w/Java_VM_memory_usage) on memory allocations explains why versions older than 1.4.2_05 / 1.5 had allocation issues (on Macs), but that's all out-of-date and irrelevant at this point.

Today there are better ways to correct memory allocations, using the Options interface. One thing you can do, when you get a message like that, is head to Options > Startup & Shutdown > Java Options and click the "JVM memory usage history" View button, which will show a log of the past few minutes of memory consumption at 10-second intervals.

You'll most likely see that Heap memory is exhausted, so goosing the Max Heap memory size by another 100MB or so would be the best option. Or you could just do that preemptively and see if it clears things up. 800MB seems like a lot already.

There's another possibility, since you said you DON'T have a minimum Heap value set: It's possible your max value is plenty big enough, but when BiglyBT tried to _increase_ the heap size because it needed more space, the system was out of memory and couldn't allocate any more. If that's the case, setting a **minimum** Heap value of like 400MB - 500MB, so that space gets preallocated on startup, might make things run more smoothly.

Personally I run with 550MB minimum / 640MB maximum, but that's on a fileserver with 6GB of dedicated RAM it isn't using for anything else, so there's no harm in setting aside a lot of it up front. YMMV.

**Comment by as-muncher** [comment]
@ferdnyc   I appreciate the feedback.  I will try setting a minimum to 500 MB or so.  Since that message predates the java options setting, perhaps now that message can be changed by the programmers, so that it will look at the system's Java Runtime Environment and if it's higher than 1.42_05 or 1.5, to omit that part of the message.  I appreciate your message.  And thanks to @parg and others for BiglyBT.

**Comment by as-muncher** [comment]
@ferdnyc Also, I had to look up YMMV means.  "Your mileage may vary", right?
