### ISSUE TITLE
Add BiglyBT entry on wikipedia article for "Comparison of BitTorrent clients"

### ISSUE THREAD

**Issue by as-muncher** [BiglySoftware/BiglyBT#2350]
Java 1.8.0_202 (64 bit)
  Oracle Corporation
c:\program files\biglybt\jre

SWT v4942r22, win32, zoom=100, dpi=120
Windows 10 v10.0, amd64 (64 bit)
B2.9.0.1_B09/4 az3

https://en.wikipedia.org/wiki/Comparison_of_BitTorrent_clients

**Comment by parg** [comment]
You try it, the moderators won't let you.

**Comment by as-muncher** [comment]
@parg Could you please give me the correct information to fill in?  It's working for me.

**Comment by parg** [comment]
Didn't last long though did it?

**Comment by as-muncher** [comment]
@parg, Yeah, that's weird, eh?  I put in some time filling out the tables and here they delete it.  Those extra bytes cost them too much?  Weird.

**Comment by parg** [comment]
Haters love to hate

**Comment by ferdnyc** [comment]
The revert gives a very simple explanation: ["Rm entry without wikipedia article"](https://en.wikipedia.org/w/index.php?title=Comparison_of_BitTorrent_clients&action=history).

An article would no doubt be accepted, if it were properly based on [reliable sources](https://en.wikipedia.org/wiki/Wikipedia:Reliable_sources) and sufficiently established [notability](https://en.wikipedia.org/wiki/Wikipedia:Notability) (BiglyBT should meet the [general notability guideline](https://en.wikipedia.org/wiki/Wikipedia:Notability#General_notability_guideline), but it's a matter of an interested third party creating said article. As a project contributor, I'm ineligible, as it would be a [conflict of interest](https://en.wikipedia.org/wiki/Wikipedia:Conflict_of_interest) for me to write about a project I'm involved in.

But you could certainly try adding BiglyBT to the [Requested articles list for software](https://en.wikipedia.org/wiki/Wikipedia:Requested_articles/Applied_arts_and_sciences/Computer_science,_computing,_and_Internet#A%E2%80%93B), @as-muncher, to see if anyone takes it up. If you do, though, and you don't want the request to just sit there with all the others  that will never get written, there are some things to keep in mind:
* Wikipedia doesn't care about primary sources, meaning things like the project repo and wiki are meaningless for establishing notability and providing reference material. The criterion is "significant third-party coverage in reliable sources", meaning things written ABOUT the project rather than BY the project. Providing _multiple_ (meaning 2-4, not 20) links to any coverage by TorrentFreak and etc. would be of the highest value.
* Emphasize the project's open-source nature; the request isn't a company looking for free advertising
* Definitely note that BiglyBT is a fork of Vuze, which Wikipedia DOES have an article about. (In fact, given that Vuze is now dead, there's some small chance a BiglyBT section would be added to the Vuze article, instead of creating a separate one. There's currently no mention of BiglyBT in the Vuze article, which is surprising. Having a BiglyBT section in the Vuze article would also be sufficient to add it to the Comparison article, so either way...)

**Comment by ferdnyc** [comment]
Oh, yes, duh: Also important to mention, the fact that BiglyBT's primary developers are the **original creators of Azureus**. Meaning that while it's technically a fork of Vuze, it actually has more right to claim that it's the current successor of Azureus than any other client — _including_ Vuze.

**Comment by as-muncher** [comment]
@ferdnyc  I can't even talk with the editors for deleting all my BiglyBT work because now my IP address is banned.  Perhaps someone else can take this up.  I think wickedpedia I mean wikipedia had a good idea to start with, but it's turned out that they are liable for all the information posted on their site, and maybe don't want to be sued for it.  It's ridiculous that they would want a wikipedia article on BiglyBT before even adding it to the table, and that they'd want multiple 3rd party sources instead of wikipedia being an authoritative source of its own.  If I was a software developer, I would be tempted to have some third party write an article about my software, or maybe a few article-writers, so that then I could finally get a wikipedia article written.  Maybe that's why I see some years-old articles written about various softwares whose softwares aren't even that great.  Instead of actually checking out the link that I provided to BiglyBT's github page, the editor just decided to remove my work just because one of their rules.  Oh well.  At least now I know maybe a little bit of why Wikipedia's always looking for cash.  I'm sure there are other sites like Wikipedia that will take an article.
