### ISSUE TITLE
Client ignores SIG_TERM signal at shutdown

### ISSUE THREAD

**Issue by Sagmegar** [BiglySoftware/BiglyBT#2360]
Manual quit necessary.

Java 1.8.0_202 (64 bit)
  Oracle Corporation
/Applications/BiglyBT/.install4j/jre.bundle/Contents/Home/jre

SWT v4942r22, cocoa, zoom=100, dpi=72
Mac OS X v10.13.6, x86_64 (64 bit)
B2.9.0.0/4 az2

**Comment by ferdnyc** [comment]
@Sagmegar 

What's the state of Options > Interface > Display > Various > "Wait for BiglyBT to close tidily on exit/restart and display progress"?

(Don't ask me why it's located there, instead of in Options > Interface > Start or Options > Startup & Shutdown. Or in Options > Interface right below "Show confirmation dialog on exit", for that matter.)

With a lot of active torrents, BiglyBT can take a fair amount of time to completely shut down, since (AIUI) it actively notifies each tracker that it's signing off. My install often takes 20-30 seconds to completely exit.

**Comment by Sagmegar** [comment]
The checkbox is checked.
