### ISSUE TITLE
Saving alerts.

### ISSUE THREAD

**Issue by GuillermoMartini** [BiglySoftware/BiglyBT#2391]
Every time I load Biglybt I have to resave the "play a sound when download finished" alert.  I know it's not a huge deal but it kinda makes the save button useless doesn't it?

**Comment by parg** [comment]
Is this the only setting that doesn't persist or is it all of them?

**Comment by ferdnyc** [comment]
@GuillermoMartini And are you running the beta, or the release version? If it's the beta, did this only start this month, or has it been happening for a while?

(@parg I'm wondering if this is my fault, for browbeating you into replacing the deprecated plugin audio APIs. Or OTOH, if this is about the release version then maybe I'm awesome because the issue could already be fixed in the beta! :grin: )

**Comment by GuillermoMartini** [comment]
Frank,

I'm using version 2.9.0.0.  This has been an issue since I upgraded from
Vuze.

**Comment by GuillermoMartini** [comment]
It's the only setting that I've noticed.  The only other things I've
changed are target locations and the number of files in the queue.  They
maintain their changes.

**Comment by parg** [comment]
Options->Interface->Alerts: Play a sound when a download is finished

saves just fine for me across restarts, with the default sound and with an explicit one.

What do you get if you go to the Help menu and select Advanced->Show Configuration Changes...  ?

The relevant settings are:

    Play Download Finished=1
    Play Download Finished File=<default>

**Comment by parg** [comment]
Hmm, actually there is some weird OSX specific code that appears to reset it...

**Comment by parg** [comment]
Try 2901_B21 (join the beta programme using the Help menu option) - hopefully fixed

**Comment by GuillermoMartini** [comment]
Thanks, I'll check it out.

**Comment by GuillermoMartini** [comment]
Downloaded the newer version.  Seems fixed so far.  Thank you!

**Comment by parg** [comment]
weird one that!
