### ISSUE TITLE
Remote Access from Windows laptop to Samsing Galxy S7

### ISSUE THREAD

**Issue by bumpengrinder** [BiglySoftware/BiglyBT#2402]
Hi

I have just put BiglyBT on my Samsung S7 Android 8.0.0.  I have enabled Remote Access in BiglyBT, but cannot connect to it from my Windows laptop in the same wi-fi lan.  I connect to other devices' web guis on the LAN fine.  I cannot even ping the S7 from the laptop (although the S7 can see other devices onn the network).  

Any pointers would be most welcome please.

**Comment by ferdnyc** [comment]
@bumpengrinder 

If you can't ping the phone, that sounds like a more general network problem. But I wouldn't be surprised if it prevents BiglyBT's remote access from connecting.

I have a Note8 running Android 9, so pretty close in both hardware and OS generation. Attempts to configure pairing (regular or secure) were a bust because any attempt to generate an access code fail with this message:
> java.security.cert.CertPathValidatorException: Trust anchor for certification path not found

But after enabling Remote Access, setting a username and password, and enabling the "Keep CPU awake" and "Only transfer... when plugged in" options under Power Management, I was able to open the BiglyBT Web Remote interface from the sidebar of my desktop's running BiglyBT, enter the IP:Port combo shown on my phone, and log in to link the two clients without any trouble. Clicking "Launch UI" there brings up a https://127.0.0.1/ URL in my desktop browser showing a proxy web UI where I can manage my phone's BiglyBT instance.

If you're not able to do the same, I'd guess that it's most likely due to whatever issue is either blocking your pings from reaching the phone, or preventing its replies from getting back to you.

**Comment by bumpengrinder** [comment]
@ferdnyc

I am not in a postion to run BiglyBT on desktop, so I cannot try this solution.  Many thanks anyway.

**Comment by ferdnyc** [comment]
Ohhhhh, so you were looking to access the phone's BiglyBT instance... with a web browser, I'm guessing?

Someone will hopefully correct me if I'm wrong, but I don't **think** that's possible currently. The remote-access service on the phone uses Transmission's remote protocol, it needs a Transmission-compatible client (which desktop BiglyBT is) to serve as the frontend.

To have browser-based access directly to the phone (instead of proxied by a desktop BiglyBT instance), the phone app would have to have the BiglyBT Web Remote plugin (or similar) installed locally. That plugin includes the web server component, but AFAIK it's not available for the Android app.

**Comment by bumpengrinder** [comment]
@ferdnyc 

Web interface works after rooting my S7. Custom ROM not required, just root.  Ttorrent web interface also now working.  I can now ping the phone, which I couldn't before.
