### ISSUE TITLE
Very High RAM Usage 

### ISSUE THREAD

**Issue by absolutep** [BiglySoftware/BiglyBT#2437]
As can be seen from the screenshot.

BiglyBT is using too much RAM.

In addtion to high RAM usage, BiglyBT is slowing my coumputer down when I open other applications like Chrome or video games etc.. Computer **hangs for a minute** & then starts working again.
![RAM Usage](https://user-images.githubusercontent.com/97702149/151411727-b64a9b1d-7920-4c7e-ab45-96255ff18575.png)

Anyway to lower RAM usage & atleast not let it hang my computer?

Bigly has around 20 torrents with Mix Privacy level
qBittorent has around 35 torrents.

* BiglyBT 
Java 1.8.0_202 (64 bit)
  Oracle Corporation
c:\program files\biglybt\jre

SWT v4942r22, win32, zoom=100, dpi=120
Windows 10 v10.0, amd64 (64 bit)
B2.9.0.0/4 az3

**Comment by parg** [comment]
https://github.com/BiglySoftware/BiglyBT/wiki/Performance-Tweaks

**Comment by parg** [comment]
Oh, and if you're running the "I2P Helper Plugin" then you will see higher CPU/Memory as you are running an entire crypto framework in-process. Unless you have installed a separate I2P router and configured BiglyBT to use that.

**Comment by absolutep** [comment]
> https://github.com/BiglySoftware/BiglyBT/wiki/Performance-Tweaks

**Everything is in default state, heap memory is set to 128MB.** I did not tweak any QUEUE settings, they are all default.
**Removed I2P support for every torrent, yet RAM usage is high.**
![Untitled](https://user-images.githubusercontent.com/97702149/151494380-b083d9ff-cf55-4a77-9229-a36b8e776a2a.png)

Restarted Bigly twice & shut it down and started once again. Still usage is high.

Is there any other way to reduce RAM usage?

**Comment by parg** [comment]
Have you uninstalled the "I2P Helper" plugin?

**Comment by ferdnyc** [comment]
Also, "Java is not light". I mean, at least it's smaller than Chrome... :wink: (Though TBH I have never seen a Chrome instance running that small, mine gets over 400MB just launching the "New Tab" page.)

How RAM-starved is your system typically, @absolutep? I mean, hanging the rest of the system for "a minute" is not something I'd expect from having to allocate less than half a gig of memory. That sounds like either CPU load (a lot does happen at startup) — though even then it'd have to be an older CPU, and/or one with relatively few cores — or maybe it's the network traffic causing resource contention.

What do the graphs in the "Performance" tab of the Task Manager show once BiglyBT finishes starting up, if you open them up before you launch it? (If you go to View > Update speed and set it to "Low", you'll get 4 minutes of history instead of only 60 seconds.)

**Comment by absolutep** [comment]
> Have you uninstalled the "I2P Helper" plugin?

NO. Just unchecked it.

**Comment by absolutep** [comment]
> Also, "Java is not light". Hey, at least it's smaller than Chrome... 😉 (Though TBH I have never seen a Chrome instance running that small, mine gets over 400MB just launching the "New Tab" page.)
> 
> How RAM-starved is your system typically, @absolutep? I mean, hanging the rest of the system for "a minute" is not something I'd expect from having to allocate less than half a gig of memory. That sounds like either CPU load (a lot does happen at startup) — though even then it'd have to be an older CPU, and/or one with relatively few cores — or maybe it's the network traffic causing resource contention.
> 
> What do the graphs in the "Performance" tab of the Task Manager show once BiglyBT finishes starting up, if you open them up before you launch it? (If you go to View > Update speed and set it to "Low", you'll get 4 minutes of history instead of only 60 seconds.)

Currently, here's the state as in attached screenshots will tel
![Untitled 2](https://user-images.githubusercontent.com/97702149/151690633-652fd57b-3ec2-4359-9485-d09e438ce76a.png)
![Untitled 1](https://user-images.githubusercontent.com/97702149/151690634-33c2db9f-643d-4015-bb2e-3078f5062c42.png)
![Untitled](https://user-images.githubusercontent.com/97702149/151690635-e27af205-c850-417c-a1d2-657e59f579e5.png)
l you

**Comment by parg** [comment]
1) Ensure you have the I2P plugin UNINSTALLED (Tools->Plugins->Uninstallation Wizard...  and restart BiglyBT

2) As initially suggested go to https://github.com/BiglySoftware/BiglyBT/wiki/Performance-Tweaks and look at the bit that talks about 'JVM memory usage history' - copy/paste some values from that log here

**Comment by ferdnyc** [comment]
@absolutep Hm, OK, yeah, that's about what I'd expect to see regarding CPU and memory — TBH you've got memory to spare, and then some, only about half of your 8GB is even in use. The other half is being used as cache. Not that you don't NEED the cache, because something apparently **hates** your hard drive(s) and is trying to murder it/them!

That may be a bit of an exaggeration, but _sustained_ filesystem loads of **80%-95%** are not something I'm used to seeing under remotely normal circumstances, even with a traditional spinning-rust (non-SSD) drive.

By all means, follow Parg's advice (he wrote the bloody thing, you'd be a fool not to!) and look into options for reducing BiglyBT's memory footprint... ... ... buuuuut, I'd personally be shocked if it made any appreciable difference because there's very little indication (to my eye) that the _CURRENT_ RAM consumption is in any way a problem for your system. The stats on memory all look positively idyllic.

That filesystem load is concerning, though — unless it was a one-time fluke, like when those screenshots were taken you happened to be copying a folder full of multi-gigabyte MP4 files from one partition to another, or whatever.

But if that's a normal occurrence, personally I'd want to find out what's causing it and address _that_ issue. (It could still be BiglyBT, say performing post-startup rechecks and other torrent data operations, which can cause a great deal of disk activity particularly at startup, but there are techniques for mitigating that as well.)

I'd recommend also looking over **Options > Files**, **Options > Files > Performance Options**, and the **Options > Queue** settings that affect the number of concurrent torrents that can be down/uploading at the same time.

Some items of particular interest, affecting disk load:
* In **Options > Files > Performance Options**
    - "Enable disk cache" (You for sure want that)
    - "Size of cache in MB" (As it says, no more than 32MB, but you probably want the full 32MB)
    - "Perform read-aheads..." and "Cache download data..." you likely want
    - All three "Maximum..." options can help to limit both memory growth and disk contention
* In **Options > Queue**, setting maxes on simultaneous downloads & active torrents can be a big help. I keep mine at 4 and 6, respectively, because I find that if I have any more than that going, they just end up starving each other and they _all_ take longer than they should. (I do have the "Don't count..." values set to 50 kB/s and 15 kB/s, though, to make sure that basically-inactive torrents don't prevent well-seeded ones from starting.)

Some of the things I've mentioned may conceivably _increase_ BiglyBT's RAM usage somewhat, but in all honesty my read of your performance screenshots says that'd be a good trade. Burning up a little more RAM to take some of the load off your hard drive would be about the **best** correction you could make.

**Comment by absolutep** [comment]
Matter is not resolved but still closing it.

BiglyBT still uses very high RAM (around 300-400-700 MB, depending upon number of torrents) but when my disk usage is not 100% my computer does not lag.

So, I figured out that, my computer performs normally even with high RAM usage as long as my disk usage is in check.

**Comment by jeffward01** [comment]
I have 96GB of RAM, and I can buy more if I need it, if I want to really 'push the limits' and make BiglyBT perform like a rocket engine (I don't care how much RAM it uses, as long as it does not crash my computer), what memory settings do you guys suggest I set.

Sorry I am unfamilar with JVM (I am a `C#` dev, Java's sister). I am unsure of which settings will have an impact: 

https://github.com/BiglySoftware/BiglyBT/wiki/Performance-Tweaks

This is my current settings:

![image](https://user-images.githubusercontent.com/12589359/182006865-694e5053-6604-483f-8f8a-53241d435fa7.png)

and my PC specs:

I have overclocked to 5.00 GHZ (It does not reflect in system settings)

![image](https://user-images.githubusercontent.com/12589359/182006885-6980f72a-f85c-4997-933b-17a086c225ec.png)

Another view:

![image](https://user-images.githubusercontent.com/12589359/182006909-d4fda468-65fe-4c7f-91dc-1e03803c5183.png)

--

Thanks all!! Sorry if this is noobish, I just usually 'guess' and shoot in the dark, but would be cool to know exactly what I am doing! If anyone has suggestions for tweaks that would be great!

Currently I have about `1000+` torrents in queue to be downloaded by BiglyBT. I can easily add another 3000 to stress test this

**Comment by parg** [comment]
Generally speaking the amount of Java heap memory required is related to the number of active downloads you have. By active I mean either in a seeding state or a downloading state, but not including queued and stopped.

You can monitor the amount of memory being used via "Options->Startup & Shutdown: JVM memory usage history", the wiki gives some hints on how to interpret that. If you run a beta version of BiglyBT there is a Debug menu with "Run GC" option - hitting this forces the JVM to do an aggressive garbage collect and can give insights into the actual amount of memory being used (the JVM tends to bimble along being a bit lazy otherwise and can show higher memory requirements than necessary)

There's not point in giving the JVM huge amounts of RAM to play with if it doesn't need it.

As for the built-in cache size (Options->Files->Performance Options: Size of cache in  MB) - I would hesitate in making that very large as the OS cache does a good job and this additional layer, while useful at the piece-downloading level, doesn't help that much in the larger scheme of things.

I would increase the number of files open for read/write (Options->Files->Performance Options: Maximum files opened for read/write [0: unlimited]) to, say, 1024, if you are running lots of active downloads (as opposed to seeding completed ones) as a small limit can result in files being frequently opened and closed which messes with caching.
