### ISSUE TITLE
update window and plugin download not showing

### ISSUE THREAD

**Issue by as-muncher** [BiglySoftware/BiglyBT#2478]
Java 1.8.0_202 (64 bit)
  Oracle Corporation
c:\program files\biglybt\jre

SWT v4942r22, win32, zoom=100, dpi=120
Windows 10 v10.0, amd64 (64 bit)
B3.0.0.1_B02/4 az3

I have the plugin installer window showing, trying to download azfocus 0.4_CVS.  At the same time, I have opened Microsoft Edge on the biglybt plugins page, trying to download the share ratio maximizer plugin, but I'm not getting any popup window stating that it's already downloaded/installed, or what the deal is.  I don't see it in the transfer list.   At the same time, when I choose to check for updates, no window shows up saying whether BiglyBT is up to date or not.

**Comment by parg** [comment]
Weird, all I can suggest is restart BiglyBT and see if it happens again.

**Comment by ferdnyc** [comment]
So, this may or may not be related — but if not, it's an awfully big coincidence.

I just today happened to notice that it's been _weeks_ since BiglyBT offered me a beta update — in fact, I was still stuck on `3.0.0.1_b03`, so it was quite the surprise to discover that the current beta version was `_b18`! The last time I'd successfully updated was... hey, look, March 5.

**Fortunately**, a while back I'd disabled the Tor and I2P plugins entirely, so when I attempted a "Check For Updates..." I **_DID_** get a message box — specifically, one complaining that it couldn't download update lists because the Tor plugin was unavailable. That was the indirect clue that led me to track down the real problem: The "Update anonymously" option in Options > Interface > Start was checked, causing the regular update process to fail!

There's no reason I can think of why I would've enabled that option myself — I don't use Tor and I2P (in fact I removed them entirely), and the option text pretty clearly states that anonymous updates require them. I'm not saying it's _impossible_ that I stupidly enabled it myself... but it seems unlikely.

Is it possible that something in `_b03` mistakenly enabled that setting during update?

Soon as I disabled anonymous updates, the `_b18` beta update _and_ like 3 different plugin updates popped right up.

**Comment by parg** [comment]
Yah, anonymous updates is flakey as heck...

**Comment by parg** [comment]
but I don't know how it can automatically get enabled

**Comment by ferdnyc** [comment]
`¯\_(ツ)_/¯` I am _more_ than willing to entertain the possibility that I'm just an idiot who turned it on and broke his own updates.

**Comment by ferdnyc** [comment]
(I mean, it was _two months_ ago. I don't remember what I had for breakfast yesterday. **#WhoKnows**?)
