### ISSUE TITLE
No Pause button and No Download bar in interface?

### ISSUE THREAD

**Issue by MediaMaquina** [BiglySoftware/BiglyBT#2499]
Hello, I'm new to this client and it seems good!
But there's 2 things that I don't understand:

1. There's no pause button, only stop. There's only in a context menu which is not ideal.
![pause](https://user-images.githubusercontent.com/8179611/159688755-8a1882cb-5406-40c0-88b9-0078175b05df.png)
2. There's no Download bar, graphical representation is very important to me. There is but only in the floating bar.
![bar](https://user-images.githubusercontent.com/8179611/159688980-8f83c066-a9fb-4f91-9a6a-ba32140f2099.png)

Can someone help me enable these or  be considered in a future update? I think it would make the client better.
Thanks!

Java 1.8.0_202 (64 bit)
  Oracle Corporation
c:\program files\biglybt\jre

SWT v4942r22, win32, zoom=100, dpi=110
Windows 10 v10.0, amd64 (64 bit)
B3.0.0.0/4 az3

**Comment by parg** [comment]
The only real difference between "pause" and "stop" is visual - internally a paused torrent is the same as a stopped torrent except that it is tagged as "paused" in the UI. Just wanted to check that you didn't think there was more going on.

There is a hidden feature though, if you press and hold the stop button for a second then it will pause it rather than stop it...

There is a progress bar column - right-click on an table column header and select "column setup". Search for "progress" - you can then enable that column.

**Comment by MediaMaquina** [comment]
Awesome thanks 👍
