### ISSUE TITLE
Antivir complaining about BiglyBT_FW.exe

### ISSUE THREAD

**Issue by akidburn** [BiglySoftware/BiglyBT#25]
Hi,

Avira Antivir (Cloud) is complaining about that small installer in the main directory.
What is that nsisFirewall.dll File for anyway?

greetz
akidburn

PS: if you are taking plugin requests, the one i am missing most is autostop.

**Comment by TuxPaper** [comment]
Ah, probably the BiglyBT_FW.exe?  Avira is probably right with this one! (depending on how serious it rated the threat)  

It's a small binary (with nsisFirewall.dll in it) that adds BiglyBT.exe to your firewall exception list, so that the app can communicate with the internet.  It's not required (most firewalls will prompt you when an app tries to use the internet), so you can delete the file if you wish

**Comment by akidburn** [comment]
thx
