### ISSUE TITLE
Setting "Double Click" to "Launch" doesn't launch media files.

### ISSUE THREAD

**Issue by MasterZoen** [BiglySoftware/BiglyBT#2517]
When double clicking a torrent that contains a single media file after setting the "Interface:Tables" -> "Library" -> "Double Click in torrent view" setting to "Launch", the containing folder is opened instead of launching the file listed in the torrent.

Win10 Pro 64-bit 21H2
BiglyBT 2.9 and 3.0

**Comment by ferdnyc** [comment]
@MasterZoen I'm not seeing that, on Linux. If I have a torrent that's _TRULY_ only a single file -- meaning, there's no triangle next to it, to open it up and display the file contents -- then, double-clicking on that item launches the file in the default application, when double-click mode is set to "Launch". 

But, torrents like that are extremely rare, at least in my experience. The automatic torrents used to download BiglyBT updates, or new plugins, are examples of that kind of torrent. And, indeed, clicking on one of those launches my archive manager to display the contents of the `.zip` file, or the `,jar` (which are just renamed zips). Almost **all** other torrents will have a containing folder, even if it only contains a single file. To the point where I had to search hard to find a media torrent that _wasn't_ contained in a folder. (But I did, and clicking on it brought up VLC to play the video.)

For torrents that _have_ a containing folder, though (which is nearly all of them), it appears BiglyBT will always launch the file browser to display it, rather than launching the media player. Which, I agree, is kind of unfortunate.

I took a bit of a look at the code involved. As far as I can _tell_ (though I could be wrong), that's by design. When you double-click to Launch a _torrent_, you're launching "the torrent" (a disk save location), not the file(s) inside that torrent. Opening the twisty-triangle to reveal the torrent's contents and double-clicking on an actual _file_ would, OTOH, open that file in its default application.

But while that's the _current_ situation, it **doesn't** necessarily have to stay that way. 

As I said, I looked at the code behind the launch functionality, as well as the code behind the **_Play Content_** functionality that uses the embedded media player. Unlike the Launch option, setting double-click to Play Content **WILL** launch a media file from inside a torrent, when double-clicking on the torrent entry itself. The code (in [core/src/com/biglybt/util/PlayUtils.java](https://github.com/BiglySoftware/BiglyBT/blob/master/core/src/com/biglybt/util/PlayUtils.java)) scans the contents of the torrent, finds the largest file inside it that has a media-file extension, and plays that in the embedded media player.

So, there's certainly room for another mode, let's call it "Launch Content", that does the same thing using an _external_ player instead of the embedded one. Most of the code is already there, even. Personally, I think that would be a great addition to the set of Double Click / Enter actions for the table views.

cc: @parg @TuxPaper

**Comment by parg** [comment]
Added

**Comment by ferdnyc** [comment]
Neato! Works as expected, noice! Double-click a torrent, VLC fires right up with the enclosed video. 

So, that'll be in 3.0.0.2, @MasterZoen  — you just select "Launch Content" instead of "Launch", for the double-click setting. The same option is also available separately under "Enter/Return", if you don't use "Same As Double Click".

![Screenshot from 2022-05-04 15-45-16](https://user-images.githubusercontent.com/538020/166814233-3fc2c1f7-217c-4201-8c70-b35d51f0e0ae.png)
