### ISSUE TITLE
Causes Kernel Panic on MacOS 12.4 Beta (21F5048e)

### ISSUE THREAD

**Issue by mboland** [BiglySoftware/BiglyBT#2521]
* OS and version. MacOS 12.4 Beta (21F5048e)

* BiglyBT Version Number.  Latest version and installed from web site

On loading the app, interface loads, files load, then the Mac hangs, everything frozen
After a couple of minutes I get a restart or a kernel panic
Happens with the latest version of VUZE as well.

**Comment by parg** [comment]
Report it to Apple! A user-space application should never cause kernel panics.

**Comment by rottegift** [comment]
@mboland There is a new beta of macOS Monterey 12.4 available, please try that.  If anything goes wrong, please launch Feedback Assistant and do a File > New Feedback within the app.  You can find Feedback Assistant in the /Applications/Utilities folder on your beta-enrolled mac.

**Comment by mboland** [comment]
The kernel Panic started AFTER I updated to the version you mentioned



So whatever you did in 12.4 is what is causing the kernel Panic.
All I have to do is kick up BiglyBT or VUZE and I get a kernel panic immediately.

So you definitely broken something in this release.


Michael J Boland
***@***.***

If you want to soar like an eagle
Dont hang out with turkeys

On 20 Apr 2022, at 6:03 am, Sean Doran ***@***.***> wrote:


@mboland <https://github.com/mboland> There is a new beta of macOS Monterey 12.4 available, please try that. If anything goes wrong, please launch Feedback Assistant and do a File > New Feedback within the app. You can find Feedback Assistant in the /Applications/Utilities folder on your beta-enrolled mac.

**Comment by rottegift** [comment]
@mboland - by "new" I meant that macOS 12.4 beta 2 (215058e) published yesterday postdates the version in your biglybt bug report.

If you are getting a panic in a beta caused by launching *any* application, please please please do the whole future user base of macOS 12.4 a favour and use the Feedback Assistant to report it to Apple.    As parg wrote above, (non-superuser) user-space applications should never cause kernel panics, and if one does, the kernel almost certainly has a bug that needs fixing.

I cannot cause a panic just by launching and doing light use of BiglyBT 3.0.0.1_B16 (with the latest "brew install --cask corretto" ) in macOS 12.4 beta 2 (21F5058e).   It may be something that requires heavier use, or something that my test environment and your beta machine do not have in common.

We all want this fixed, but you're the only person reporting it, and only here.
