### ISSUE TITLE
What is the url of the "beta program" changelog?

### ISSUE THREAD

**Issue by david-bakin** [BiglySoftware/BiglyBT#2576]
This has been bugging me for awhile.  I can't see anywhere the url of the beta program changelog window so I can look at it in a browser.  (For some reason clicking on what are obvious links to changelog items, in the beta program view, doesn't do anything: i.e., no browser window opens on that change.)  

Please put the url somewhere!  On biglybt.com, in the README.md, on that beta changelog page itself!  Or even more than one such place!

**Comment by ferdnyc** [comment]
> https://www.tumblr.com/blog/biglybt

AKA [biglybt.tumblr. com](https://biglybt.tumblr.com/) — says so in the right column of the beta page! :grin:

**Comment by ferdnyc** [comment]
@parg
> I'll stick it in a few places!

Honestly? That's cool, and certainly no objections... but in _general_, like in bigger-picture terms... it would be nice if web content _**in**_ BiglyBT was overall more (and more consistently)... inspectable, I guess?

I'm talking about things like:
1. Right-clicking on web links (in Options, in the embedded browser view(s), anywhere a link appears) to copy the URL to the clipboard. 
2. A context menu option (and/or middle-click, <kbd>Ctrl</kbd>-click bindings) to explicitly launch ANY link in the configured external browser, regardless how the settings say links should be opened normally or what the default disposition for the link might otherwise be.
3. Mousing over web links to either _see_ the URL (in a tooltip, or some sort of transient text container), or "call up" the URL in a dialog or etc.
4. The ability to either navigate **in** — _or_ **out of** — the embedded browser. As @david-bakin said, at least in the Beta Program view, it seems to just be... inert.

    On my (Linux) system, the "Test the external browser" button in Options has no trouble bringing up https://www.biglybt.com/ in my default (Firefox) browser. But clicking links on the beta page _neither_ launches them in Firefox, _nor_ loads them in place.

    It's kind of odd. Especially since I see a `WebKitWebPr...` (I assume `...ocess`?) jump to the top of my process list for a couple of seconds, then slink away again without anything ever happening.

I can't speak for anyone else, but personally I don't need BiglyBT to be a full-featured web browser. There are plenty of those already. I'd be perfectly  happy if all of the links on the beta changelog page — or any other embedded web content — were just replaced with a single "Open this page in external browser" button / menu item.

**Comment by parg** [comment]
Yup, should be removed.

In the meantime many (?) links will show the URL on hover and have a right-click menu to copy to clip.

**Comment by parg** [comment]
Oh, the browser is "inert" because it comes mainly from the Vuze era when non-Vuze content could appear within Vuze (e.g. adverts) and sometimes they misbehaved so a URL white-listing scheme was used to control whether links would be followed or not. Given the lack of browser controls this is generally a good thing anyway...

**Comment by ferdnyc** [comment]
> non-Vuze content could appear within Vuze (e.g. adverts) and sometimes they misbehaved so a URL white-listing scheme was used to control whether links would be followed or not.

\*snrk* Because there's absolutely nothing that can't be made terrible  web advertising.
