### ISSUE TITLE
The new Right Bar

### ISSUE THREAD

**Issue by ferdnyc** [BiglySoftware/BiglyBT#2594]
So, as of 3001_B37 there's now a Right [side]Bar, toggleable with <kbd>F9</kbd> the same way the [Left]Side Bar is with <kbd>F7</kbd>.

Cool. Can't find anything it can be _used_ for, yet... but that's what we call "potential", kiddies!

I did notice **one** thing, though. Remember #1612, the whole thing about the Settings pane in Tags Overview lays itself out so that it only fits in the window at **full** width, meaning the [Left]Side Bar has to be _closed_ for Settings to fit in the window?

Well, the Right Bar makes that situation **way** worse, because now they _both_ cover part of the Settings view, which still lays itself out across every pixel of the _full_ window width.

#1612 is closed. (I think by me, because the Settings view was tweaked to make it horizontally scrollable which at least meant it was "better", and deemed tolerable for the time being.) But this `A WILD [RIGHT BAR] APPEARS` situation makes me think it's probably worth reopening/revisiting. With sidebars now encroaching on it from **both** sides, the Tag Overview > Settings pane's utter refusal to confine itself to the visible window area allotted for it is proving increasingly troublesome.

#### System block
```
Java 11.0.15 (64 bit)
  Red Hat, Inc.
/usr/lib/jvm/java-11-openjdk-11.0.15.0.10-1.fc36.x86_64

SWT v4942r22, gtk/3.24.34, zoom=100, dpi=96
Linux v5.17.12-300.fc36.x86_64, amd64 (64 bit)
B3.0.0.1_B38/4 az3

```

**Comment by parg** [comment]
You can add pretty much any view you want to the right-bar (and dashboard and sidebar) by right-clicking on a sidebar entry or tab folder header and selecting "Add To->Right Bar"

**Comment by ferdnyc** [comment]
@parg

> I must be missing something about the Tag Settings view - seems to behave OK to me with the horizontal scroll bar appearing when needed?

Oh, it _does_, but horizontal scrolling is the devil, and really the point is that the horizontal scrollbar appears even when it **shouldn't** be necessary — the only reason it's "necessary" is that the panel layout sizes itself to a fixed width that matches the **full** window area (rather than just the _available_ space for its contents).

The widest part of this layout **should** be the combo box for "When exceeded" in the Transfer Settings section. But it gets blown out way wider. So wide, in fact, that the Name field is like 100 characters long (because _that's_ useful) and it shoves the Color/Icon items clear past the right edge of the frame (when the sidebar is open). The right-aligned (and excessively distant) checkboxes after each File Settings row end up mostly obscured for the same reason.

![Screenshot from 2022-07-07 23-30-50](https://user-images.githubusercontent.com/538020/177911671-b0dddd1d-c50a-4343-991b-7aadcc4c9ef3.png)

(This was taken with both sidebars hidden, but when they're enabled the layout gets no narrower, despite the fact that it _could_. It just enables devil-scrolling.)

The layout for any of the Torrent Details tabs (as an example) will size themselves to fit the width of the _available_ space, meaning the window width _minus_ the sidebars — as it should be. Those tabs' contents even respond to sidebar open/close events by resizing the layout to fit their new visible/available width.

**Comment by parg** [comment]
Hmm! Well for me (on Windows and a Linux VM) I don't get a horizontal scroll bar when not necessary - it appears are required when resizing or showing/hiding the side/right-bars. I admit that the items that glue themselves to the right are annoyingly distant from their left-aligned friends but they are glued to the right of the available space for the settings tab, not the overall window width.

The reason they are right-aligned is that it gives the file locations (for initial save location, move on complete etc) space to display correctly. If they aren't right-aligned then we have to select some arbitrary fixed width for the file location labels. Otherwise the move data/torrent check boxes end up next to "None Assigned" (in your example) and then when a value is assigned its display gets truncated at the width of the "None Assigned" text. Don't get me started on forcing the label to resize to the necessary width and shove the check box bit to the right.

It might be possible to at least make the "right hand side" the right of the "When exceeded" combo, I'll have a play.
