### ISSUE TITLE
Unable to create access code for pairing on Android

### ISSUE THREAD

**Issue by fooltothink** [BiglySoftware/BiglyBT#2631]
I am trying to set up pairing with BiglyBT running on my Nvidia Shield TV Pro to allow remote access and control from the BiglyBT app running on my Pixel 4a (5G). After enabling pairing under connection settings and clicking Create to allocate a new access code, it fails and I get the following error:

`java.security.cert.CertPathValidatorException: Trust anchor for certification path not found`

This happens whether I am trying to run the client on the Shield TV Pro or my phone.

* OS and version: Android 11 (Shield TV Pro), Android 12 (Pixel)
* BiglyBT Version Number: 1.3.2.0 (build 1030200)

**Comment by NaPurHab** [comment]
Since BiglyBT is currently up to Version 3.1.0.0, the first thing you should do is Update to the latest version. Your version 1.3.2.0 is rather old.

Then if the problem continues, it will be easier to diagnose.  Also on the `Help`/`About`, you should copy the text in the System section. It includes your Java version as well as the other useful data. Here is what mine looks like:

![image](https://user-images.githubusercontent.com/37715552/179421958-3996934d-477c-4f55-ae87-bbba5c595026.png)

Normally, I use the copy Button in the image and paste it here. As you can see, it show what the system is setup like. (Good idea to always include this in your post.) But definitely make sure to Update to the latest release, and see if the problem continues.
