### ISSUE TITLE
'Search for Existing Data Files (SFEDF)' results in 100s of incomplete (0% - 99.9%) torrents & Save path not updated

### ISSUE THREAD

**Issue by MasTech** [BiglySoftware/BiglyBT#2657]
Java 18.0.1.1 (64 bit)
Oracle Corporation
d:\misc\peer\torrents\biglybt\jre

SWT v4942r22, win32, zoom=200, dpi=84
Windows 10 v10.0, amd64 (64 bit)
B3.1.0.0-00/4 az3

Clean install as stated in the.

ISSUE #1:

I stopped and re-checked all 4862 torrents prior to re-install. All completed with 100% verified without issue. Installed BT and set options. Initiated "Search for existing data files". This resulted in 100s of incomplete (0% - 99.9%) torrents after the operation completed a few days later.

BT fully verified the "missing/incomplete" files just days before to 100%. I can verify the the files in uTorrent & qbittorrent without issue.

ISSUE #2: (Library View, default & custom tag views)

SFEDF ONLY updates the column "Save Path" for torrents that track single files. Not one of the 4000+ torrents that includes a subfolder in the path is corrected even when all files are found, linked, and verified.

**Comment by ferdnyc** [comment]
@MasTech 

> after the operation completed a few days later.

What the _what_? 

It sounds like you were using SFEDF to do basically a mass import of torrent data, yes? That's... not really how SFEDF is meant to be used. And in fact, SFEDF isn't necessary when importing data that matches the existing structure of a torrent. If you just point the torrent download location to the _existing_ files, when Opening it in BiglyBT, you'll get this dialog:

![Screenshot from 2022-07-25 03-15-16](https://user-images.githubusercontent.com/538020/180720696-87edda45-cacb-45f0-9e13-3461b2bc4af0.png)

When the torrent is started (or before, if it's loaded in Stopped state and a forced re-check is manually requested), BiglyBT will perform an initial piece check on the existing data files. If they all match the torrent, it will go to 100% and immediately enter Seeding mode when started.

SFEDF is intended primarily as a tool to find torrent content which _isn't_ part of the torrent's download dataset, but already exists on the filesystem for some other reason. (e.g. it was previously downloaded as part of a different torrent, or obtained via other means).

It's also a _search_, literally — it can match existing files even if they're saved under a different filename (it uses filesize to determine potential matches, and piece hash checking to confirm them), and it can match up partial torrent contents if some files are available and some are missing, or if the necessary files are scattered around in different locations on disk. As a result, it's somewhat slow, and it will perform a _lot_ of unnecessary comparisons if you're using it to scan a large store of existing torrent-download data, since in that situation **every** comparison is unnecessary except one. The only file you actually **need** to check is the one with the exact filename and in the exact location that the torrent specifies. BiglyBT will do _that_ automatically, as long as the files are already in place when the torrent is opened.

> SFEDF ONLY updates the column "Save Path" for torrents that track single files.

Well, yes, that's correct. Because it doesn't have any control over the torrent save path. It functions at the level of _individual files_, and (depending on the mode you select) will update the location of _each file_ separately (and potentially to a different location relative to other files in the torrent). Even though every file in the torrent may be redirected to a different location on disk, the torrent's download path remains the same. (Except for single-file torrents, where the file location _**is**_ the torrent save path.)

> This resulted in 100s of incomplete (0% - 99.9%) torrents

What mode did you use? There are several these days (too many, IMHO), and they can have subtle differences with how the file matches are handled.

The primary factor here is what I said earlier about SFEDF working at the _individual file_ level. Torrent data isn't managed at file granularity, it's managed at _piece_ granularity. That results in a situation where, in multi-file torrents, each file will be spread across one or more torrent piece blocks. If the file is larger than a single piece, most likely both the start and end of the file fall somewhere in the middle of a piece block which it shares with the adjoining file.

As a result, when SFEDF is matching and importing individual files, it can't _necessarily_ mark every piece of the file as 100% transferred. If the piece is at the start or the end of the file (what I call "border" pieces), the piece will only be able to pass the hash check and be set to 100% if the adjoining file (the one that shares the border piece) is also available, since it contains the other half of the piece's data bytes.

There's also a very real danger, when running SFEDF scans over multiple torrents, that any files which appear in _multiple_ torrents will get matched to the wrong copy, and that can have potentially disastrous results. BiglyBT will use the first matching instance of a file that it finds, even if that file is a member of a different torrent. And if it then has to _download_ any part of that file, in ANY of the torrents that it's matched to, that's very likely to screw up the **other** torrents also referencing that same file. A single disk file should never appear in more than one active torrent, unless they are all in seed-only mode and none of them will ever write to that file.

But for your particular situation, if I'm understanding it correctly, there's no reason to use SFEDF at all (and plenty of reasons _not_  to) — just point BiglyBT at the existing torrent download location when loading in a torrent file, and the existing files will automatically (and efficiently) get matched up during the initial piece scan.

**Comment by parg** [comment]
Mode = RELOCATE is what you want to use if you are attempting to match an existing download that you know is complete

**Comment by as-muncher** [comment]
@parg, ah, that's interesting.  I think that's the mode I will use from now on.  But perhaps you could create a tooltip popup for each mode that the mouse cursor rests over, with that sort of information, so that people know which mode is most appropriate to choose.

**Comment by MasTech** [comment]
@ferdnyc 
Correct the assumption of the mass import.

> What mode did you use? There are several these days (too many, IMHO), and they can have subtle differences with how the file matches are handled.

Link

> But for your particular situation, if I'm understanding it correctly, there's no reason to use SFEDF at all (and plenty of reasons not to) — just point BiglyBT at the existing torrent download location when loading in a torrent file, and the existing files will automatically (and efficiently) get matched up during the initial piece scan.

The files are stored across a few  4TB & 18TB drives not the default download folder. They files maintain the torrent folder structure. I set the parent folders on each drive then used SFEDF to hash and link those files.

@parg 
Thanks. I'll delete the needed files to clear downloads/arch data, import the torrents again for a clean run using that setting.

**Comment by MasTech** [comment]
Correction / Update

Okay. Files & paths are being matched. It's just not occurring the way assumed it would/should.

SFEDF in Relocate mode isn't/doesn't search multiple sub-directories. It only looks at the top directory to find matches.

```
w:\in
	\07012022\
			\audio.wav
			\image.raw
	\06122022\
			\audio.wav
			\image.raw
			\subfolder2\
					   \document2.pdf
	\audio.wav
	\image.raw

x:\in
	\04252021\
			\audioA.wav
			\imageA.raw
	\11122021\
			\audioB.wav
			\imageB.raw
			\subfolder2\
					   \document2.pdf
	\audio3.wav
	\image3.raw
```

Referencing the above:
I have to select "x:\in\04252021\" to match items in that same path as SFEDF will not search sub-folders deeper than "x:\in\" when it is chosen as the search path.

The parsing is only 1 level deep no matter the path. 

Is this the intended functionality?

**Comment by as-muncher** [comment]
@MasTech I agree that it would be helpful to have a datastore directory, so that one doesn't have to select all the torrents in BiglyBT and then "search for existing data files" which would be immensely time consuming.  With a datastore directory, if BiglyBT would find any useable data files or pieces in there, then it could copy it into the torrents currently in BiglyBT.

**Comment by parg** [comment]
Not sure I understand your example

Is w:\in the old torrent data root folder and x:\in the new one?

If so why have all the folders and file names changed?

**Comment by parg** [comment]
sorry, missed earlier post.

For "relocate" it assumes that you have simply relocated the entire torrent's folder structure from A to B - if you have renamed stuff it doesn't work.

For "link" it matches based on file sizes for files that contain at least one piece, file size/name otherwise.

It was designed for people who have added a new torrent to BiglyBT and want to see if they have any of the existing files downloaded already. Over time it has been extended. It isn't some kind of magic file system organiser that will resolve all-the-things-any-user-might-wish-it-did.

**Comment by MasTech** [comment]
@parg 
@ferdnyc 
@as-muncher 
@ebourg 

Thanks for the feedback guys.

Quick point to take away for anyone else that may need it:

Relocate mode has been the solution to the massive re-importing. Just had to realize that SFEDF (Relocate) will only match data if the direct parent folder is the search point.

I had to add each dated folder (Z:\07272022, Z:\07122022, Y:\03202022, X:\11122021 etc.) to the 'default search' list for SFEDF (Relocate) to correctly recognize and verify data in one go.

SFEDF pointed to Z:\ will only match torrent data (files & folders) saved to the root of the drive while ignoring all other sub-directories. The match is 1 level deep ONLY. Files MUST retain the original folder structure & file names as they are in the torrent.

I messed up by assuming Relocate mode would parse Z:\*.* IT DOES NOT

@parg 
Safe to assume move & copy modes function the same as link mode only it copies or moves matched file to the default download path?

**Comment by parg** [comment]
I guess relocate-mode could be enhanced to check sub-folders of the search root, performance wise though there might be some issues if you had deeply nested folder hierarchies.

copy+move work in the same way as link, if a matching file is found then instead of linking it copies/moves the file. I'm not sure what you mean by "default download path" - it is matching existing download file locations against the files in the search roots regardless of whether the existing downloads are saved to the default save location or not.

**Comment by MasTech** [comment]
@parg 
That would be welcomed.

This is resolved as far as I'm concerned so closing is in order.
