### ISSUE TITLE
Prolonged accessing of external drive

### ISSUE THREAD

**Issue by LuvBiglyBT** [BiglySoftware/BiglyBT#2676]
Java 1.8.0_202 (64 bit)
  Oracle Corporation
c:\program files\biglybt\jre

SWT v4942r22, win32, zoom=100, dpi=96
Windows 10 v10.0, amd64 (64 bit)
B3.1.0.0/4 az3

About 2 months ago, I began noticing constant accessing of my external HDD, which I use to store downloaded torrensts.  This goes on for a half hour or more.  The external HDD is 5TB.  During this time of accessing, it is so total that the HDD is virtually unusable for anything else.  I have tried checking Task manager and a process manager to find out which process is using all my resources with very little success.  The only thing that stops the accessing of th external HDD is for me to close out BiglyBT.  Can anyone help with this issue?  What exactly is BiglyBT doing while accessing my HDD?

Thanks!

**Comment by parg** [comment]
Do you have torrents in a "checking" or "allocating" state? This is the only state that can cause sustained high read/write rates from a drive, otherwise the only access should be for upload/download operations.

If you have "allocating" ones causing issues then consider changing their mode to "sparse" under Options->Files. Note this would only affect newly added torrents, not existing ones.

**Comment by LuvBiglyBT** [comment]
Parg,

Thanks for your response.  

 

Status of all torrents I stopped.  None are checking or allocating.  I assume you were asking about torrent status.  I have changed allocation to sparse. Just as a precaution, and will let you know if I find any change in disk activity.

 

Best regards,

LuvBiglyBT

**Comment by as-muncher** [comment]
> Do you have torrents in a "checking" or "allocating" state? This is the only state that can cause sustained high read/write rates from a drive, otherwise the only access should be for upload/download operations.
> 
> If you have "allocating" ones causing issues then consider changing their mode to "sparse" under Options->Files. Note this would only affect newly added torrents, not existing ones.

I have sparse files checked, and BiglyBT still does allocating, taking a long time to allocate.  Maybe it's because the torrent has more files than the "file links" option allows (was 2048 by default, changed to 4000 before I added the torrent).  and I have it save with .!qB extension.  

Java 17.0.4 (64 bit)
  Oracle Corporation
C:\Program Files\Java\jdk-17.0.4

SWT v4942r22, win32, zoom=100, dpi=120
Windows 11 v10.0, amd64 (64 bit)
B3.1.0.1_B20/4 az3
