### ISSUE TITLE
Download only one file from a torrent with multiple files

### ISSUE THREAD

**Issue by tonecas** [BiglySoftware/BiglyBT#2686]
* OS and version : Ubuntu 20.04.4 LTS; Kernel: 5.4.0-124-generic x86_6
* BiglyBT Version Number : 2.2.0.2
* For *nix: Desktop Environment : Xfce 4.14.2

When downloading a torrent that contains more than one file, the pop-up window that shows up to chose how to store the files will allow to select only one file but BiglyBT will still save 2 files always. It should only download the selected file and create the sub-directory (or not)

**Comment by parg** [comment]
https://github.com/BiglySoftware/BiglyBT/wiki/Torrents-and-Files#why-are-files-being-createdallocated-on-disk-when-they-are-deselected

**Comment by tonecas** [comment]
> https://github.com/BiglySoftware/BiglyBT/wiki/Torrents-and-Files#why-are-files-being-createdallocated-on-disk-when-they-are-deselected

thank you.
but why then give an option to select files if deselecting them makes nothing?

**Comment by parg** [comment]
It doesn't "do nothing", it only downloads the parts of the file that overlap with pieces in files that you do want. So if you deselect a 10GB file in a torrent that has a piece size of 1MB then at worst it will result in just under 2MB being downloaded rather than the 10GB.

I don't like it either but it is the way that Bittorrent was designed.

**Comment by tonecas** [comment]
got it. thank you!
