### ISSUE TITLE
Does BiglyBT ration its disk usage?  slow checking speeds on ssd drive

### ISSUE THREAD

**Issue by as-muncher** [BiglySoftware/BiglyBT#2778]
Java 1.8.0_202 (64 bit)
  Oracle Corporation
c:\program files\biglybt\jre

SWT v4942r22, win32, zoom=100, dpi=120
Windows 10 v10.0, amd64 (64 bit)
B3.2.0.1_B07/4 az3

I recently imaged my old HDD drive and wrote it to a new internal SSD.  I've been running BiglyBT using that new internal SSD, now, and I find the checking speeds are rather slow.  I downloaded a 1.84 GB file, and when BiglyBT went to check it, I see it's taking a long time, only checking at 9 MB/s.  I can't see why that would be the case with a fast internal SSD unless maybe BiglyBT is rationing its disk usage based on disk speeds of the previous device.

**Comment by ferdnyc** [comment]
Well, it does if it's configured to:

![screen](https://user-images.githubusercontent.com/538020/200096035-5b382ff5-5685-43d0-ac7a-df662df41ebc.png)

But beyond that, the checking process isn't simply a matter of reading data from the disk. It's reading data, calculating a hash for that data, and then comparing it to the expected hash value. So it's never going to saturate the disk's read bandwidth completely. And at some point (depending on the processor speed, memory pressure, etc.) it'll become CPU bound rather than disk bound.

Once that happens, faster disk transfer rates won't make it go (appreciably) faster, the disk will end up waiting for the process to request more bytes. (Or, more likely, it will handle other reads from different threads/processes, until the hash checker reads the next piece.)

**Comment by ferdnyc** [comment]
> unless maybe BiglyBT is rationing its disk usage based on disk speeds of the previous device.

No, it definitely does not do that.

**Comment by as-muncher** [comment]
@ferdnyc  Thanks for the response.  I will have to try disabling low-resource checking.
