### ISSUE TITLE
[Basic Request] Syntax for RSS FeedScanner

### ISSUE THREAD

**Issue by JUser69** [BiglySoftware/BiglyBT#2787]
In the help file it states:  " * Your choice of Regular Expression or Substring matches"
Okay, let's forget  the regex and go with the substring way of searching for matches.  While right clicking on the torrent and selecting add filter does work, how do you modify that to narrow it down.  For example:
name1.name2.S07E02.1080p.WEB-DL.AAC2.0
just selects every mention of name1.name2 (the season and episode seem to work okay)
Can I modify the search string to also look for "720p and web", if so, how?  The typical * and | do not seem to work.

If you have to use the exclude terms (not the best way to do it) then how do you do that?

**Comment by ferdnyc** [comment]
@JUser69 In the end I suspect you'll end up _wanting_ to use regular expression filtering, it just makes things easier and cleaner. Creating filters using only substrings is like choosing to walk up 20 flights of stairs because you've never ridden an elevator before. :rofl: Regardless, the basics apply to either filter type equally.

#### Feeds & filters
Adding a Feed configuration gives RSSFeed Scanner the ability to download the feed contents and create a list of entries on the feed. If all you wanted to do is manually select feed items to download, you'd be done, because you could just double-click on any item in the list to add that torrent for downloading.

Adding _filters_ to the configuration lets you define which feed items RSSFeed Scanner will (or will not) _**automatically**_ import for downloading. A filter that Passes a feed item will import the item's magnet link as a download job and apply the configuration selected in the filter settings. It'll also apply all of the tags listed in "Set tag(s)/category".

(Tags are a powerful feature that can be configured to adjust _many_ torrent parameters simply by applying that tag to the torrent. Because RSSFeed Scanner supports applying tags when filtering, you can configure far more than the limited set of parameters it directly supports. Just create a tag that applies the necessary configuration, and add it to the filter's list of tags.)

#### Filter matching
Whether, and how precisely, you need to filter the items on a feed depends on its contents. I use one service that offers a web tool for creating custom feeds of their torrent stream. The custom feed configuration provides its own tools for selection and filtering, so that the feed comes into RSSFeed Scanner pre-filtered and **every**  item is a torrent I want to import. For that feed, I only have one filter defined, a Pass filter configured with the regular expression `.*`, which means "match everything". (It's the equivalent of specifying a single `*` wildcard when matching filenames.) That single Pass filter auto-imports every new item that appears on the feed.

Other feeds I have RSSFeed loading are more generic, they contain a mix of torrents I want and torrents I don't. For those, I have to define more specific filters that select only the items I'm interested in.

This is probably a good place to cover one of the fundamental concepts in working with RSSFeed filtering: Pass and Fail filters.

As I said, initially nothing is imported from a feed automatically. With no filtering, every item listed will be ignored. When a Pass filter is created for a feed, it scans the list of feed items for matches, and each match is added to the list of what will be auto-imported. Depending how the filters are defined, the list might now contain items that **should** be imported mixed with items that **shouldn't**.

For example, a Pass filter might look for just the title of a series. It'll match every episode, which is great, but if each episode is available in multiple different video resolutions it'll match them all. You may not want to import 5 different versions of each episode.

Depending on what you want to accomplish, there are different ways you can handle this.

1. If you want to require a specific format or formats explicitly, you can write a regular expression Pass filter that will only match torrents with both the title(s) and format(s) you've specified.

2. Sometimes, though, there are multiple options for what you're interested in. You don't want to specify an exact identifier to require, because it risks ignoring other acceptable options that aren't labeled in exactly the way your filter expects. But, you still know there are certain matches you definitely **DON'T** want under any circumstances. In those cases, you can create a Fail filter that will take matching torrents back off the list of imports that matched the Pass filters on the feed.

3. If there are multiple, _completely unrelated_ criteria for selecting torrents from a feed (say, you want all torrents for 'name1' in 720p, but also any torrent from season 3 or later of 'name2' in any format), there's no way to define all of that simultaneously in the same set of filters. But what you _can_ do is **create multiple Feed configurations with the same feed URL**. Then, each feed gets filtered separately using a different set of criteria. 

Multiple Feed definitions with a mix of Pass and Fail filters is often the best way to handle a feed that contains some torrents you want, mixed in with a lot of others you don't want. Using Pass filters exclusively or a single feed definition means that you have to specify every possible variation and combination of torrents to be imported. But by splitting the feed up to define separate Pass criteria, and using Fail filters where necessary to filter out certain torrents, you can use simple Pass filters that grab all possible matches for your criteria, with a Fail filter excluding anything you never want to import under any circumstances.


> Okay, let's forget the regex and go with the substring way of searching for matches. While right clicking on the torrent and selecting add filter does work, how do you modify that to narrow it down. For example:
> name1.name2.S07E02.1080p.WEB-DL.AAC2.0
> just selects every mention of name1.name2 (the season and episode seem to work okay)

You can match torrent names containing either "name1" OR "name2" (only) by using a regular expression filter. The syntax, specifically, is:

```
(name1|name2)
```

You could also accomplish this specific case with two substring Pass filters, one matching "name1" and the other matching "name2".

> Can I modify the search string to also look for "720p and web", if so, how? The typical * and | do not seem to work.

Substring filters can only have a single fixed string to match against the torrent, so they can't have more than one matching value or combine matches in multiple places in the name. There are no wildcards or patterns, "substring" means just that. A name will only match if the exact string of characters in the filter is found somewhere within the identifier for the torrent. Anything more complex, you have to use a regular expression filter.

There are good resources for learning regular expression syntax online, I don't have any suggestions handy but it shouldn't be hard to find resources that will get you up to speed. The  [regex101](https://regex101.com) tool is also handy for "debugging" complicated expressions, although generally if your filter expressions are getting that complex you should probably consider separating things into multiple filters and/or multiple feeds instead.

#### A quick rundown of basic regular expression syntax

* `.` has special meaning, it matches any one character (like a `?` in filename globbing).

    If you want to match literal periods in your target strings, you have to escape them. The R.E. `M\.A\.S\.H\.` matches the string "M.A.S.H.", explicitly. The R.E. `M.A.S.H.` will match "M.A.S.H.", but it will also match  `MaAaSaHa` and lots of other strings with an M, A, S, and H in those positions.
    
    The R.E. `....` will match **any** string of four or more characters. (Because an expression doesn't have to match the entire **string** to pass. An expression succeeds if any portion of the input string satisfies the entire **expression**.)

* `*` has special meaning that's different from how it's used in filename matches. In regular expressions, `*` or `+` placed after a character or expression indicates that it should keep matching repeatedly for as long as it's successful. When `*` is placed after an expression, it means "match 0 or more times repeatedly". `+` means "match 1 or more times". So, where a  `*` wildcard would be used in a filename match, in regular expressions the equivalent is `.*`: "Match any character, and do it zero or more times". (The character doesn't have to be the same one repeating, `.*` will match "aaaaa" but also "abcde". `a*` will match "aa" or "aaaaa", and it will match only the first letter of "abcde".)

* Multiple patterns can be "OR"-joined inside parentheses, separated by pipes: `(name1|name2)`

* To perform two matches in the same string, use `.*` to consume any characters between them. `name1.*720` matches only strings that contain "name1" followed by "720", and allows any other characters (or no characters) between them, before "name1", and after "720".

* The previous won't work if the order is swapped. If that's a possibility, you have to let each part match either string:
     ```
     (name1|720).*(name1|720)
     ```

    ...But a string like `name1...name1` or `720...720` will also match that expression, which is a flaw. To avoid that you have to completely define each alternative pattern separately. That way only a complete match on one of those patterns will succeed:

     ```
     (name1.*720|720.*name1)
     ```

* You can anchor an expression to the start of a string by leading with `^`. You can anchor it to the end by following it with `$`. So, `^abc` matches "abc" or "abcdef" but not "bbabc" or "babce". `xyz$` matches "wxyz" but not "xyzw". `^abc$` matches only the **exact** string "abc" and nothing else.

**Comment by ferdnyc** [comment]
Oh! Bit more:

* To match multiple alternative _characters_ in a given position, list them all inside square braces, without separators. Often used to ignore captialization: `[Ss]ome\.[Nn]ame` matches "Some.Name" or "some.name" or "some.Name" etc.

* Just like with periods, any other special syntax has to be escaped to match literally. `\*` matches "*", `\+\(.*\)` matches any string that has the form "+(<var>something</var>)". Escape all of the following, and more I'm not remembering ATM, for literal matches: `()[]{}*+.-?|^$`. Forgetting an escape usually just causes the expression to fail, figuring out exactly what's wrong is where regex101 comes in handy.

**Comment by JUser69** [comment]
Thanks so much for all the information.  But I have been trying to learn regular expressions for  25 years and have not done it yet, so probably will not do it now,  You did mention some other ways of doing it though that I was not thinking about.  The placement order of the matches and just making the first one a match of all that I dont want and set it to fail,  Seems to work nicely.
BTW:  Nice tutorial that you provided.  I will keep it just in case...
