### ISSUE TITLE
BBT crashes if torrent contains a lot of files

### ISSUE THREAD

**Issue by gh338** [BiglySoftware/BiglyBT#2792]
* Kubuntu 20.04.5
* BiglyBT 3.2.0.1_B11
* KDE

If a torrent contains 1000s of files upon clicking the Files tab or doing Ctrl+A BBT freezes.
I am not sure if this is related to ulimit in the first place - please advise.

Cheers

**Comment by gh338** [comment]
raised ulimit for the user - problem fixed.
i assume that torrenting in general handles 1000s of files for most users.
it would make sense to check the ulimit and display a warning and recommendation to the user.

**Comment by gh338** [comment]
another approach could be to make BBT handle file operations i a serial fashion to avoid ulitmit boundary.

**Comment by parg** [comment]
Hmm, I'm surprised it is ulimit related - just displaying files shouldn't result in actual file operations occuring. Unless you're doing more than that?

**Comment by ferdnyc** [comment]
That is weird; I regularly have multiple torrents running containing several thousands of files each, and I've never hit this. `ulimit -a` on my system reports a file descriptor limit of only 1024. (Locks are unlimited, though.)

It's possible I have BiglyBT configured to be less resource-hungry in general, to the point it's never been an issue. (Like, I limit connections per torrent to 30, so in theory that should also be the max # of simultaneously open files per torrent.)

**Comment by Nik343** [comment]
I've had Bigly's UI freeze numerous times on Debian 11 after right clicking on a torrent, selecting all torrents or clicking on "Open Torrents". I've tried a lot of things from different heap memory settings to updating the SWT library, but setting ulimit to something high seems to have fixed this problem. This issue was encountered especially often when trying to do the things I mentioned within a minute of opening BiglyBT.
