### ISSUE TITLE
Existing data files resulting in missing pieces

### ISSUE THREAD

**Issue by itlezy** [BiglySoftware/BiglyBT#2800]
Hi, first of all thanks for this great software.

The scenario is the following:
- there are existing data files that are for certain the correct data files and are fully complete (checked with externally calculated hashes of the files)
- torrent added to BiglyBT
- search for existing data files
- data files are matched, but after rechecking some pieces are reported missing (few of them, often 1 piece)
- if the torrent has seeds, it is possible to complete the download - which does not change the content of the files - almost as if it has to check the hash of the missing piece by downloading it and to ensure it's actually correct

This can happen also on torrents I have created locally, for which I have the files, and for which the files have never changed.

By checking the content of the files, as they are media files, I see there are some 0x0 sequences in them.

- might that be the reason for which some pieces are identified as missing? like is there any logic that tells if 0x0 sequence > missing piece, and it doesn't calculate its hash?

![2022-11-30 18_08_10-Window](https://user-images.githubusercontent.com/24484050/204868236-5537eb8d-2a98-4621-b130-c66692c4a04d.png)

![2022-11-30 18_12_22-Window](https://user-images.githubusercontent.com/24484050/204868216-8a88750a-1caf-495a-b181-c17971d73b35.png)

---

Java 1.8.0_351 (64 bit)
  Oracle Corporation
c:\program files\java\jre1.8.0_351

SWT v4942r22, win32, zoom=100, dpi=96
Windows 10 v10.0, amd64 (64 bit)
B3.2.0.0/4 az3

**Comment by parg** [comment]
There's nothing special about any byte sequence regarding hash checking so ignore that.

You will notice all missing bits are at the start/end of files which would imply that there's an issue with the boundary pieces that span files.

Perhaps something is messing with the start-end of your files (e.g. some player is updating ID tags). Alternatively there are other files missing that are required for checks to complete. If file A is followed by file B in the torrent and a piece spans the AB boundary it isn't possible to check end of file A without having the start of B downloaded.

Bittorrent doesn't care at all about the individual file hashes, it only cares about the piece hashes, so your statement that the files themselves are correct due to some external hash check is irrelevant.

**Comment by itlezy** [comment]
No that's clear. Wish we started with file-aligned hashes since V1..
Thanks for confirming there's no special handling of null sequences
