### ISSUE TITLE
Enforce Torrent Network Setting (Public/Tor/I2P)

### ISSUE THREAD

**Issue by gh338** [BiglySoftware/BiglyBT#2848]
* Kubuntu 22.04
* 3.2.0.0
* KDE

is there a way to enforce the Network (Public/Tor/I2P) on torrents other than javascript ( it's not available on JRE11+ ) ?

**Comment by parg** [comment]
You can do it via Tags if nothing else - https://github.com/BiglySoftware/BiglyBT/wiki/Plugins#invocation-from-tags

**Comment by as-muncher** [comment]
If I may add something to this.  When I search for something in the swarm, and find one marked as I2P, even just downloading the magnet is done just over I2P and no other networks.  If just the .torrent file is downloaded over I2P, definitely the data should be downloaded over I2P as well, ignoring that I've selected Public, I2P, and Tor as my networks for downloading torrents - that setting is for general usage, but when something is tagged as I2P, then the .torrent file and the data should both be downloaded over I2P only by default, and not put it on the public non-anonymous network.   I don't want to forget to uncheck the public network, don't want to have an accident.

Java 1.8.0_202 (64 bit)
  Oracle Corporation
c:\program files\biglybt\jre

SWT v4942r22, win32, zoom=100, dpi=96
Windows 10 v10.0, amd64 (64 bit)
B3.2.0.1_B46/4 az3

**Comment by as-muncher** [comment]
@parg Should I make this a separate Issue?

**Comment by as-muncher** [comment]
Java 1.8.0_202 (64 bit)
  Oracle Corporation
c:\program files\biglybt\jre

SWT v4942r22, win32, zoom=100, dpi=96
Windows 10 v10.0, amd64 (64 bit)
B3.5.0.0/4 az3

In Options -> Connection, only the Public network is checkmarked.  But in Plugins -> I2P helper, Enable (*) is checkmarked. In Options -> Plugins -> Tor helper, the Enable (*) is also checkmarked.   Under Plugins -> Magnet URI handler, default networks has only Public checkmarked.  In Options -> Sharing, Use Global defaults is checkmarked, so the three networks listed below are greyed, and only Public is checkmarked.  So there seems to be a conflict when I2P helper is enabled.  Perhaps if someone chooses to uncheck I2P or Tor in Options -> Connection, then the I2P and Tor helper plugins should be automatically disabled, too.   One of these settings has to have priority over the other ones.  Otherwise, a person thinks he has disabled certain networks and they are in fact running.

What's happening is that my networks that I choose to use is being ignored.  I just want to use the Public network.  But in my display, I choose to add the column that shows which networks my torrents are running on, and I see that metadata information is being asked for on the Public, I2P, and Tor networks, and that when that data comes in, the torrent continues to be downloaded on those networks instead of just the Public network that I had specified.

**Comment by as-muncher** [comment]
Please reopen this issue.  And please give users other than the original posters to reopen issues here on BiglyBT's github Issues page.

**Comment by parg** [comment]
If I'm not going to work on something I'm not going to leave it open.

Otherwise things get out of control and the whole issue system is pointless.

**Comment by as-muncher** [comment]
I've seen that you can close issues as "not planned" rather than "completed".
At least with the Issue system, people are telling you problems with the software.  Shouldn't you at least know about them, even if you don't work on them?
