### ISSUE TITLE
If torrent has I2P tag, then by default, override current defaults and download over only the I2P network

### ISSUE THREAD

**Issue by as-muncher** [BiglySoftware/BiglyBT#2867]
mentioned here:
https://github.com/BiglySoftware/BiglyBT/issues/2848

If a .torrent file is download over just the I2P network, then it makes sense to download the torrent data by default over just the I2P network, overriding the default networks selected in Options.  This helps the user to not make the mistake of downloading by mistake over the public non-anonymous networks.

**Comment by parg** [comment]
No it doesn't.

If people want to download purely over I2P then they need to know what they're doing and explicitly control the process. 

BiglyBT isn't I2PSnark.

If I added your proposal I would just be deluged by people who are currently running I2P in a "help the network but I don't particularly care" fashion (most users I would say) with downloads stuck or downloading very slowly, ignorant of the fact that I2P-only downloading has been silently enabled just because someone else in the swarm happened to be running I2P.

**Comment by as-muncher** [comment]
@parg, At least I find BiglyBT easy to use, and it's too bad that you feel that you couldn't handle the deluge of requests to fix stuff that you figure might not even get used.  I tried looking on the github i2psnark page and they don't even give instructions on how to install it.  I had to go searching on the regular web for how to do it, and it seems complicated.  I'm just looking for ways to make the i2p plugin for biglybt a bit more safe to use.
