### ISSUE TITLE
Tag Constraint: Add "Full Copy Seen"

### ISSUE THREAD

**Issue by Zenya393** [BiglySoftware/BiglyBT#2884]
I want to keep track of potentially dead torrents.

I would like to automatically tag torrents based on the time (preferably days) since the "Full Copy Seen".
If a full copy hasn't been seen for X number of days, then the torrent is probably dead. 
If there's never a full copy, then I don't want to allocate bandwidth or queue priority to a torrent that has < 1.0 availability.

I believe I can accomplish managing these torrents if there was a "Full Copy Seen" variable.

B3.3.0.0

**Comment by parg** [comment]
B07 has two things - a full_copy_seen variable and a timeToElapsed function to convert a time into seconds elapsed since the present

See https://github.com/BiglySoftware/BiglyBT/wiki/Tags

So something like

age > dtos( 5 ) && ( full_copy_seen  < 0 || timeToElapsed( full_copy_seen ) > dtos( 5 ))

might work for you if your time limit was 5 days.

**Comment by Zenya393** [comment]
Thank you.  Sorry I didn't see "full_copy_seen" before.
I also just figured out B07 is referring to Beta 7.
Thanks again!
