### ISSUE TITLE
Installer 64/32bit Doesn't Recognize Java 9

### ISSUE THREAD

**Issue by TomatoLoli** [BiglySoftware/BiglyBT#29]
Observed behaviour: Installer attempts to automatically download Java.
Expected behaviour: The program to be installed for testing with Java 9.

Workaround: Removing JRE folder from BiglyBT's installation directory.
Setting environment variable EXE4J_JAVA_HOME to java 9's installation folder.

![image](https://user-images.githubusercontent.com/31081814/29388049-04c10c3e-82b1-11e7-86f3-19b3ce672585.png)

Windows 10 Build 1703
java version "9"
Java(TM) SE Runtime Environment (build 9+181)
Java HotSpot(TM) 64-Bit Server VM (build 9+181, mixed mode)

**Comment by TuxPaper** [comment]
We've intentionally forced Java-8-only in the installer, due to some changes in J9 that mess up some stuff (networking I believe). @parg has fixed one of them so far at 28285a4df2c9fdfdcb2dac0a2ba6893726a4240a, so please switch to the beta program if you plan on using J9 :)

BiglyBT application, as you found out, doesn't have a J9 restriction on it.  Although it's surprising you had to set EXE4J_JAVA_HOME.  I would have expected it to just find J9 if it can't find the local JRE folder.

The screenshot makes me sad.  I need to install Windows 10 so I can fix the pixel-y image rendering (#16)
