### ISSUE TITLE
Need bandwidth separated between WAN and LAN

### ISSUE THREAD

**Issue by Zenya393** [BiglySoftware/BiglyBT#2903]
The LAN network traffic bandwidth is counted towards the net_limit configuration in Speed Limit Profiles.

I do not need to limit bandwidths on LAN, but I do need limits on WAN.

I also have enabled separate LAN speed limits, but this appears to apply to transfer rate, not bandwidth.
Transfer: LAN = Enable separate speed limits for LAN connections.

B3.3.0.0

**Comment by parg** [comment]
I believe that network limits with a specific Tag don't could LAN transfers if "enable separate LAN speed limits" are enabled.

Network limits without a Tag don't as currently the long-term stats recording stuff doesn't distingish between LAN and non-LAN.

I might be wrong, perhaps you could test by setting up a tag that has all downloads allocated to it (use a Tag Constraint of "true") and use that in your net_limit

**Comment by ferdnyc** [comment]
The Speed Limit Scheduler permits the definition of `peer_set`s that can be partitioned by (among many other things) CIDR subnet addresses. Would defining two peer sets for LAN and WAN connections, then using those in your speed limit configuration, perhaps give you what you need? e.g...

```ini
peer_set LAN=192.168.1.0/24  # (Or whatever)
peer_set WAN=LAN,inverse=yes
```

(See **Tools > Speed Limit > Schedule and Settings...** for documentation on the configuration language & options.)

**Comment by ferdnyc** [comment]
(Experimentally, because I don't have any LAN peers, I partitioned my peer connections into two `peer_set`s:

```ini
peer_set Hi=192.0.0.0/6
peer_set Lo=Hi,inverse=yes
```

That gave me two new tags:
* **"Hi"**, containing all of the peers with an IP starting with 192 or higher
* **"Lo"**, containing every IP with a first octet between 1 and 191.

I have the ability to set upload and download speed limits separately for each of them.

![image](https://user-images.githubusercontent.com/538020/224453715-91e91715-b172-4be8-9bd0-4f91a7dfeb6c.png)

I was a little worried, especially based on one possible interpretation of this statement (which I'm still not sure I'm understanding completely):

> I also have enabled separate LAN speed limits, but this appears to apply to transfer rate, not bandwidth.

...that setting a limit there might only constrain the _per torrent_ speeds, not the total aggregate rate for the (network/tag/grouping). But after setting a very low "Up Speed" limit of `20 kB/s`, the _aggregate_ upload rate for all peers in the group appears to be holding at or below that value.
