### ISSUE TITLE
Lost all settings after todays update

### ISSUE THREAD

**Issue by dbareis** [BiglySoftware/BiglyBT#296]
Lost all settings after todays update, currently on 1.4.0.0 but I think it might have been a beta update (immediately) before that?

WIN10 64 bit.

**Comment by dbareis** [comment]
It hasn't made any backups (that I can find) and won't restore Vuze backups

**Comment by parg** [comment]
For backups to occur you either have to do them manually or configure periodic ones via Tools->Options->Backup & Restore

I assume you updated via the 'new version available' prompt rather than downloading a new installer yourself and running it?

If you want to re-import the Vuze settings then grab a new installer from https://www.biglybt.com/ and select the option during installation (If you have a previous install then this option is disabled by default)

**Comment by dbareis** [comment]
Thanks, Yes I followed the 'new version available' bouncing ball.  I have now reinstalled BiglyBT (after chosing config clearing during uninstall) and can see the automatic backup settings were migrated (at least this time):

* Settings shouldn't get lost in upgrade.
* No backup was made after first install/migration, I think this is a bug, it should do so for something to restore to.

**Comment by user8446** [comment]
I'm on the beta channel and I haven't lost any setting on incremental updates. Possibly some happened locally on your machine?

On another note I see in options>files under configuration settings there is a "backup configuration files for recovery purposes" which is different from the normal backup & restore. Not sure what that is for.

**Comment by parg** [comment]
The option you mention causes '.bak' files to be created for the various configuration files when they are updated - it is no replacement for a proper backup approach, either using specific backup software (e.g. Windows backup and restore) or by configuring the BiglyBT backup via Tools->Options->Backup & Restore.
