### ISSUE TITLE
Feature: change bincode files storage for config/statistics/history to sqlite files

### ISSUE THREAD

**Issue by rwperrott** [BiglySoftware/BiglyBT#2969]
Today I needed to redownload some torrent referenced content due to another application errantly deleting some files, but BiglyBT refused and gave me no option to redownload this content! I could find no easy way to find and delete the download history entry for the specific torrent (bincode editor support is poor), so risked deleting all the download history to successfully bypass this nuisance. I have scheduled daily backups, so could afford this risk.

bencoded data is fine as a compact transport format, but horrible as a local config/data storage format, where compactness is far less important. sqlite files long ago became the standard for storing single user config/data, and there are plenty of feature rich sqlite clients available which would make them easy to maintain and edit, while BiglyBT is not running. A sqlite database can contain multiple sets of data in multiple tables, so could reduce the number of files which need to be managed and backed up. Use of sqlite database(s) may also reduce memory load and startup time for BiglyBT, because it is already structured for lookup.

I suggest that BiglyBT config and data storage is migrated to use one or more sqlite database files, for all but saved torrents and plugin's own files. Unstructured content could be saved in the database(s) as JSON text.

**Comment by parg** [comment]
Not sure what your problem was but going from "BiglyBT refused and gave me no option to redownload this content" to rewriting stuff to use sqlite doesn't really make sense... 

Perhaps explain what your actual problem was first? I can guarantee that the presence of an entry in "download history" has absolutely nothing to do with it though.

**Comment by rwperrott** [comment]
The bits I tried which allowed re-download were deleting all the dlhistory*.config bincoded files, and the downloads.config file in the ~/.biglybt directory, but keeping the .bak files. I had to guess and delete, because of lacking bencode GUI editor support to see the custom structure, get what it's for, and be able to CRUD nodes/leaves, as needed.

Another example was that biglybt.config was a pain in the past, because some saved settings stopped it working on restart; I had to copy in a different one to fix it, because of the above editing problem.

I put SQLite as a feature, because it's a nice to have, but may not be easy to do. SQLite editors are prevalent, mature, and rich featured, so easy to use, including to fix issues with a client app.

**Comment by parg** [comment]
My point is that if you wanted to redownload something then you can find it in the download history, right-click on it and select "redownload". Not sure why you are hacking around to remove stuff from the config files.

Also, just because an application happens to use an SQL database to store internal stuff it doesn't mean that it is safe for users to start hacking around with it. Maybe things have been denormalised, for example, and you need to delete multiple things/edit entries to keep things consistent...

**Comment by rwperrott** [comment]
Closing this, after doing Platform Engineering has clarified my ideas, so posted a new feature issue #2977
