### ISSUE TITLE
Allocation Rechecking at every start

### ISSUE THREAD

**Issue by absolutep** [BiglySoftware/BiglyBT#3008]
I do not know why it happens but

**Whenever I start BiglyBT, it rechecks & allocates all of my 40 torrents.**

**This results in freezing of the application & my computer as well as results in extremely high RAM & disk usage.**

I decreased the number of my torrents from 40 to 4 and it still happens albeit the process gets completed faster due to only 4 torrents being present.

Everything is in default settings.

screenshot
![1](https://github.com/BiglySoftware/BiglyBT/assets/97702149/3ebf8041-d537-4eae-a661-f234c96e52d8)

Java 1.8.0_202 (64 bit)
  Oracle Corporation
c:\program files\biglybt\jre

SWT v4942r22, win32, zoom=100, dpi=120
Windows 10 v10.0, amd64 (64 bit)
B3.4.0.0/4 az3

**Comment by parg** [comment]
Is it actually allocating new files? Downloads that have been allocated before normally transition through an "allocating" phase on restart as the existance of their files is checked (as opposed to actual allocation taking place).

If they are going through a "recheck" state then BiglyBT must believe the data in the downloads is potentially corrupted. This can happen if BiglyBT doesn't close down tidily (e.g. crashes) - does it appear to close succesfully?

There must be something strange about your setup, especially if you haven't changed any settings), as there are a lot of users out there that don't have this issue!

**Comment by as-muncher** [comment]
I'm using biglybt 3.4.0.0

I have been finding that biglybt has been rechecking my torrents 3 or 4 times over the past 2 days, and that's 100s of GBs of data.  I've been finding data missing.  BiglyBT has checked all my files, some with Downloading + swarm, I look at System Informer to see if any swarm merging is going on in the background, and when everything is done, then I restart BiglyBT.  But then what I find is that then one of my torrents starts up, and some of the data files are at 0.0% - the files are just gone.  I don't know if it's because I use an incomplete file extension, or what the deal is.  I changed the save resume data interval to every 2 min instead of 5, because I was tired of BiglyBT saying that there's data missing when it isn't shut down correctly.  But specifically, data was missing when I chose to restart biglybt, even though everything was checked, swarm merging in the background finished, no disk operations except when biglybt is shutting down.  So that's why you haven't heard from me in so long, is because I've been using qbittorrent, and now I am going to have to go back/stay using qbittorrent because of missing data due to biglybt.  I've also done it where I've paused my torrents, then search for existing data files, copy mode, for files that were downloaded elsewhere to completion, and so everything transfers, torrents are rechecked, swarm merging may or may not happen in the background, but then specifically when I choose to restart biglybt, then a file or two in my torrents just go missing.  Maybe it's the resume data state, where it's maybe looking for x.mp4 for instance, and not looking at x.mp4.!qB or whichever incomplete file extension I use.  I can't be using biglybt and have all this missing data all the time.

**Comment by absolutep** [comment]
> Is it actually allocating new files?

NO

> If they are going through a "recheck" state then BiglyBT must believe the data in the downloads is potentially corrupted. This can happen if BiglyBT doesn't close down tidily (e.g. crashes) - does it appear to close successfully?

Irrespective, of how BiglyBT closes [tidily or untidily] it reallocates & rechecks all the files - after every start.


> There must be something strange about your setup, especially if you haven't changed any settings)

Nothing strange, as far as my system is concerned,  I use BiglyBT for I2P torrenting.
