### ISSUE TITLE
availability of torrent

### ISSUE THREAD

**Issue by johnvolfovits** [BiglySoftware/BiglyBT#3037]
* OS and version :win 11 and
* BiglyBT Version Number :B3.4.0.0/4 az3
* For *nix: Desktop Environment
how could i check a torrent availability(for peer that complete download )periodic with a script or something else that biglybt run it and show me the result?

**Comment by parg** [comment]
What are you trying to achieve?

**Comment by johnvolfovits** [comment]
check availability of a torrent automated

**Comment by parg** [comment]
So you have download a torrent and then want to check its availability? Why? So you know whether to remove it from BiglyBT?

**Comment by johnvolfovits** [comment]
check for availability when adding it to biglybt! and periodically check it with a script or something to see is there any peer complete  the torrent download?
because i have some torrent for so long time that they have no peer with 100% download for them

**Comment by parg** [comment]
Maybe set your download queue order to "seed count" via the setting

Options->Queue->Downloading: Prioritize downloads based on

Ensure you have selected "Options->Files: Use sparse files when supported by the file system" (assuming you have a file system that supports sparse files) so that minimal space is used by downloads with little download.

**Comment by johnvolfovits** [comment]
that was helpful
