### ISSUE TITLE
Some text is cut off at the end inside Options dialog

### ISSUE THREAD

**Issue by adem4ik** [BiglySoftware/BiglyBT#3108]
* OS and version: Manjaro Linux x86_64
* BiglyBT Version Number: 3.5.0.0
* For *nix: KDE Plasma 5.27.9
* Java 21 (64 bit)
* SWT v4942r22

1. Install BiglyBT from [AUR](https://aur.archlinux.org/packages/biglybt) or using official **Installer for Linux, BSD, etc**
2. Open Tools > Options...

Result: Some text is cut off at the end.

Extra info: Latest beta B3.5.0.1_B04 has the same problem. But there is no such issue on Windows 10.

![изображение](https://github.com/BiglySoftware/BiglyBT/assets/4707112/1fb7b18f-fcd0-4cbc-9a6e-1134c27c7a98)

**Comment by parg** [comment]
That's Linux for you

**Comment by TuxPaper** [comment]
What does Help->About BiglyBT  say for java version and SWT version?

If you are using Java 8 - 16, you will be on an old SWT (v4942).
If you are using Java 17 or higher, and used the installer .sh, you should be getting a later version of SWT (v4962).

You can also grab the latest SWT (release, stable, integration, etc) from https://download.eclipse.org/eclipse/downloads/ to see if the bug is fixed.  

Although it may also be a KDE Theme issue.  Some theme creators don't spend a lot of time fixing up edge cases. So, you could try changing your theme and see if that helps.

**Comment by adem4ik** [comment]
@TuxPaper I've added Java/SWT versions to the main post:
![изображение](https://github.com/BiglySoftware/BiglyBT/assets/4707112/7f0e6803-b94b-49a2-b99d-75edd80d5a7a)
It seems like my installation uses old SWT version with Java 21.

Anyway here is the summary of my short researching:
- There is no such issue on XFCE 4.18 (Simply Linux 10.2)
- Switching GTK theme from Breeze to Adwaita fixes the problem on Manjaro's KDE.

![изображение](https://github.com/BiglySoftware/BiglyBT/assets/4707112/5e1a419f-3901-4c79-9fe9-5333611446b5)
