### ISSUE TITLE
Start/Stop button issues

### ISSUE THREAD

**Issue by de-served** [BiglySoftware/BiglyBT#3109]
Bigly BT 3.5.0.0/4 az3
Java 20.0.1 x64 Eclipse Adoptium
Win 10 x64
SWT v4956r12

1. Extended list view (sidebar at left, torrents to download upper list, downloaded torrents - middle (bottom) list, torrent details (common/files/settings/peers... etc) - at bottom)
2. Find a downloaded torrent with all files with "Delete" status
3. Check that torrent is is state "Stopped"
4. Click at this torrent
5. Look at the Start/Stop button - it is in Stopped state and waiting to Start
6. At the bottom part with torrent details select "Files" tab
7. Click at any file (all of them with "delete" status, remember)
8. Press "Space" - file status will be changed to "Normal" and the torrent will jump to upper list (to download)
9. Look at the button Start/Stop - it is now changed to Started state and waiting for Stop (red box), but must wait to Start
10. Click at that "Stop" button - torrent starts, button changes it's state for a moment and then changes back to Started
11. Click that button few times - torrent state changes from"Download/Stopped" and vice versa but button is always in "Started" state
12. Click at any part of main window where is no any pressable buttons/inputs/menus/torrents - Start/Stop button now fixes

**Comment by parg** [comment]
What does the tooptip say for the start/stop button? If you hold down CTRL before showing the tooltip there is more info,

Probaby some interaction between the Files tab and the Torrents view in term of toolbar context.

**Comment by de-served** [comment]
![BiglyBT_sqNuRAFAB1](https://github.com/BiglySoftware/BiglyBT/assets/18093731/8d19e52f-1b7f-4b55-9ed3-d8d3db41ede9)

**Comment by parg** [comment]
It is "skipping selected files" not "stopping the torrent". Changing the selected file set will cause the torrent to automatically be stopped and started.

**Comment by de-served** [comment]
So it is normal? Clicking Start/stop and it is always Started state, State is not shows real state...

Ok. No bugreports from me ever.
Good luck.

**Comment by parg** [comment]
My point is that the toolbar controls more than just the torrent start/stop state (whether that's a good thing or not I'm not 100% sure). But as it is implemented it also controls File skipped/non-skipped state when a file is selected in the Files subtab. It also can be used to delete subscription entries, for example. If the focus is on a file then it works on that. If the focus is on a torrent it works on that. The "issue" is that multiple things can be on the screen at a time - incomplete torrent, complete torrent, file... and it can be confusing which one the toolbar is acting on. Which is why I always explicitly click on something before using the toolbar.
