### ISSUE TITLE
Link to swarm merging incorrectly point to http://wiki.vuze.com/w/Swarm_Merging

### ISSUE THREAD

**Issue by andrasfuchs** [BiglySoftware/BiglyBT#3298]
OS: Windows 11
BiglyBT Version Number: 3.4

System:
Java 1.8.0_202 (64 bit)
  Oracle Corporation
c:\program files\biglybt\jre

SWT v4942r22, win32, zoom=100, dpi=96
Windows 10 v10.0, amd64 (64 bit)
B3.4.0.0/4 az3

I got a torrent related message in its public chat that I could enable swarm merging to improve sharing:
![image](https://github.com/BiglySoftware/BiglyBT/assets/910321/8bfa1547-6f15-4ef5-9baa-9c4436899cb4)

But it points to the `http://wiki.vuze.com/w/Swarm_Merging` URL. The correct URL would be: `https://github.com/BiglySoftware/BiglyBT/wiki/Swarm-Merging`

Also the `See Swarm Merging for help` message doesn't indicate the reason for it. I didn't know if I have it already enabled (I had) or if the message was generated because a merging occurred or some other reason.

**Comment by parg** [comment]
Well the correct URL is http://wiki.biglybt.com/w/Swarm_Merging. 

However the message has been posted by a Vuze client which is why it contains the old Vuze wiki link.

I suppose I could hack something to change it but not sure I can be arsed. The context for the message is the previous lines, the other client is hinting that an alternative download may contain the same files and hence that swarm merging maybe useful to you.
