### ISSUE TITLE
[SUGGESTION] allow making a save-able regex string for Swarm Discoveries and the same for Subscription searches

### ISSUE THREAD

**Issue by HiPlainsdrift3r** [BiglySoftware/BiglyBT#3398]
* OS and version
* BiglyBT Version Number
* For *nix: Desktop Environment

Not sure if suggestions are taken - but here it goes

If would be great if there was a way to have the ability to create a master custom REGEX for the Swarm Discoveries that would always be applied - rather than having to reapplied with each reboot.

for instance - I use key words to 
Includes the year 2023 or 2024.
Includes "1080p".
Does not include "720p", any explicit content, certain languages, or specific file types (like .zip).
Does not contain any characters from specified Unicode ranges, which likely correspond to certain languages/scripts.

It's easy enough to paste back in each time - but it seems like it should be able to be an option to apply - especially
if you know how to create regex statements.

**Comment by parg** [comment]
If you have created your own subscription (rather than using an existing one) then you have the option to save your settings (there's a save button next to the include/exclude etc filters).

For swarm discoveries , if you right-click on the "swarm discoveries" header in the sidebar then you get a menu that allows you to "discover by search/file size/hash..." - selecting one of these will give you a separate swarm discoveries results tab that has an RSS icon - you can click on this to create a subscription from the swarm discover results and this subscription will allow you to save settings (as you created it)

One way of getting around the "not my subscription" problem is to create your own one based on the existing one. The way to do this is a bit involved. Go to Options->Subscriptions and enable the "create rss feeds from subscriptions" checkbox at the bottom. THen click on the "click to view RSS feed" link. This will give you a webpage listing all your subscriptions. Find the one that you want to make a copy of, right-click on the link and copy-to-clipboard. This link will be something like "http://127.0.0.1:6905/subscriptions/UO3OHUWQXUKTK2D6". Now create a new subscription by clicking on the "+" icon in the Subscriptions header in the sidebar. Hit the "create new subscription" button, click the "RSS" tab, paste that URL into the rss location, give it a name and hit save.
