### ISSUE TITLE
uninstallation in linux (fedora)

### ISSUE THREAD

**Issue by legacychimera247** [BiglySoftware/BiglyBT#34]
wanted to try out biglyBT in fedora workstation but i am not sure on how to remove it...just run the scipt as i have done for installing?and will it remove all of it dependencies?(like java for example)

**Comment by TuxPaper** [comment]
There's a `uninstall` script in the app dir, `~/biglybt/uninstall` if you used the default directory.  It will only remove BiglyBT (and will only remove the config files if you tell it).

It won't uninstall java, since there's no good way to determining if another app still requires java (plus the uninstaller doesn't know who originally installed java).  For Fedora, java is almost always already installed by the OS.

**Comment by legacychimera247** [comment]
well it asked me to install something like jna.jar and then to install the app...at the end i unistalled jna.jar and removed all files and folders related to biglyBT...seems a good way of remove files to me...

**Comment by TuxPaper** [comment]
Erasing all the files and folders related to BiglyBT is fine. :) I'll close this issue since you successfully uninstalled

**Comment by styromaniac** [comment]
File manager context menu: "Open terminal here"

sudo bash uninstall
