### ISSUE TITLE
Help / Check for Update(s)

### ISSUE THREAD

**Issue by trgarner** [BiglySoftware/BiglyBT#36]
Takes some time to do update, sits @ 83% for quite  a while.

Non-mandatory plugins -     Failed to load details for plugin 'aznettor': https://files.biglybt.com/plugins/aznettor-win32_1.2.2.zip: I/O Exception while downloading 'https://files.biglybt.com/plugins/aznettor-win32_1.2.2.zip', java.security.cert.CertificateException: No subject alternative names matching IP address x.x.x found

  Non-mandatory plugins -     Loading details for azneti2phelper/I2P Helper Plugin
    Non-mandatory plugins -         current=0.9.30.1.3, latest=0.9.31.1.1
    Non-mandatory plugins -     Failed to load details for plugin 'azneti2phelper': https://files.biglybt.com/plugins/azneti2phelper-win32_0.9.31.1.1.zip: I/O Exception while downloading 'https://files.biglybt.com/plugins/azneti2phelper-win32_0.9.31.1.1.zip', java.security.cert.CertificateException: No subject alternative names matching IP address x.x.x.x found

The above is from the Operation in Progress windows after clicking Help / Check for updates.

Java 1.8.0_131 (64 bit)
SWT v4757, win32
Windows 10 v10.0, amd64 (64 bit)
B1.0.0.0/4 az3

**Comment by parg** [comment]
I'm guessing you have turned on 'anonymous updates' under Tools->Options->Interface->Start.

This appears to be broken at the moment as running the SSL connection over Tor to https://files.biglybt.com/ is generating an SNI error.

If you can, please turn off anonymous updating until a fix is available. Otherwise you could work around it by using a TorBrowser to directly download the .biglybt updates from the same location (replace .zip with .biglybt) and install them manually

**Comment by trgarner** [comment]
Bingo!  That was the problem - all is working now, update is fast and all items that needed updating has been updated!

Went in to Tools / Options / Interface / Start - unchecked Update Anonymously 
Restarted BiglyBT
and everything worked as advertised.

Thanks for the explanation and for now, all is working.
