### ISSUE TITLE
Already Exists problem

### ISSUE THREAD

**Issue by nodern** [BiglySoftware/BiglyBT#394]
Java 1.8.0_152 (64 bit)
  Oracle Corporation
c:\program files\biglybt\jre

SWT v4757, win32
Windows 7 v6.1, amd64 (64 bit)
B1.4.0.0/4 az3

![alex](https://user-images.githubusercontent.com/6150587/36948244-49f97ea0-201b-11e8-9f2c-5e55881c0792.png)

When I add a new torrent, I get this message. I want to seed one file at two trackers(cross seeding or double seeding), but I can’t. Some torrent is possible, others aren’t. Maybe different piece size is the reason. Can I seed same file for several trackers at the same time?

**Comment by parg** [comment]
You can't add an identical torrent more than once to BiglyBT. If it is a public torrent then you can just edit the trackers (right-click on the torrent and select Tracker/Torrent->Edit Trackers) and add whatever you want

**Comment by nodern** [comment]
@parg Even they have different tracker? (Not public torrent)

**Comment by parg** [comment]
Unfortunately not - the 'info hash' (i.e. the unique identifier) for a torrent doesn't include the tracker list. Private trackers like to totally control their torrents which is why BiglyBT won't allow you to edit a private torrent's trackers. Not sure if any torrent clients out there would allow you to add more than one torrent with the same hash.

You would need to run two copies of BiglyBT at the same time to achieve your aims. This can be done by the use of command line switches if you are interested.

**Comment by nodern** [comment]
@parg Thank you for your kind and fast response.

I’m interested in running two copies of BiglyBT at the same time. Where can I find the information about it?

**Comment by parg** [comment]
There's some basic instructions here: https://github.com/BiglySoftware/BiglyBT/wiki/Command-Line-Options

**Comment by nodern** [comment]
@parg Thank you very much!

I’m not familiar with github. Between I close this issue or not, which one should I do?

**Comment by parg** [comment]
I'll close it - just add some more comments if you have further questions!
