### ISSUE TITLE
High Priority Tracker feature for private trackers

### ISSUE THREAD

**Issue by ChrsKt** [BiglySoftware/BiglyBT#52]
I have slow internet, but I always get a positive seeding ratio on public torrents. But on private ones I cant help too much, most of the times because im seeding public torrents instead the private ones.
It would be great when the "High Priority" Tag changes the seeding behaviour in a way that these torrents _always_ seed when possible

**Comment by parg** [comment]
Are you referring to this feature - http://wiki.vuze.com/w/Speed_Limit_Scheduler#Preferred_Seeding_By_Tracker ?

**Comment by BuggerReporter** [comment]
Partly, this does not seem to force the start of the high priority torrents. 
But thank you, Ill try it out when I understand it :)

**Comment by HOTinHEELS** [comment]
your problem with poor seeding on private torrents is very common and is primarily due to the fact that there are a large number of members on private trackers who use rented seed-boxes which have **upload** bandwidth from 100Mbps to 10Gbps.  If a peer is connected to a few high-bandwidth seeds that are able to satisfy all her requests, then you are gonna be flapping in the wind trying to even connect.  Another criteria that affects PT seeding is that PT memberships are usually capped and there are fewer peers leeching, especially if the torrent is aged 7d or more.  Most PT members will acquire the content in the first 24 hours, unlike public sites where peers are more constant during the first week of a torrent.  The pro of private torrents is that you are likely to have seeds even on an old torrent and get to complete it, but with public torrents, the public just want to leech and not seed, so after the first week, completing a download on a less popular torrent can be a hit-miss affair.  Remember this when you think about stopping your torrents with a ratio below 1.  Also, Priv-trackers rely on the principle that you are **part of a caring & sharing community** and that you will leave your torrents seeding for months, even past a 1:1 ratio because you **care**.
