### ISSUE TITLE
Missing basic functions - fix immidiately!

### ISSUE THREAD

**Issue by Vpstr** [BiglySoftware/BiglyBT#549]
Hello!
I discovered something in your client that was a shockingly unpleasant surprise to me. It turned out that some core functionality is just missing despite all the plenty of tools and settings that your client is famous for. I started using it because of this fame with a purpose of having no trouble with basic functions and still I'm facing them. It's a great shame for you and you must fix these as soon as possible.
The troubles I faced follow.
First, if I download a torrent with many files and I don't delete the top level folder when adding torrent, I can't delete it later if I need to move the files. This is crap.
Second, it turned out that it's impossible to retarget entire folders (not single files) in case a downloaded torrent contains them. So if I want to redirect a folder, I have to redirect all files in that folder one by one, which is double crap. 
And third, if the torrent contains several folders, but I download files from only one of them, all the folders are created on disk anyway, although empty, thus cluttering the disk with junk. And if the torrent contains a 100 folders... I don't have the words. This is triple crap. 
But that's not all! The search fields in different places are case-sensitive and there's no way of changing that! Using regexes is too complex and what if I don't know them at all. 
You know, before developing new fancy features like swarm discoveries you must first finish the basic functions, which these defects definitely describe. You must feel big shame for these defects and fix them immediately. I'm writing all this not because I'm trolling you or some other moronic reason, but because this is a real fail of yours.
Are you wise enough to accept it?

**Comment by parg** [comment]
Thanks for the valuable input

**Comment by Havokdan** [comment]
Spammer!!!!! Free Gizmo and ban Spammers! Sorry,I did not resist the flood.

**Comment by ferdnyc** [comment]
Personally, I'd be _honored_ that someone created a Github account and opened their first-ever issue in order to deliver this missive. **#RantingIsCaring**

**Comment by Vpstr** [comment]
So will you fix these problems? And how soon?

**Comment by Havokdan** [comment]
And the flood continues.

**Comment by Vpstr** [comment]
> LOL. Some friendly advice: Rethink your entire approach.
Your advice stinks and is of no interest to me. I was talking to the developers, not you, and I don't think they hired you as an advocate to speak on their behalf.
And for argument's sake I'm not ordering anything, I'm taking an interest in when the problems will be fixed. 
Your approach is slavish mumble "who am I to express any discontent and demand anything from the great developers who have worked so much to bring us this piece of software for nothing?" and you want everyone else to think like that. First, the software being free doesn't cancel the developers' responsibility for it's quality (and doesn't cancel their earning money for it). Second, for me the answer to your question follows. I'm a user who is seriously concerned about the products quality so I'm saying what I'm saying. As for you, you're a spiritual slave and you're pathetic in your self-treatment, so it's your approach that needs to be rethoght. That's my friendly advice.
So I'm waiting for the developers' answer.

**Comment by Havokdan** [comment]
He already answered in the second post.

**Comment by ferdnyc** [comment]
(\*sigh\* I apologize in advance to everyone _else_ following this discussion, for feeding the trolls.)

> Your advice stinks and is of no interest to me. I was talking to the developers, not you, and I don't think they hired you as an advocate to speak on their behalf.

Ah, but you _weren't_ talking to the developers, were you? You were posting to the public Issues tracker on Github, and as such your post is visible to the world and open for public comment. **You** don't get to decide that, so it's best to keep it in mind and act accordingly. If you'd like to talk privately with the developers, you can see if they'd be interested in passing on their email addresses or other private contact info. Otherwise, you're here, and while you don't have to read or respond to my comments, you can't tell me not to leave them. 

But I most certainly do not speak on anyone else's behalf, my opinions and views are purely my own.

> And for argument's sake I'm not ordering anything, I'm taking an interest in when the problems will be fixed.

Your OP:

> > It's a great shame for you and you must fix these as soon as possible.

> > You know, before developing new fancy features like swarm discoveries you must first finish the basic functions, which these defects definitely describe. You must feel big shame for these defects and fix them immediately.

...Try again.

> Your approach is slavish mumble "who am I to express any discontent and demand anything from the great developers who have worked so much to bring us this piece of software for nothing?" and you want everyone else to think like that. 

Well... _yes_! I absolutely don't have a right to **demand** anything at all from the developers. Nor would I. I don't really _care_ how anyone else **thinks**, but I certainly believe that there are better and worse approaches to interaction between users and developers.

Look, I report [plenty of issues](https://github.com/BiglySoftware/BiglyBT/issues?utf8=%E2%9C%93&q=is%3Aissue+author%3Aferdnyc+). And here's the crazy thing, _all_ of mine have been addressed or are in the process of being addressed, several in the very next beta release.

Being respectful and undemanding doesn't mean pretending the software is perfect or feeling that it has to be accepted just the way it is. It simply means that if I encounter a problem, [I furnish as much detail as possible](https://github.com/BiglySoftware/BiglyBT/issues/490) so that the developers can reproduce the bug and address it. If I simply feel that something could be better,  [I _suggest_ an improvement](https://github.com/BiglySoftware/BiglyBT/issues/544) and make my case for why I think it's valuable. Generally, the developers agree even when they probably shouldn't, which is why BiglyBT now has like 7000 configuration options, some of which were basically added just for me. :laughing: (And I'm sure plenty of other users can say the same. I am not special.)

But what I _don't_ do is insult the developers' priorities, tell them they should feel _shame_, pressure them to address my concerns, or demand they commit to a timeframe for doing so. You did **all** of those things, right out of the gate. Nice to meet you, too!

> First, the software being free doesn't cancel the developers' responsibility for it's quality 

I never said "free", I said "open-source". And it does, actually, absolve them of _responsibility_ for... well, anything. It's right there in the GNU General Public License that BiglyBT is distributed under:

> BECAUSE THE PROGRAM IS LICENSED FREE OF CHARGE, THERE IS NO WARRANTY
FOR THE PROGRAM, TO THE EXTENT PERMITTED BY APPLICABLE LAW.  EXCEPT WHEN
OTHERWISE STATED IN WRITING THE COPYRIGHT HOLDERS AND/OR OTHER PARTIES
PROVIDE THE PROGRAM "AS IS" WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESSED
OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.  THE ENTIRE RISK AS
TO THE QUALITY AND PERFORMANCE OF THE PROGRAM IS WITH YOU.  SHOULD THE
PROGRAM PROVE DEFECTIVE, YOU ASSUME THE COST OF ALL NECESSARY SERVICING,
REPAIR OR CORRECTION.

That the developers _choose_ to maintain their software and support its users is their choice, **not** their responsibility.

> (and doesn't cancel their earning money for it). 

Immaterial. The developers' sources of income is not relevant. YOU did not pay for BiglyBT, or if you did then I'm sorry to tell you that you were ripped off, and neither Parg nor Tuxpaper saw any of that money. Regardless, there is no financial arrangement between you and the developers that would entitle you to any particular level of support.

As I've said, the software is open-source, which ultimately means "feel free to fix it your damn self". Oh, and see this?

![image](https://user-images.githubusercontent.com/538020/43203956-9af9cafc-8fed-11e8-8b03-6a9bd77347a0.png)

What that basically says is, "I have". (It was like one line of code and most _certainly_ does not make me one of the BiglyBT developers, but it does mean I won't be told to shut up.)

> Second, for me the answer to your question follows.

I asked you no questions. You don't get to imagine a question so that you can answer it. What even is that, some sort of Socratic Strawman?

> As for you, you're a spiritual slave and you're pathetic in your self-treatment, 

Well, you've definitely got me pegged.

> So I'm waiting for the developers' answer.

You do that.

**Comment by ferdnyc** [comment]
> (It was like one line of code and most certainly does not make me one of the BiglyBT developers, but it does mean I won't be told to shut up.)

...Not by the OP, anyway. If Parg or any of the other devs want me to can it, that's a different story. But I think I've said my piece, at this point.

**Comment by Vpstr** [comment]
To developers:
So, what do you say? Will you work on these problems soon?
