### ISSUE TITLE
BiglyBT acting like a a virus

### ISSUE THREAD

**Issue by biglyuyser** [BiglySoftware/BiglyBT#554]
Any posts or screenshots displaying torrent names, search results, subscription names, will be removed without notification, unless they are linux distros.

For bugs, please include the "System" section of the Help->About window, or if you don't have access to the window, include:
* OS and version
* BiglyBT Version Number
* For *nix: Desktop Environment

Erase all this text before submitting the issue :)

**Comment by biglyuyser** [comment]
OS window 7

I cannot find my biglyBT version, it will not open up as a window, but it was the latest download (again!)

Twice now I have had to uninstall and reinstall bigly BT after it decided (for no reason I can fathom, it had been working find for years) to run in the background (but using no CPU, but is using 423,000 K of memory). If I try to end process it says access denied, and if I tell it to open it does not. So the only way I can turn it off is to shut down the computer.

The last few times I did this it still did not open up properly, so I have no idea what (if anything) it is doing.

What is happening?

**Comment by ferdnyc** [comment]
I have no idea what's going on with BiglyBT in your setup, but presumably there's something in your configuration that makes it unhappy. I'm not _particularly_ familiar with the Windows version, though I've been using it (in various incarnations) on Linux for over 10 years. But when you uninstall and reinstall, it doesn't completely wipe out your settings, does it?

I'd suggest removing the _entire_ directory (this is only my best guess of the location) `C:\Users\<username>\AppData\Roaming\BiglyBT`. (Or move the whole thing somewhere else, like `C:\Users\<username>\Documents\`, if you want to keep it around as a backup.) Then start BiglyBT and let it create a new configuration from scratch. You don't need to reinstall, because there's nothing that gets modified in BiglyBT after install _except_ what's in that location, unless it's updating itself.

The access denied thing is strange, but then again Windows is strange, so I won't speculate on that. That the application won't open from the task manager is **not** strange, since as you say it's running but not visible ­— Windows can only bring up a running application if it has a window to bring up, and your BiglyBT in that state doesn't. The "frontend" of BiglyBT (the part that displays the application window and lets you interact with it) is somewhat separate from the backend part that handles the actual BitTorrent side of things (communication, file management on disk, etc.) and it's possible for the frontend to crash while the backend is still running. _Possible_, but that's not a normal situation, and should be preventable if we can eliminate whatever's causing it. That "whatever" is almost certainly something in your configuration.

With BiglyBT not running, even in the background (restart if you have to), remove/move that settings directory I mentioned. Then, launch the program (it should come right up no problem), and you can try adding some torrents and see how it goes. BiglyBT isn't a virus, but it **is** a Java application and those are not known for being light on system resources. BiglyBT's memory usage, in particular, is _very_ dependent on its settings. (My copy, running since yesterday, is currently using 850MB of RAM. But, I can actually see the application window and it's got a bunch of stuff going on, so that's not so bad. It's a third of what Firefox is using, anyway.) So, if you change any settings, keep an eye on whether it develops any problems — if it does, change them back. :grin: 

You can set up automatic configuration backups in the Options> Backup & Restore, which can be helpful it does get into a state where it won't open, as you can manually replace your non-working configuration with the most recent backup from before it stopped working. Also, be wary of what plugins you install, if any. There are some that can really chew up system resources.

**Comment by ViperCode7** [comment]
If you added very large torrents you'll have to give it time to make room for all the files on the HDD and to sort its pieces. The same behaviour it exhibits if having multiple (> 20) torrents with average-large files and trying to stop them. On normal torrents with small files it will stop them within a few moments, but on these large torrents it will take its time and continue to display "stopping..." until it's done. I can only associate this behaviour with BiglyBT running in the background, it will do the same thing, trying to stop the torrents and also taking its time with them but if you let it it will eventually finish and terminate for good.

**Comment by ferdnyc** [comment]
Over in #546, this issue was tracked down to an internal Windows issue, and there's a Windows Update package now available that corrected it for at least two of the other users experiencing this issue. See the comments towards the end of #546 for details.

**Comment by gr88** [comment]
.../biglyBt/biglybt/installed/biglybt --open
This is how I get the gui to re-appear if I cannot find it.
I am using Linux, not windows.

**Comment by o0nd7ots** [comment]
@parg Can we close this also?

**Comment by parg** [comment]
Closing as nothing's going to happen here, re-open if so desired.
