### ISSUE TITLE
More basic functions holes. And a couple of questions.

### ISSUE THREAD

**Issue by Vpstr** [BiglySoftware/BiglyBT#561]
Another portion of mostly basic functions holes. I also have a couple of questions.
-if I move a downloaded file to a different place outside of the client (via Windows explorer) and then point the client to the new location via Move data files, the won't seed the file, but it says like Error - file missing. It's impossible to get rid of it in any way but restarting the client.
-the client is faking Share ratio time to time. When I add the torrents that are already downloaded, it assigns the values to Uploaded and Share ratio columns that are about the torrent's size, not zero as they should be.
-again it's messing with download folders. If when selecting a path I remove the top level folder and then change the save path, the lowest folder of the first path is attached to the second path. That's an ugly hybrid!    
-the Switch torrent file function is not working. I know this because when I try replacing the torrent file with another one (with the same hash of course) the comments (that are located in the torrent file) remain the same and so does the list of trackers. 
Also when I open another torrent file with the same hash it's not always offering to add new trackers from this file, just says the media has already been added. 
-the last active column in the library is showing wrong data. When I closed the client, almost all torrents were seeding, but when I opened it the next day and many of the torrents got queued, Last active for the torrents still seeding was not the current time, but the time I closed the client.
-some error with a huge call stack often appears in the console. It says "Image DPI adjustment failed: Argument cannot be zero...".
-the queuing algorithm is not working as it must. I've set it to Timed rotation and since I opened the client of the 100 torrents I have only about 70 are seeding. And this picture hasn't changed since then (each torrent's status remains unchanged), although the 10 minutes countdown in the seeding rank column had expired long ago. 
-after assigning a category to a torrent it won't display in this category's list at once (in My torrents section). The amount label updates, but when I switch to that list, I often see only the old torrents.   
And the questions. 
-previously the queuing algorithm was set to Seed:peer ratio. One of the trackers that I'm downloading from doesn't support Scrape requests. It's written in the Vuze wiki that "Without scraping, Azureus would never know which torrents have no seeds and require assistance". I assume then that a torrent from this tracker could never be set for seeding with this queuing algorithm, because it calculates this ratio from scraping results that it can't get. Is that correct?
-when I install the mlDHT plugin, does it work together with the built-in DHT or does it replace it? And if the built-in DHT includes only the peers with Azureus derivatives, then why does it find the non-Azureus peers?
-what is this DNS helper or something that the client is often messaging about and why is it trying to install anything without alerting me first?
It's the second message that I'm writing about mess in basic functions and after everything said I have to acknowledge that the client is just poorly developed (concerning that all this hasn't been fixed in many years of development). Some amount of bugs is inevitable in absence of serious software testing, but that amount of holes in basic functions is beyond the pale. 
Now I'm asking the developers the same question that I asked before. What are you gonna do with this? Are you gonna fix these (and problems from the previous issue) anytime soon?

About window:
![bbt](https://user-images.githubusercontent.com/41571113/43582487-282800c4-964c-11e8-9f63-ea3d046af424.png)
I don't know why it's showing amd64, cause I have Intel 64bit.

**Comment by parg** [comment]
It isn't 'faking' share ratio, it is following the settings under 

Tools->Options->Queue->Seeding: Consider 'add for seeding' downloads to have downloaded this number of copies: 1

**Comment by ferdnyc** [comment]
> -the last active column in the library is showing wrong data. When I closed the client, almost all torrents were seeding, but when I opened it the next day and many of the torrents got queued, Last active for the torrents still seeding was not the current time, but the time I closed the client.

'Last Active' is a downloading stat, roughly equivalent to the start of the 'OnlyCDing4' stat. (Meaning, assuming uninterrupted operation since downloading finished, the 'Last Active' tooltip time ("NmNNs ago") should be nearly equal to the 'OnlyCDing4' time.

You probably want 'Up Idle', which shows how long it's been since peers were last connected to the client as a seed.



> -after assigning a category to a torrent it won't display in this category's list at once (in My torrents section). The amount label updates, but when I switch to that list, I often see only the old torrents.

Don't use Catgories. They're outdated. (I really don't understand why they're even still available in the interface.) Use their superior replacement, Tags. 

(If you have the same problem with tags, then that's something worth looking into. But I haven't noticed any such issues with Tags, personally.)



> -the client is faking Share ratio time to time. When I add the torrents that are already downloaded, it assigns the values to Uploaded and Share ratio columns that are about the torrent's size, not zero as they should be.

Share ratio is a _ratio_, meaning a **proportion** of upload:download. It's tweaked a little bit, of course, because the ratio is actually computed based on the size of the torrent itself. But the intent of Share Ratio is to monitor whether the client is "doing its part" by uploading data to the swarm. It's expected that clients will upload _at least_ as much as they download, meaning that they'll seed until they have a share ratio > 1.0.

By default, if you add a torrent that does **not** have to download anything, the share ratio _starts_ at 1, meaning you've already uploaded as much as you've downloaded — since you've downloaded 0 bytes, this is correct. Effectively, every byte uploaded is "extra" credit beyond the 1.0 share-ratio expectation.

Parg already told you the option you can enable to _fake_ a download "debt" of 1 on added torrents, which will subtract bytes equal to the size of the torrent from the starting share ratio, causing it to become 0.

**Comment by Vpstr** [comment]
In addition to everything I wrote I can't choose the category when adding the torrent, only the tags, which is stupid, because category is the primary unit of classification, while tags are just for assistance.
By the way, developers, don't you think that this whorish advocacy garbage above justifies those defects or cancels your responsibility for them - they are still there and must be fixed.

**Comment by ferdnyc** [comment]
> this whorish advocacy garbage above

You are _such_ a pleasant person, I can't  imagine why your reports are being ignored. I suppose I'll do the same, from now on.

**Comment by tryfon** [comment]
LOL, this conversation is hilarious! Vpstr is probably the current incarnation of Darth Vader.
