### ISSUE TITLE
App keeps crashing!

### ISSUE THREAD

**Issue by Xemnarth** [BiglySoftware/BiglyBT#571]
Using latest beta on Win10
Even when I have no torrents active, the program crashes. It didn't happen this much in the past. I have over 2000 torrents in my library. I can't use BiglyBT with this issue.

**Comment by sklm** [comment]
Confirming constant hang-ups on Ubuntu and Windows 10. Reverted to 1.6.0.0 for now.

**Comment by ferdnyc** [comment]
Dup of #568? (@Xemnarth didn't specify exactly what form "crashing" takes, so I'm not sure.)

**Comment by parg** [comment]
Please try beta B04 - there is a fix for a deadlock issue in it

**Comment by ferdnyc** [comment]
This is now fixed for real in 1.6.0.1_B06. (See #568)

**Comment by ackerthehacker2** [comment]
I think the deadlock is still in B07 .... everything just grinds to a halt with app on Mac Mojave.  I force quit and then restart and all is OK.

**Comment by ferdnyc** [comment]
@ackerthehacker2  - "grinds to a halt" doesn't _sound_ like the same thing. When the deadlock was happening, it caused a **complete** and total application freeze — the interface was utterly dead, you could not interact with it and the window didn't even redraw. 

Unless you're seeing the same thing, it's not the deadlock. You may be experiencing some other issue. (I haven't personally seen _any_ sign of the deadlock since \_B06, including in \_B07.)

**Comment by ferdnyc** [comment]
(I mean, I may be misinterpreting, but to me when I hear "grinds to a halt" I think of something that gets progressively slower and slower, with operations taking more and more time to complete, possibly even several seconds between mouseclicks...

You know, like Windows XP if you hadn't rebooted in a few days. :laughing: 

The deadlock didn't "grind" anywhere, it was like slamming into a wall. Everything was working fine, working fine, working normally... and then **\*BAM!\*** it's dead.)

**Comment by ackerthehacker2** [comment]
Since I am not on the computer constantly, it looks like a slam into the wall for me …  works great ..I walk away for a few hrs and when I come back — nothing  going on, all more transfers halted and the application says its not responding

**Comment by ferdnyc** [comment]
Yeah, thats sounds like exactly my experience when I was seeing deadlocks.

Well, one thing you can do is, next time it's frozen, follow the debug-log-gathering instructions @parg provided [over on my bug](https://github.com/BiglySoftware/BiglyBT/issues/568#issuecomment-413981757) and post the resulting logs. Actually, I'll just copy them here...

> Just in case it works can you try cranking up a browser when it is deadlocked and entering
>
> http://127.0.0.1:45100/setinfo?name=AZMSG&value=AZMSG;0;config;log-diags;;
> 
> (make sure you include the double ;; at the end of that)
> 
> If this 'page' loads then upload the debug_1.log / debug_2.log as this should contain some stack traces that might pinpoint the issue

I'll just add two things:

# Tho he doesn't mention it, I'm sure it makes things easier for him if you **delete** the debug log files first, while BiglyBT is shut down, and _then_ start it and wait for a freeze. That'll mean that the files contain the minimum amount of extra noise, that makes the issue harder to spot.

# Since I was skimming too fast and didn't 100% correctly read that info the first time, what you want to do is just visit that URL while BiglyBT is frozen to trigger the status-dump into the debug logs. It won't return anything useful in the web browser (I just got this:) 
![image](https://user-images.githubusercontent.com/538020/44958362-2f3e7e00-aead-11e8-8151-0d953210e911.png)
...but once you've done that, then the `debug_1.log` and/or `debug_2.log` files contain the info needed to debug the freezes, so you can kill the app and post them to this issue. (Github allows direct upload of `.log` format files, so you can just drop them right into a comment.)
