### ISSUE TITLE
Client ID selection

### ISSUE THREAD

**Issue by ssjvash** [BiglySoftware/BiglyBT#579]
It seems that BiglyBT has a built in option that allows the program to report different client IDs.  Apparently, it can appear as different BiglyBT versions or even Vuze.  Certain private torrent communities are banning the use altogether because of their fear of spoofed clients.  This feature can be used to allow for easier client ID hacking.  I'd like use BiglyBT as my primary (read only) torrent software if possible, so I'm wondering if this is a temporary thing or a long term feature intending to stay.

**Comment by parg** [comment]
It is a migration aid and may be removed in the future.

**Comment by jaymzjulian** [comment]
Flip side of this: currently private trackers i'm on disallow biglybt still because they didn't update their client list, and don't recognize it as an azureus derivative, so I'd be sad if it was removed yet

**Comment by ssjvash** [comment]
It's kind of cyclical from what I've seen jay.  I'm part of 2 communities that have banned BiglyBT specifically because of that.  The feature that can help get around it is why it is looked down on in the first place.  Either way, thanks for the heads up parg.

**Comment by psychic717** [comment]
I'm having the same issue with some trackers
They ban BiglyBT/Vuze outright just because it's possible to do this. I don't want to use another client, but at the same time a lot of trackers ban BiglyBT automatically because of this ability, so it's inconvenient to keep using it as my client.

Please consider removing this soon so BiglyBt can be seen as a real option for private trackers.
Thanks.

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
its solved by version 2.0.0
