### ISSUE TITLE
BiglyBT and BiglyBT for Android reporting same ID

### ISSUE THREAD

**Issue by Dem002** [BiglySoftware/BiglyBT#580]
BiglyBT and BiglyBT for Android are reporting as the same client and some trackers that dislike mobile clients are banning BiglyBT because of this. Could you give BiglyBT and BiglyBT for Android different IDs?

**Comment by TuxPaper** [comment]
We'll be adjusting the Android client's id in the next Android release.  See BiglySoftware/BiglyBT-Android#74 for additional information when I get to implementing it.  

What we'll probably do is change the client id to `-BI1601-A` and the desktop will remain `-BI1601-`, where 1601 is the core version being used.  We are still debating on whether to add an additional character after the `A` to specify the type of Android device.  Differentiating between chromebook, Android TV, non-battery devices and phone devices might be handy.  However, this could have privacy implications.  We don't want to be like browser's User-Agent and end up being 95% unique per user.

**Comment by proton-ab** [comment]
That won't work. Personally on AnimeBytes I will not bother whitelisting every minor release because of -A. We will continue using "-BI16" or none at all. Go read BitTorrent specifications and stop trying to invent your own. http://www.bittorrent.org/beps/bep_0020.html. All clients to this day that are widely used follow convention where - after version is random string.

**Comment by TuxPaper** [comment]
I just re-read BEP-20.  There is no definitive spec in there for client id.  The BEP lists common styles of client identification.. there's at list 10 different formats listed there.  There is no definition of an approved format. There isn't even a common byte length for client id.  There's one style that I'd call a defacto standard, but it isn't an official BEP standard, and it says nothing about requiring a different client id per device type.

If you or any other tracker needs programming help to check the 9th byte for an 'A', i'm sure myself or a dev familiar with the tracker's language can assist.

Perhaps I overlooked something, but if there a BEP, or has a BEP been proposed for specifying the device type in the client id, I'd be glad to implement that (in fact, i'd prefer it).  As I mentioned, BEP 20 doesn't say we must have a different id for the same client on different device types.  Since there isn't a BEP or even a defacto standard, we are left with the choice of making one up.  No matter what choice in client id we make, having no current BEP to give us guidance will always make our choice "wrong" by someone. :(

Changing the "-BI" part for Android will affect other trackers who whitelist (or blacklist) our client. If we are whitelisted, users of the android client would suddenly be locked out of those trackers and blame us.  If we are blacklisted, the trackers would claim we are trying to circumvent their blacklist by having multiple client ids for the same product.

We are trying to be accommodating, but it's hard to negotiate with an (IMO) "our way or the highway" attitude.   We want a solution that give you the ability to blacklist or whitelist based on device type, without annoying other trackers with more work (ie.  We shouldn't force other trackers to change their code for a feature request another tracker has made)

**Comment by mighelch** [comment]
Any development here?
> We want a solution that give you the ability to blacklist or whitelist based on device type, without annoying other trackers with more work
I'm not aware of a private tracker that allows biglyBT (actually I'm, but they'll go along with whatever solution you'll came up with). So far the only problem with biglyBT is it's ID.

**Comment by TuxPaper** [comment]
Prepping a new Android client with this change soon.. should be live next week, baring any unrelated bugs

**Comment by BiglyBT** [comment]
Latest android version (1.1.9) now has an 'A' in the 9th position (array position 8)
For example, -BI5701-A...........
