### ISSUE TITLE
Menu command "Change data directory" unavailable for a single torrent

### ISSUE THREAD

**Issue by sklm** [BiglySoftware/BiglyBT#587]
Kubuntu 18.04.1, KDE, GTK 3.
Version 1.6.0.1_B07.

It seems that this option doesn't appear on the context menu for a single torrent. However, it does appear if several torrents are selected.

Apparently, it is conditioned on the torrent being in the "hasSelection" state. I can't figure out how to put a single torrent in such state, though. Simply clicking on a torrent does not "select" it, and tricks like Ctrl+click or Shift+click don't seem to work either. So basically, I see no way of enabling and using "Change data directory" option on a single torrent.

**Comment by ferdnyc** [comment]
True, that does seem to be a multi-select-only option. (Not sure why, TBH I'd never seen it before, since I rarely open the context menu with multiple torrents selected.) 

However, Advanced > Files > Move Data Files... is always there, for one torrent or many.

**Comment by ferdnyc** [comment]
Change Data Directory also doesn't seem to appear if you have any seeding torrents included in the selection. (Or maybe it's active torrents, both of my seeding torrents are currently uploading.) whereas Advanced > Files > Move Data Files... can always be selected.

**Comment by parg** [comment]
'Change Data Directory' is a recover option that appears when a torrent goes has some of its files missing - AFAIK it was added to give a quick way to fix things up if, say, someone went and moved the torrent's data files from outside BiglyBT.

As ferdnyc says, there is 'move data files...' within BiglyBT if you want to manage things from the app and also 'Search for existing data files...' if you want to look for files - also you can fix up individual files by right-clicking in FilesView and selecting rename/retarget.

**Comment by sklm** [comment]
>  a recover option that appears when a torrent goes has some of its files missing
Indeed it does, thank you. Although, I think the behavior is somewhat inconsistent, e.g.
single torrent with missing file - the option is available;
single torrent with all files intact - not available;
multi-torrent selection - always available, regardless of whether the files are missing or not.
Buy your logic, if I select a couple of perfectly fine torrents with all physical files intact, then such option should not appear as there is nothing to "fix" about these torrents' files. However, this is not the case and the option is always there for multi-selection.

**Comment by ferdnyc** [comment]
> Although, I think the behavior is somewhat inconsistent,

Yeah, it looks like the logic for when the option should be shown failed to take into account multiple-selection, and manages to get confused by it. Good thing they have beta testers to find this stuff!

**Comment by parg** [comment]
It is because of this:

			/**
			 * Only perform a test on disk if:
			 *    1) We are currently set to allow the "Change Data Directory" option, and
			 *    2) We've only got one item selected - otherwise, we may potentially end up checking massive
			 *       amounts of files across multiple torrents before we generate a menu.
			 */

For a single selection it goes ahead and checks to see if files are actually missing. For multi-selection is skips the existence checks (as performance can be slow and hence the menu doesn't appear for a potentially long time) and just bases the menu visibility on all downloads selected being stopped/queued/error

**Comment by sklm** [comment]
Thank you for looking into this. So the current behavior is expected and by design, isn't it? Then I think I can close this one.

**Comment by ferdnyc** [comment]
That wasn't my interpretation, from the source comment / logic description @parg posted.

AIUI:
* The code was _supposed_ to perform a disk check, iff those two conditions are met
* It would then display the menu option if the disk check indicated it was needed
* But it would _NOT ever display, otherwise._

It's that last part that didn't quite go right in the code.

So, right now, if there are multiple items selected, a disk check is skipped which would **hide** the menu option, when the logic was supposed to require a certain result from that disk check as a necessary prerequisite to **_show_** the menu option. (If I'm indeed interpreting that correctly?)

IOW, it's slightly buggy, but not in a super impactful way since we can still simply just... **not** select it. :laughing:

Though, from the perspective of your Issue here, it's pretty clear now that we're **NOT** meant to _use_ Change Data Directory for "casual" file relocation (and AIUI we shouldn't even be seeing that option, and presumably won't be once this bug is fixed)... to relocate files, Advanced > Files > Move Data Files... is the right tool. 

Which I suppose is indeed the answer to your question, and therefore the solution to issue #587. :grin:

**Comment by sklm** [comment]
> The code was supposed to perform a disk check, iff those two conditions are met
> It would then display the menu option if the disk check indicated it was needed
> But it would NOT ever display, otherwise.

My interpretation of the current design is slightly different. All other things equal, like e.g. stopped status etc, this is how I view the difference between single and multiple selection scenarios.
- when a single torrent selected, check that file(s) exist then either show the menu (if files are missing) or hide it (if files are ok);
- when multiple torrents selected, skip the files check and just show the menu anyway, just in case. I think it's a reasonable compromise, to avoid heavy filesystem checks.
