### ISSUE TITLE
Custom tag settings are not saved

### ISSUE THREAD

**Issue by cengizhan** [BiglySoftware/BiglyBT#64]
I have created tags for torrens and set upload and download settings for them. if you restart biglybt, you will see that download and upload settings are all back to 0. 

also if the progam crashes or a power loss occurs, user tags are all lost. you have to create them again. very annoying
------------------------------
Java 1.8.0_102 (64 bit)
  Oracle Corporation
c:\program files\java\jre1.8.0_102

SWT v4757, win32
Windows 10 v10.0, amd64 (64 bit)
B1.0.2.1_B01/4 az3

**Comment by parg** [comment]
Very odd, I don't see that behaviour over restart and I have been starting and stopping BiglyBT for years!

There is a backup+restore feature that can help with data loss if a crash occurs - see Tools->Options->Backup & Restore

**Comment by cengizhan** [comment]
what do you mean for years? you mean vuze? i have tested this in 3 different computers. all of them have same behaviour. restore doesnt restore upload/download speed limits, because they are not saved.

**Comment by parg** [comment]
Yes - I developed Azureus/Vuze and now BiglyBT - I created the Tag feature as well and I can assure you that upload/download limits applied to Tags are persisted. They are stored in a file named 'tag.config' that is stored in your BiglyBT configuration folder (%APPDATA%\BiglyBT)

Can you check that the file exists in that folder and isn't being deleted by something?

**Comment by cengizhan** [comment]
the tags are there after restart. but only download/upload settings are lost.

**Comment by ferdnyc** [comment]
I was having  a problem with Vuze (5.7.5.1_B10) losing my tags when it crashed, recently, because I had a power-supply issue that was completely freezing my system up at random times.

_Normally_ killing or even crashing the software is fine, and doesn't break tags, but for whatever reason these hangs were more often than not causing Vuze come up missing all of my tag definitions on its next launch. I suspect it's something like a particular config file being open for writing at the time of the hang, and getting left in a corrupted state, since the hangs prevented even a proper closing/flushing of the filesystem journal. (My `$HOME/.zsh_history` would similarly have corrupted lines at the bottom, when the system came back up after a freeze, which I'd have to manually trim off to keep zsh from complaining.)

While this was going on, I ended up configuring Vuze to do _daily_ config backups, and I'd just restore the most recent one whenever the tags got corrupted. The real fix, in the end, was to just sort out the machine's hardware issues so the system hangs went away. 

But, point is, there does appear to be a code path that can cause the tags config to be left in a bad state, if it's interrupted at exactly the wrong time. That should be rare under normal circumstances — actually, under _normal_ circumstances it should never be encountered — but it's lurking there somewhere. Wish I had more detail for you, but honestly I'll be happy if I never encounter that issue again so I'm afraid this is everything I know.

### Wandering off-topic...

Also, parg, holy crap! How am I just finding out about BiglyBT _today_? We've spent the last like 6 months over at the Vuze forums wandering the place like zombies, moaning "Where's parg? Why did he leave us? How will we go on?" (Your absence was very keenly felt, is my point.) Somehow BiglyBT was _never **once**_ mentioned there, that I saw, until an offhand mention today led me here. (Thank you Havokdan!)

Now I have to spend the evening moving my fileserver over from Vuze 5.7.5.1_B10 to the latest BiglyBT, which would feel like a chore if I wasn't so excited about the prospect of finally saying goodbye to Vuze. The client is dead, long live the client! Onward to BiglyBT!

**Comment by parg** [comment]
I think there's a code path with all our config files, not just tags ;)  Spent quite a long time messing with writing to a temporary file, syncing it, deleting old, moving new etc.etc. Somewhere there's dragons we can't tame.

Wandering off-topic... 

Sorry about that... The owners of Vuze decided that our services were no longer required but we departed on good terms and it would have been rude to start hitting up the forums with info about BiglyBT, so we just quietly did our own thing. Glad you found us :)

**Comment by cengizhan** [comment]
still can't use it on private sites. biglybt is not in their while list. is there some option for changing client id?

**Comment by parg** [comment]
Is Vuze accepted? If so, what version?

**Comment by ferdnyc** [comment]
> I think there's a code path with all our config files, not just tags ;) Spent quite a long time messing with writing to a temporary file, syncing it, deleting old, moving new etc.etc. Somewhere there's dragons we can't tame.

Which is definitely understandable, I mean it _is_ a failure condition so really there's a point where you have to just say, "things will fail during failure".

But the thing that puzzles me is, why would the tag definitions live in an actively-updating file? They're not being edited by the user, they're not being changed by the system... they _shouldn't_ be that vulnerable to corruption, seems like. Crash-based corruption is the sort of thing that you'd expect to see hitting _state_ files, not _configuration_ files. (Which is why, for instance, my `$HOME/.zsh_history` can get corrupted during a freeze... but my `$HOME/.zshrc` couldn't, unless I had the incredibly bad luck to be saving an edit at that exact moment.)

So, if the tag definitions can get wiped out by a filesystem corruption, does that imply that they're being stored in a volatile statefile, rather than a static config? And if so, can those contents be better separated in terms of what's volatile vs. what's static, to make the static config "side" less fragile?

I have to wonder, now, if this could even be a contributing factor to things like the dreaded [Tag-Tab Label Schizophrenia](https://imgur.com/8wewJjG), one of the many issues behind [my irrational anger at the very existence of tag tabs](https://imgur.com/a/B7hid).* ...It's that thing where the titles on tag tabs just randomly stop resolving, and they all change from the actual tag name to internal identifier strings like `Views.plugins.Tag.3.<number>.title`. I've been lazy and haven't gotten BiglyBT up and running locally yet, to explore whether it has the same tag-tab implementation and/or issues, but let me know if you think there's value in me opening that bug here, too.

\* – (Those are imgur links "mirrored" from a much more lengthy, desperate, wits'-end Vuze Forum rant on the topic, in order to incorporate screenshots that wouldn't display in the forum.)

**Comment by parg** [comment]
Ah, but the tag assignments are stored in the tag file - it contains all the tag state. However, if you are seeing constant updates even when downloads aren't changing assignments I would agree that is odd... As for tabs, I never use that view and the sidebar is pretty reliable :) Obviously the header names should work though, I'll take a look. Thanks

**Comment by ferdnyc** [comment]
Sorry, should've mentioned: The tag-tab issue is with the Classic view (I'm a luddite, still, though I do plan to revisit that decision once again with BiglyBT). There (at least in Vuze 5.7.5.1_B10), tabs were automatically opened for every tag with a visible filter button enabled on the My Torrents view.

**Comment by parg** [comment]
You might need to wait until the next beta of biglybt for Tags in classic view - I found a bug while playing about...

**Comment by ferdnyc** [comment]
My work here is done!
