### ISSUE TITLE
Fix Backups

### ISSUE THREAD

**Issue by 2635599** [BiglySoftware/BiglyBT#68]
i'm wondering if you have plans to make the backup in the future one single file instead of a folder full of multiple files. might want to take a look at tixati. thanks

**Comment by Xuchilbara** [comment]
Maybe give the option, but not make all the backups always one single file, because it's useful and convenient to have every different element in its own section. For example, I like having all the backup .torrent files in their original state. This way I don't need any particular program to process them.
Just my opinion.

**Comment by 2635599** [comment]
the only program that would be processing your torrent files is biglybt, backing them and everything else up in to one file won't change the torrent files or any other file in the backup.
