### ISSUE TITLE
Does java 9 support?

### ISSUE THREAD

**Issue by Havokdan** [BiglySoftware/BiglyBT#69]
Does java 9 support?I installed Java 9 here that was just released and biglybt did not open. Apareceu a seguinte mensagem:

![sem titulo](https://user-images.githubusercontent.com/6549729/30740440-56792660-9f67-11e7-9152-c59f1c16d172.png)

**Comment by parg** [comment]
BiglyBT runs on a Java 9 JVM - looks like an issue with the launcher

**Comment by TuxPaper** [comment]
I believe parg is right.  There was a newer version of the exe generator program that claims support for J9,  Can you try this exe and tell me if it works?

https://s3.amazonaws.com/biglybt-files/J9-64/BiglyBT.exe

**Comment by Havokdan** [comment]
@TuxPaper is working with this version.

![sem titulo](https://user-images.githubusercontent.com/6549729/30758487-0499ff3a-9fa9-11e7-8109-376b5f520b1d.png)

**Comment by hatewesterncivilization** [comment]
Java 9 is completely a bad due to stopping continue of outdated collectors types like a the concurrent collector e.g. -XX:+UseConcMarkSweepGC + -XX:+UseParNewGC parallel collector type that working jointly with an concurrent collector. I'm didn't find yet a way to serve beatiful latency e.g. finest client response including UI except of this discontining concurrent collector. G1 collector is pretty lacking for that purposes or maybe I still didn't find examples in net, but was searching very intensively. Maybe parg or TuxPaper having what we need?

Also Java 9 cause some errors like a broken torrents in the list when I am trying work with Java 9.

Havokdan, you are need add an system variable to the system properties and all will be work easily.

http://prntscr.com/goopox

**Comment by TuxPaper** [comment]
I've updated the installers with the new BiglyBT.exe
