### ISSUE TITLE
Unable to connect to remote instance

### ISSUE THREAD

**Issue by mortefer** [BiglySoftware/BiglyBT#734]
Phone OS Android 9.0
Phone BilyBT version 1.1.9
Remote OS Android TV 8.0 running on Nvidia shield
Remote BiglyBT version 1.1.9

with latest update (1.1.9) I cannot connect to remote instance of Bigly running on my Nvidia Shield.
However web interface can be opened with absolutely no problem - it's just the Bigly client installed on phone that gives me "Unable to connect to your remote client. If does not appear to be running".

Checked the settings:remote access is enabled (tried disabling and enabling it with no avail).
Both devices were rebooted - same result.

Before the update everything was working just fine.

**Comment by TuxPaper** [comment]
hmm, nothing apparent has changed since the last version for remote access, but a few libraries were upgraded so something new could be affecting you.  Thanks for mentioning the webui is working, that's helpful.  A few questions:

1) When you were on your phone and added the remote nVidia Shield, did you use the QR code, or enter it manually?

2) Do you use a username/pw?

3) Check to see if your phone is on the same wifi.  I've been still on the cellphone network a few times and swore I broke BiglyBT only to realize I'm stupid  :P

4) Double check the ip address and port on the nVidea Sheild's biglybt (Settings->Remote Access) and compare them to the Remote Connection Settings on the phone.  Also make sure the phone's settings doesn't have "https" enabled.

5) You can safely remove the remote profile from the phone and add it back in again (through QR or manually), and that might clean things up.  (Click and hold on the "Available Clients" row and it should popup a menu that has "Remote Profile" on it)

6) Unlikely to help, but you could try rebooting your router.  You will have to restart BiglyBT on the nVidia (either restart the service or reboot the device).  Really only a 5% chance this would help though.

Since the web ui is working, it's safe to bet the nVidia Shield's BiglyBT is working properly, and the problem is with the one on the phone, so if you are fooling around, that would be the one to fool with.

You could also play around with setting/changing the username/pw and see how that affects the webui and remote app.  You might discover something that would help me diagnose it.

**Comment by TuxPaper** [comment]
Additional and more advanced thought:

If you use your phone's BiglyBT only to remote access and you don't do torrenting with it, you can try uninstalling it and installing 1.1.8 (https://github.com/BiglySoftware/BiglyBT-Android/releases/tag/v1.1.8 ) to see if that connects.  Don't uninstall BiglyBT from your nVidia, that would have a good chance of removing your download list, settings, etc.

**Comment by TuxPaper** [comment]
Android 9 has some changes to DNS access, so if you were trying to connect via a DNS name instead of an ip address, there's a chance I have a bug there.

**Comment by TuxPaper** [comment]
Good news! I found the issue and it's related to Android 9 (Pie).  Bad news is there is no workaround (other than using webui) you can do in the current BiglyBT version.  I'll be releasing a fix to Google Play later today, although it takes up to 6 hours after that before everyone gets the update, so be patient.

**Comment by mortefer** [comment]
Waiting patiently. Will report back once update arrives.

**Comment by mortefer** [comment]
Works as a charm! Thanks!
