### ISSUE TITLE
Block seeding to clients who sell their upload bandwidth for coins

### ISSUE THREAD

**Issue by TuxPaper** [BiglySoftware/BiglyBT#786]
[BTT](https://www.bittorrent.com/btt/btt-docs/BitTorrent_Token_Whitepaper.pdf) isn't live yet, but in anticipation of clients selling their bandwidth for a price, this issue has been created to poll how much interest there is in a feature to ban any clients that report to your BiglyBT client that they are selling their torrent pieces for a price.

**Comment by DeoW** [comment]
I would be very uncomfortable uploading a torrent freely to someone who is going to expect to be paid to do the same later. Thus full agreement with TuxPaper's proposition.
As I see it, bandwidth costs should be the only costs for downloading and uploading (and giving the client devs an occasional cup of coffee to support their java habit). 
I think that if bittorrenting is commercialised, it will be more than just a body blow, it will be a death knell for the BT universe as we know it, in less than a decade.
Much will depend on the commercial model used (if this comes to pass). If payment is restricted to share-ratios greater than at least one, the model will allow people to "buy" rare torrents, which seems a reasonable concept.

**Comment by WPFilmmaker** [comment]
@TuxPaper Is it know whether users will be able to turn BTT on and off or whether it won't be possible to stop using it? Because if it would be an opt-in/out kinda thing I think it would make sense to block users using BBT rather than the software itself, Why? 

Because what if  a popular client (utorrent or transmission) decide to enable BTT and Bigly blocks such clients? You would lose 1/4 or more of seeders...so I don't know how much it would be viable. Having said that I am in favor of blocking this coin.

**Comment by TuxPaper** [comment]
@WPFilmmaker According to the whitepaper, clients using BTT will tell other clients how much their data will cost.  So, the idea would be to block any peers announcing any price for their data.  If they announce their price is 0, or don't announce a price (thus free), then they wouldn't be blocked.

The whitepaper also says these clients will send prices to trackers during announce, so I have no doubt any tracker not liking the idea will block those peers from ever being listed as available to connect to.
