### ISSUE TITLE
Unable to view right-click menu on Qubes R4.0 when BiglyBT is maximized

### ISSUE THREAD

**Issue by ghost** [BiglySoftware/BiglyBT#799]
* Qubes R4.0
* 1.7.0.1_B36
* KDE

When I right click on a torrent while BiglyBT is maximized, the menu appears for a split-second and vanishes. If BiglyBT isn't maximized, I am able to see the menu fine.

**Comment by Eric678** [comment]
Thought I should update this issue: It is still there in R4.1 and R4.2 Qubes (dom0 X).  Never run maximized, happens running normal window.  Feels like a race condition - if the VM has not been used for a long while, then lots is swapped and it takes a while to pop up the menu - then it works, otherwise flashes up then dismisses. In R4.0 one could put another window on top of Bigly , and that would cause enough of a delay to have it work.  In R4.1 the only way to get the menu was to hit F1, wait for the home page to start loading in a browser, then it works. Suspect bigly started getting a lot of hits... they switched it to github.  Never seen this on any other application.

**Comment by parg** [comment]
What if you either double-right-click to show the menu or change

Options->Interface->Tables: Show Fancy Menu (Requires Restart)

to false?

Another option is to enable

Options->Interface->Display: Show the Torrents menu

and use the main menu "Torrent" item instead of right-click.

**Comment by Eric678** [comment]
Double right click - if really fast you get 1 popup & dismiss, otherwise 2.
Problem is with fancy menu only.
Both the other methods of accessing the old menu work OK.

**Comment by parg** [comment]
I guess Qubes doesn't do fancy.
