### ISSUE TITLE
More Encryption?

### ISSUE THREAD

**Issue by mwsasser** [BiglySoftware/BiglyBT#8]
Hi guys, this isn't so much a bug as it's a feature request.  Can you add some newer encryption methods that are better than RC4?

**Comment by parg** [comment]
The message-stream encryption (https://en.wikipedia.org/wiki/BitTorrent_protocol_encryption, https://wiki.biglybt.com/w/Message_Stream_Encryption) is more about obfuscation than confidentiality which is why RC4 was deemed sufficient. The I2P support within BiglyBT provides better protection, see https://wiki.biglybt.com/w/I2PHelper_HowTo

**Comment by TuxPaper** [comment]
Newer encryption would also require other clients to implement the same encryption method.   Closing issue, because as parg mentioned, the goal of RC4 is to prevent throttling ISP’s from shaping your traffic, so the likelihood of getting the major torrent clients on-board would be pretty high, imo.

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
what happened with AES codeparts?
