### ISSUE TITLE
Remove Vuze from Meta Search template list

### ISSUE THREAD

**Issue by kwloafman** [BiglySoftware/BiglyBT#80]
Please remove Vuze from the template list, or at least make it optional.  Having a mandatory template feels like someone is watching our searches.

...Thanks! 

Java 1.8.0_144 (64 bit)
  Oracle Corporation
/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home

SWT v4528, cocoa
Mac OS X v10.13, x86_64 (64 bit)
B1.0.2.0/4 az3

**Comment by parg** [comment]
You can remove the Vuze search by doing a search to get the results screen and then right-clicking on 'Vuze' and selecting 'remove' - it won't be used in subsequent searches.

However, if you hit the 'Add/Edit Templates/ button you will still see Vuze there as currently that is fixed in that dialog.

**Comment by kwloafman** [comment]
Thanks!  Did not know about the right-click.

**Comment by Benu-Athanasia** [comment]
Any idea how to put the Vuze template back? Add/remove won't let me put it back.

**Comment by o0nd7ots** [comment]
@parg Can we close this please?

**Comment by parg** [comment]
Closing as nothing's going to happen here, re-open if so desired.
