### ISSUE TITLE
Display of Torrent Seeds/Peers does not agree with Sources Tab

### ISSUE THREAD

**Issue by NaPurHab** [BiglySoftware/BiglyBT#836]
This is a problem that has been around a very long time. I have seen this in Vuze for years. And thought I would bring it up.

In the Image below, the selected Torrent shows 0 Seeds and 1 Peer.  But in the Sources view at the bottom, the DHT and connected trackers all show 1 Seed, and more than the 1 shown at the top in the Leecher column for each connected tracker.

While the image doesn't show it, the 2nd torrent which shows 0 seeds and 4 peers, has 0 seeds and 8 peers in the trackers view.

Not something I am in a hurry to see fixed. But please put it on the list of things to do.

* Windows 10 1809
* BiglyBT Version 1.8.0.1_B02

![biglybt display problem seeds-peers png](https://user-images.githubusercontent.com/37715552/51711150-351e3280-1ff9-11e9-9440-6548d58fc9c5.jpg)

**Comment by parg** [comment]
For a running download the seed/peer columns show the number of *connected* seeds and peers. It should also show the number potentially available using the 'of <n>' suffix.

The code shows a lot of tinkering, I'll make a small change to grab the 'best' scrape response to see how that improves things.

**Comment by NaPurHab** [comment]
Here is an example of a larger selection of the issue. All the ones showing 0 Seeds, like the selected item in the image, have a number of seeds.  And as you say, some have the 'of' suffix on them, but a lot don't.  Image is from the Library View.  You can see that it show this issue with both the Seeds and the Peers. So as you say it shows 'tinkering', good time to tidy up the code.

![biglybt display problem seeds-peers 2 png](https://user-images.githubusercontent.com/37715552/51857718-f5a95c00-2300-11e9-8bb4-a01629a322c6.jpg)

**Comment by parg** [comment]
Beta B05 is out - please see if that improves things at all...

**Comment by parg** [comment]
What's wrong with that view?

**Comment by NaPurHab** [comment]
![biglybt display problem seeds-peers 4](https://user-images.githubusercontent.com/37715552/51866239-7161d380-2316-11e9-9229-cf342425ac49.png)

I Cropped the previous image, and added an Outline to the problem areas.

**Comment by parg** [comment]
If they don't have a valid scrape response then that's what you get - those are the connected seeds/peers

**Comment by parg** [comment]
the entries either show as

<number>    - this is the number of connected seeds or leechers
<number 1> of <number 2> - you are connected to <number 1> seeds/leechers and the tracker has reported that there are <number 2> in the swarm

Of course a torrent can have many trackers so in this case the 'best' one's scrape result is shown

**Comment by parg** [comment]
Yup - the 'best' scrape result is selected along the following lines:

If there are 'real' tracker results then these are preferred over DHT ones as they tend to be much more accurate. (that gets rid of the 2/30 returned by the mlDHT and 3/0 from the BiglyBT DDB)

Amongst these the result with the most leechers is preferred as this has more significance regarding seeding rules. This is where the '6 of 8' comes from. (well, those two rarbg trackers are actually the same one)

Normally it would go ahead and display '<n> of 3' from the same tracker. However, you are actually connected to 4 leechers so, rather than display something stupid like '4 of 3' it falls back to ignoring the 'of 3' part

Like I said, it is fairly complex but I think I improved it somewhat.

**Comment by NaPurHab** [comment]
Ok, as long as your happy with the result.  Only started this issue because that is what beta is all about. Find the bugs, but also the small issues. This one didn't make Biglybt work better, just look better.

**Comment by parg** [comment]
heh, I dunno, I didn't write this part of it :) At least now I think it shows the right kind of numbers - thanks for raising it!

**Comment by NaPurHab** [comment]
Would not be a good beta if I didn't raise issue large or small.  And I used to program databases, so I have an idea of how things work. And bring them up after I think them through. Like having the Enforce binding be able to pause all traffic, but also make it optional.  Have to consider the Good and the Bad that something can cause.  I have another idea, but I have to finish thinking it through and write it up.  Perhaps later tonight.  Thanks.

**Comment by TuxPaper** [comment]
fwiw, the seed/peer count column has always bothered me too.  In my personal source, I have my own code that picks the largest peer/seed numbers out of all the trackers.  It was a hack and still not a very accurate value, so I never committed it to svn.

More importantly though, I founds trackers are big fat liars when it comes to peer/seed counts.  It don't expect it's intentional, but just the way it is.  Honestly, I think the DHT or Mainline scrape values are probably the most accurate counts of real clients.

**Comment by NaPurHab** [comment]
I agree that the DHT and mlDHT are probably more LIVE.  Only thing would be to refine it with actual connection attempts.  But certainly DHT and mlDHT are more trust worthy.

**Comment by NaPurHab** [comment]
Looks like this is well discussed. So I here by close it.

**Comment by parg** [comment]
Not sure I agree about the DHT being a better source, from my experience it is stuffed full of bogon scrapers - never seen a torrent that only you know the hash for be flooded with Chinese peers? Also if you walk the Azureus DHT you will see a huge skew in peers that doesn't tie in with what I see in reality - here's a sample:

RU=300411, US=93183, UA=85237, GB=47822, CA=43907, AU=43740, FR=34885, KZ=25095, ES=22325, TR=20500, NL=13909, IT=12887...

Ukraine with the same number of users as the US?
