### ISSUE TITLE
Azureus transition

### ISSUE THREAD

**Issue by ViperCode7** [BiglySoftware/BiglyBT#9]
IDK how many of these there are, but -Dazureus.config.path remains, normally it should be -Dbiglybt.config.path in BiglyBT.exe.vmoptions ... in case anyone wants to make it "portable".

Also was wondering if I can transfer all of Az config folder to the new folder, will BiglyBT have any issues with that that are not visible?

**Comment by TuxPaper** [comment]
We kept all the -D parameters and config keys the same to save headaches.

Essentially, when you choose "Migrate" in the installer it copies your whole config directory, minus the plugins directory, to a BiglyBT directory.  It then renames `azureus.config` and `azureus.statistics` to `biglybt.*`, and installs clean versions of the plugins (from plugins.biglybt.com).  The trickiest step to do manually, is modifying downloads.config to makes sure the 'torrent' key points to the new config dir.  Since you are setting `azureus.config.path` anyway, the downloads.config should be correct (the 'torrent' key's value is `<azureus.config.path>/torrents/*`)

**Comment by ViperCode7** [comment]
Done. The downloads.config had no path reference to Vuze, so I left it as it was.
