### ISSUE TITLE
Allocation speed extremely slow

### ISSUE THREAD

**Issue by brazenvoid** [BiglySoftware/BiglyBT#930]
The usual allocation at the start of the torrent happens with good speed (75-100MBps) but when I add back some skipped files, it proceeds extremely slowly, like 0.1-4MBps slowly. I have even defragmented and checked my HDD for errors to no avail. This happens both while the torrent is active or in a stopped state.

* Windows 10 x64 1803
* BiglyBT Version 1.8.0_201 x64

**Comment by brazenvoid** [comment]
One thing more, if I initiate the inclusion while its in stopped state then the UI freezes and process goes into non-responsive state.

**Comment by parg** [comment]
File allocations happens in the same way regardless of when it occurs, so that doesn't make a whole lot of sense.

If you can reproduce the complete-hang issue then please try the following (when BiglyBT is not responding)

Go to a browser and enter

http://127.0.0.1:45100/setinfo?name=AZMSG&value=AZMSG;0;config;log-diags;;

(make sure you include the double ;; at the end of that)

If this 'page' loads then upload the debug_1.log / debug_2.log as this should contain some stack traces that might pinpoint the issue - these are in the 'logs' directory of the BiglyBT config folder (%appdata%\BiglyBT on Windows)

Other things to try:

* Join the beta program and see if the latest beta version fixes the problem (see the Help menu for details)

* Turn off file pre-allocation under Tools->Options->Files - make sure you change your 'Mode' setting to advanced.

**Comment by brazenvoid** [comment]
I didn't get the freeze anymore so I installed the beta. This exhibited a new behavior. Now whenever it rarely freezes, it allocates at full speed but when it does not, it slows down to <1MBps-13MBps. There is an improvement I guess.

I'll try turning off pre-allocation once I am very sure there is no other way.

**Comment by parg** [comment]
The beta also has sparse-file support that you might try turning on
