### ISSUE TITLE
Can't assign "Do Not Download" to some files

### ISSUE THREAD

**Issue by brazenvoid** [BiglySoftware/BiglyBT#953]
So some files can't be given DND priority for some reason and they get assigned "Delete" instead... Usually it occurs with files already marked delete before. Even if I first change it to any other downloadable priority, and then to DND. It still gets marked Delete. 

To fix this I have to mark it with any downloadable priority and wait till a piece gets downloaded, only then I can mark it DND.

For some reason it doesn't happen with most of the files. But when it happens, it happens for all files within a folder. Or perhaps that's a coincidence that I keep encountering...

I want to keep some files as DND till their availability reaches over 1 copy (For dying torrents). Its an organization tactic rather.

* Windows 10 x64 1803
* BiglyBT B35

**Comment by parg** [comment]
It is because there is an optimized storage mode under the covers called 'compact'. When you have a DND file the pieces that (most likely) overlap the start and end of the file still have to be downloaded in order to complete the previous/subsequent files. With a 'normal' DND file this results in the DND file still being created to hold that data. This can confuse the user and also, if you happen to have a file system that insists on reserving the full size of the file to support a few bytes at the end, space being used up.

The 'compact' mode was introduced to store the overlapping pieces in a separate location. Once set up in this way the mode persists until the file is marked as a normal priority and some data is downloaded at which point it is converted back to a 'normal' file.

The file is shown as 'delete' as an indicator that things are slightly different about the file - however it is really exactly the same as 'DND' and the two can be treated synonymously.

**Comment by brazenvoid** [comment]
I understand the compact and the start/end pieces logic. I am a long time torrent user.

What I wanted was to actually have those files allocated still as it is for DND. How can that be synonymous with 'Delete' which does not have the file allocated?

**Comment by brazenvoid** [comment]
Also when user clicks DND, it should change to that or show an error or info tooltip. Its counter-intuitive to have delete plastered instead...

**Comment by parg** [comment]
please accept my apologies for treating you so rudely

**Comment by brazenvoid** [comment]
> please accept my apologies for treating you so rudely

I didn't think it was rude. It is exactly I would have handled it. Other than that I am only requesting/suggesting. I am not angry. Sorry if I wrongly insinuated that.

When it assigns Delete, it resets the torrent, with almost dead torrents, it takes a long while for it to connect to other peers enough so I can again see the actual availability rating.

**Comment by brazenvoid** [comment]
Well I guess it is 'as designed' behavior. I'll just hold onto my mundane hope that any next file will not be one of those which will get delete instead of dnd, stopping the torrent and initiating a recheck... 

Thanks for your patience and time. I hope our next exchange will be more pleasant.

**Comment by parg** [comment]
I can see the issue but the area is a bit complex. I assume that your files are originally getting into a 'Delete' state because you unchecked the 'download' option in the dialog you get when adding a new torrent? As there is only a yes/no option here the mapping is to 'Normal/Delete'.

Would it be helpful to have an option for the unchecking of a file in that dialog to be treated as 'do not download' instead of 'delete'? Not sure how straight forward that would be but I can take a look.

Once a file is 'Delete' it does indeed stop/start the torrent when changing to 'Normal' as it requires a change in storage mode to make the transition and unfortunately this requires the restart. From 'DND' -> 'Normal' doesn't as the storage mode doesn't change.

**Comment by brazenvoid** [comment]
I really don't find the issue in having only Normal/Delete as options on startup. 

Having assigned 'Delete' without warning, to only some files, when user has explicitly assigned DND, is not an expected result. How I see it, not only it does function as expected, the user even gets punished with a torrent stop and recheck. 

Can't those files still get DND instead of Delete, just like other files do?

**Comment by brazenvoid** [comment]
If they can't then simply don't do it, perhaps couple it with the error beep or some other feedback. 

If delete is really the usual outcome why not show a confirmation dialog with the reasoning and buttons to proceed to assign delete or cancel the action. Perhaps it may even have a dialog disable check box.

**Comment by parg** [comment]
I'll change it so that when you select 'DND' it changes it to 'DND' and not 'Delete' if the file doesn't exist (and likewise Delete->DND will always work). Don't think it'll break anything...
