### ISSUE TITLE
Rendering issues on Windows

### ISSUE THREAD

**Issue by lislei** [BiglySoftware/BiglyBT#970]
I noticed the Support BiglyBT pop up isn't sized according to my display settings.
I believe this was working just fine until I added magnification to my windows display settings.
This is set to 150%. (yes i know it's a bit dorky, but I use it for projecting it to my tv:))

Here's what i get:
![bilde](https://user-images.githubusercontent.com/13136714/55255340-b04ecf80-525a-11e9-9435-35ca20314ff4.png)

It't doesn't resize, but when i scroll it there's some rendering issues happening at the right hand edge rendering it like this:
![bilde](https://user-images.githubusercontent.com/13136714/55255636-65818780-525b-11e9-836b-404bdcaf2fd3.png)

This rendering thing might or might not be related to #16.
 
Thank you for keeping up all the good work!
Cheers!

-------------
![bilde](https://user-images.githubusercontent.com/13136714/55256103-88606b80-525c-11e9-88af-70a755000d44.png)

Java 1.8.0_201 (64 bit)
  Oracle Corporation
c:\program files\java\jre1.8.0_201

SWT v4922, win32, zoom=100, dpi=144
Windows 10 v10.0, amd64 (64 bit)
B1.9.0.1_B01/4 az3

**Comment by TuxPaper** [comment]
99% likely it's the DPI stuff 
We have our donation window notify our java code to the required window size, and we obviously aren't applying the correct DPI adjustment

**Comment by Krad-dono** [comment]
I've the same issue with 4k monitor and 150% scaling but just to note - this bug is affecting OTHER pop ups.
See example below - even if you change size of delefe or new torrent window it will default again to the same small size.
![image](https://user-images.githubusercontent.com/19714490/58683352-cec96800-837c-11e9-8cdf-978089d8e725.png)
As well this bug breaks any notifications in bottom right corner:
![image](https://user-images.githubusercontent.com/19714490/58683446-1a7c1180-837d-11e9-9e6f-b9580ac2e71d.png)

![image](https://user-images.githubusercontent.com/19714490/58683503-52835480-837d-11e9-8a1a-20a11a93569b.png)

Java 1.8.0_181 (64 bit)
  Oracle Corporation
c:\program files\biglybt\jre

SWT v4922, win32, zoom=100, dpi=144
Windows 10 v10.0, amd64 (64 bit)
B2.0.0.0/4 az3

**Comment by TuxPaper** [comment]
bah, I forgot to look at these before the release.  Assigned it to myself so I remember!

**Comment by Krad-dono** [comment]
Any update when we can expect this fixed? Still is an issue...

**Comment by Krad-dono** [comment]
Writing again after more than a year... It is still a problem. Scaling is incorrect and every window looks smashed.... Maybe we can expect a fix for this?

> Java 1.8.0_202 (64 bit)
  Oracle Corporation
c:\program files\biglybt\jre

SWT v4930r7, win32, zoom=100, dpi=144
Windows 10 v10.0, amd64 (64 bit)
B2.5.0.0/4 az3

**Comment by jmcbassett** [comment]
I also have this issue, pop-ups are too small for the content and non resizeable.

<img width="246" alt="Bigly issue" src="https://user-images.githubusercontent.com/7431527/116276672-a327a600-a77c-11eb-9d4d-8fc99dd390f1.png">

**Comment by Krad-dono** [comment]
@TuxPaper  any timelines when this bug can be fixed? I still can't understand why it is still a thing in 2021...
